hefposten	SbSgMsConc	.chef.posten	.SbSgMsPersForg.SbSgMs
undeskanzler	SbSgMsProfConc	.bund.es.kanzler	.SbSgMs.Cm.SbSgMsProf
hefposten	SbSgMsConc	.chef.posten	.SbSgMsPersForg.SbSgMs
intergrund	SbSgMsConc	.hinter.grund	.AjRoot.SbSgMs
ffenbar	AjRootConc	.offen.bar	.AjRoot.AjRoot
llerdings	SbGeConc	.aller.dings	.AjQant.SbGe
ackenschlag	SbSgMsConc	.nacken.schlag	.SbSgMs.SbSgMs
ewissrecht	UnConc	.gewiss.recht	.AjRoot.SbSgNt
undesbahn	SbSgFmConc	.bund.es.bahn	.SbSgMs.Cm.SbSgFm
eilweise	UnConc	.teil.weise	.SbSgNt.SbSgFm
ffenbar	AjRootConc	.offen.bar	.AjRoot.AjRoot
eilweise	UnConc	.teil.weise	.SbSgNt.SbSgFm
undesbahn	SbSgFmConc	.bund.es.bahn	.SbSgMs.Cm.SbSgFm
kisprung	SbSgMsConc	.ski.sprung	.SbSgMs.SbSgMs
kisprung	SbSgMsConc	.ski.sprung	.SbSgMs.SbSgMs
eltcup	SbSgMsForg.EnConc	.welt.cup	.SbSgFm.SbSgMsForg.En
esamtweltcup	SbSgMsForg.EnConc	.gesamt.welt.cup	.AjRoot.SbSgFm.SbSgMsForg.En
