achstube	SbSgFmConc	.wach.s.tube	.AjRoot.Cm.SbSgFm
ernfahrer	SbSgMsConc	.fern.fahrer	.AjRoot.SbSgMs
ugenblick	SbSgMsConc	.auge.n.blick	.SbSgNtBody.Cm.SbSgMs
ahnhof	SbSgMsConc	.bahn.hof	.SbSgFm.SbSgMs
rundlos	AjRootConc	.grund.los	.SbSgMs.AjRoot
ischerblatt	SbSgNtBotaConc	.wischer.blatt	.SbSgMs.SbSgNtBota
ferdesattelknauf	SbSgMsConc	.pferd.e.sattel.knauf	.SbSgNtZool.Cm.SbSgMs.SbSgMs
andesamt	SbSgNtConc	.land.e.s.amt	.SbSgNt.Cm.Cm.SbSgNt
egenbogen	SbSgMsConc	.rege.n.bogen	.AjRoot.Cm.SbSgMs
achteile	SbSgFmConc	.nacht.eile	.SbSgFm.SbSgFm
egenwald	SbSgMsBotaConc	.rege.n.wald	.AjRoot.Cm.SbSgMsBota
ausarrest	SbSgMsConc	.hau.s.ar.rest	.SbSgMs.Cm.SbSgNtMeas.SbSgMs
ehnmal	SbSgNtFreqConc	.zeh.n.mal	.SbSgMs.Cm.SbSgNtFreq
eileibe	SbSgFmBotaConc	.beil.eibe	.SbSgNt.SbSgFmBota
esichtsausdruck	SbSgMsConc	.gesicht.s.au.s.druck	.SbSgNtBody.Cm.SbSgFm.Cm.SbSgMs
ltersteilzeit	SbSgFmConc	.alter.s.teil.zeit	.SbSgNt.Cm.SbSgNt.SbSgFm
iebenmal	SbSgNtFreqConc	.sieb.e.n.mal	.SbSgNt.Cm.Cm.SbSgNtFreq
