<?xml version="1.0" encoding="UTF-8"?>
<html>
<head><title>Colored Word Types</title>
<link rel="stylesheet" title="all"    type="text/css" href="all.css"    />
<link rel="stylesheet" title="vbav"   type="text/css" href="vbav.css"   />
<link rel="stylesheet" title="sbajar" type="text/css" href="sbajar.css" />
<link rel="stylesheet" title="nmnu"   type="text/css" href="nmnu.css"   />
<link rel="stylesheet" title="prcj"   type="text/css" href="prcj.css"   />
<link rel="stylesheet" title="puxy"   type="text/css" href="puxy.css"   />
<script type="text/javascript" src="javascript.js"></script>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body><h2>Colored Word Types</h2>


<span class="Pr" title="Pr">Nachdem</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Aj" title="AjQant">alle</span> <span class="Aj" title="AjQant|AjXP">diese</span> <span class="Sb" title="SbPl">Vorkehrungen</span> <span class="Vb" title="VbSPa0">getroffen</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbSIp11|VbSIp13|VbSCt11|VbSCt13">wollte</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Un" title="Un">nicht</span>
<span class="Aj" title="AjCmpr">länger</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">warten</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbSIn0|VbSIm91|PnSgPossNomvMs3|PnSgPossNomvNt3|PnSgPossAccvNt3">sein</span> <span class="Vb" title="VbRtWeak">Vorhaben</span> <span class="Pr" title="PrShor">ins</span> <span class="Sb" title="SbSgNt|SbSgNt">Werk</span> <span class="Pr" title="PrPrim">zu</span> <span class="Vb" title="VbRtWeak">setzen</span><span class="Pu" title="Pu">;</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Vb" title="VbPa1F">drängte</span> <span class="Pn" title="PnSgPersAccv3Ms">ihn</span>
<span class="Av" title="Av">dazu</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="SbSgMs|SbSgMs">Gedanke</span> <span class="Pr" title="PrPrim">an</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbSgFm">Entbehrung</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbSgFm|SbSgFm">Welt</span> <span class="Pr" title="Pr">durch</span> <span class="Vb" title="VbSIn0|VbSIm91|PnSgPossNomvMs3|PnSgPossNomvNt3|PnSgPossAccvNt3">sein</span>
<span class="Vb" title="VbRtWeak">Zögern</span> <span class="Vb" title="VbPr11">erleide</span><span class="Pu" title="Pu">,</span> <span class="Xy" title="Xy">derart</span> <span class="Vb" title="VbSIp91|VbSIp93">waren</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">Unbilden</span><span class="Pu" title="Pu">,</span> <span class="Pn" title="PnReltDatvPl">denen</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Pr" title="PrPrim">zu</span> <span class="Vb" title="VbRtWeak">steuern</span><span class="Pu" title="Pu">,</span>
<span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbPl">Ungerechtigkeiten</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Vb" title="VbSCs93|VbSCs91|VbSIm91|VbSPr93|VbSPr91|VbSIn0|VbSCs93|VbSCs91|VbSIm91|VbSPr93|VbSPr91|VbSIn0">zurechtzubringen</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">Ungebühr</span><span class="Pu" title="Pu">,</span>
<span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Vb" title="VbSCs93|VbSCs91|VbSIm91|VbSPr93|VbSPr91|VbSIn0">abzuhelfen</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">Mißbräuche</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Xy" title="Xy">wiedergutzumachen</span><span class="Pu" title="Pu">,</span>
<span class="Aj" title="AjRoot">kurz</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbPl|SbPl">Pflichten</span><span class="Pu" title="Pu">,</span> <span class="Pn" title="PnReltDatvPl">denen</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Pr" title="PrPrim">zu</span> <span class="Vb" title="VbRtWeak">genügen</span> <span class="Vb" title="VbSIp13|VbSIp11">gedachte</span><span class="Pu" title="Pu">.</span> <span class="Cj" title="Cj">Und</span> <span class="Pr" title="PrPrim">so</span><span class="Pu" title="Pu">,</span> <span class="Un" title="Un">ohne</span>
<span class="Xy" title="Xy">irgendeinem</span> <span class="Pr" title="PrPrim">von</span> <span class="Pn" title="PnSgPersGenv3Ms|PnSgPersGenv3Nt|PnSgPossGenvFm3|PnSgPossGenvPl3|PnSgPossDatvFm3">seiner</span> <span class="Xy" title="Xy">Absicht</span> <span class="Sb" title="SbSgFm|SbSgFm">Kunde</span> <span class="Pr" title="PrPrim">zu</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">geben</span> <span class="Cj" title="Cj">und</span> <span class="Un" title="Un">ohne</span> <span class="Ex" title="ExNrul|Cj">daß</span>
<span class="Pn" title="PnUndtNomv">jemand</span> <span class="Pn" title="PnSgPersAccv3Ms">ihn</span> <span class="Vb" title="VbSIp11|VbSIp13">sah</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbPa1F">bewehrte</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Pn" title="PnReflSg3|PnReflPl3">sich</span> <span class="Ar" title="ArUndtGenvSgMs|ArUndtGenvSgNt|PnUndtNomvNt">eines</span> <span class="Av" title="AvTime">Morgens</span> <span class="Pr" title="PrPrim">vor</span> <span class="Xy" title="Xy">Anbruch</span> <span class="Ar" title="ArDetmGenvSgMs|ArDetmGenvSgNt">des</span>
<span class="Sb" title="SbSgGe|SbSgGe">Tages</span> <span class="Pu" title="Pu">-</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Vb" title="VbSIp11|VbSIp13">war</span> <span class="Ar" title="ArUndtGenvSgFm|ArUndtDatvSgFm|PnUndtNomvMs">einer</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">heißen</span> <span class="Xy" title="Xy">Julitage</span> <span class="Pu" title="Pu">-</span> <span class="Pr" title="PrPrim">mit</span> <span class="Pn" title="PnSgPersGenv3Ms|PnSgPersGenv3Nt|PnSgPossGenvFm3|PnSgPossGenvPl3|PnSgPossDatvFm3">seiner</span> <span class="Aj" title="AjQant|AjXP|AjXP">ganzen</span>
<span class="Sb" title="SbSgFm">Rüstung</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbSIp11|VbSIp13">stieg</span> <span class="Pr" title="PrPrim">auf</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Nm" title="NmFmZool">Rosinante</span><span class="Pu" title="Pu">,</span> <span class="Pr" title="Pr">nachdem</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Pn" title="PnSgPossDatvPl3|PnSgPossAccvMs3">seinen</span>
<span class="Vb" title="VbPa1A">zusammengeflickten</span> <span class="Xy" title="Xy">Turnierhelm</span> <span class="Vb" title="VbIm92">aufgesetzt</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbPa1F">faßte</span> <span class="Pn" title="PnSgPossNomvFm3|PnSgPossNomvPl3|PnSgPossAccvFm3|PnSgPossAccvPl3">seine</span> <span class="Sb" title="SbSgFm|SbSgFm">Tartsche</span>
<span class="Pr" title="PrPrim">in</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Sb" title="SbSgMsBody|SbSgMsBody">Arm</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbSIp11|VbSIp13">nahm</span> <span class="Pn" title="PnSgPossDatvPl3|PnSgPossAccvMs3">seinen</span> <span class="Sb" title="SbSgMs|SbSgMs">Speer</span> <span class="Cj" title="Cj">und</span> <span class="Vb" title="VbSIp11|VbSIp13">zog</span> <span class="Pr" title="Pr">durch</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">Hinterpforte</span>
<span class="Pn" title="PnSgPossGenvMs3|PnSgPossGenvNt3">seines</span> <span class="Sb" title="SbSgGe|SbSgGe">Hofes</span> <span class="Pr" title="Pr">hinaus</span> <span class="Pr" title="PrShor">aufs</span> <span class="Sb" title="SbSgNt|SbSgNt">Feld</span><span class="Pu" title="Pu">,</span> <span class="Pr" title="PrPrim">mit</span> <span class="Aj" title="AjXC|AjXP|AjXC|AjXP">gewaltiger</span> <span class="Sb" title="SbSgFm">Befriedigung</span> <span class="Cj" title="Cj">und</span>
<span class="Xy" title="Xy">Herzensfreude</span> <span class="Av" title="AvModlAnct">darob</span><span class="Pu" title="Pu">,</span> <span class="Pr" title="PrPrim">mit</span> <span class="Ir" title="IrPrim">wie</span> <span class="Aj" title="AjXP">großer</span> <span class="Sb" title="SbSgFm">Leichtigkeit</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Vb" title="VbSIn0|VbSIm91|PnSgPossNomvMs3|PnSgPossNomvNt3|PnSgPossAccvNt3">sein</span>
<span class="Aj" title="AjXP|AjXP">löbliches</span> <span class="Vb" title="VbRtWeak">Vorhaben</span> <span class="Vb" title="VbSCt93|VbSCt91">auszuführen</span> <span class="Vb" title="VbSPa0">begonnen</span><span class="Pu" title="Pu">.</span>
<br /><br />Morphems: <span class="Aj">Aj</span> 8
<span class="Ar">Ar</span> 19
<span class="Av">Av</span> 3
<span class="Cj">Cj</span> 4
<span class="Ex">Ex</span> 1
<span class="Ir">Ir</span> 1
<span class="Nm">Nm</span> 1
<span class="Pn">Pn</span> 24
<span class="Pr">Pr</span> 20
<span class="Pu">Pu</span> 26
<span class="Sb">Sb</span> 17
<span class="Un">Un</span> 3
<span class="Vb">Vb</span> 31
<span class="Xy">Xy</span> 12
<br />
<strong>92.9%</strong> = 158 recognized and 12 unknown out of 170 total words<br />
Highlight: <a href="#" title="Click to switch" onclick="activateStyles('all');    return false;">all found</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('vbav');   return false;">Vb+Av</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('sbajar'); return false;">Sb+Aj+Ar</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('nmnu');   return false;">Nm+Nu</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('prcj');   return false;">Pr+Cj+Cc+Un</a> 
<a href="#" title="Click to switch" onclick="activateStyles('puxy');   return false;">Pu+Xy</a> 
<br />
</body></html>