<?xml version="1.0" encoding="UTF-8"?>
<html>
<head><title>Colored Word Types</title>
<link rel="stylesheet" title="all"    type="text/css" href="all.css"    />
<link rel="stylesheet" title="vbav"   type="text/css" href="vbav.css"   />
<link rel="stylesheet" title="sbajar" type="text/css" href="sbajar.css" />
<link rel="stylesheet" title="nmnu"   type="text/css" href="nmnu.css"   />
<link rel="stylesheet" title="prcj"   type="text/css" href="prcj.css"   />
<link rel="stylesheet" title="puxy"   type="text/css" href="puxy.css"   />
<script type="text/javascript" src="javascript.js"></script>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body><h2>Colored Word Types</h2>


<span class="Pr" title="r">Nachdem</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Aj" title="jQant">alle</span> <span class="Aj" title="jQant|AjXP">diese</span> <span class="Sb" title="bPl">Vorkehrungen</span> <span class="Vb" title="bSPa0">getroffen</span><span class="Pu" title="u">,</span> <span class="Vb" title="bSIp11|VbSIp13|VbSCt11|VbSCt13">wollte</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Un" title="n">nicht</span>
<span class="Aj" title="jCmpr">länger</span> <span class="Vb" title="bSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">warten</span><span class="Pu" title="u">,</span> <span class="Vb" title="bSIn0|VbSIm91|PnSgPossNomvMs3|PnSgPossNomvNt3|PnSgPossAccvNt3">sein</span> <span class="Vb" title="bRtWeak">Vorhaben</span> <span class="Pr" title="rShor">ins</span> <span class="Sb" title="bSgNt|SbSgNt">Werk</span> <span class="Pr" title="rPrim">zu</span> <span class="Vb" title="bRtWeak">setzen</span><span class="Pu" title="u">;</span> <span class="Pn" title="nSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Vb" title="bPa1F">drängte</span> <span class="Pn" title="nSgPersAccv3Ms">ihn</span>
<span class="Av" title="v">dazu</span> <span class="Ar" title="rDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="bSgMs|SbSgMs">Gedanke</span> <span class="Pr" title="rPrim">an</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="bSgFm">Entbehrung</span><span class="Pu" title="u">,</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="bSgFm|SbSgFm">Welt</span> <span class="Pr" title="r">durch</span> <span class="Vb" title="bSIn0|VbSIm91|PnSgPossNomvMs3|PnSgPossNomvNt3|PnSgPossAccvNt3">sein</span>
<span class="Vb" title="bRtWeak">Zögern</span> <span class="Vb" title="bPr11">erleide</span><span class="Pu" title="u">,</span> <span class="Xy" title="y">derart</span> <span class="Vb" title="bSIp91|VbSIp93">waren</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="y">Unbilden</span><span class="Pu" title="u">,</span> <span class="Pn" title="nReltDatvPl">denen</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Pr" title="rPrim">zu</span> <span class="Vb" title="bRtWeak">steuern</span><span class="Pu" title="u">,</span>
<span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="bPl">Ungerechtigkeiten</span><span class="Pu" title="u">,</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Vb" title="bSCs93|VbSCs91|VbSIm91|VbSPr93|VbSPr91|VbSIn0|VbSCs93|VbSCs91|VbSIm91|VbSPr93|VbSPr91|VbSIn0">zurechtzubringen</span><span class="Pu" title="u">,</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="y">Ungebühr</span><span class="Pu" title="u">,</span>
<span class="Ar" title="rDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Vb" title="bSCs93|VbSCs91|VbSIm91|VbSPr93|VbSPr91|VbSIn0">abzuhelfen</span><span class="Pu" title="u">,</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="y">Mißbräuche</span><span class="Pu" title="u">,</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Xy" title="y">wiedergutzumachen</span><span class="Pu" title="u">,</span>
<span class="Aj" title="jRoot">kurz</span><span class="Pu" title="u">,</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="bPl|SbPl">Pflichten</span><span class="Pu" title="u">,</span> <span class="Pn" title="nReltDatvPl">denen</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Pr" title="rPrim">zu</span> <span class="Vb" title="bRtWeak">genügen</span> <span class="Vb" title="bSIp13|VbSIp11">gedachte</span><span class="Pu" title="u">.</span> <span class="Cj" title="j">Und</span> <span class="Pr" title="rPrim">so</span><span class="Pu" title="u">,</span> <span class="Un" title="n">ohne</span>
<span class="Xy" title="y">irgendeinem</span> <span class="Pr" title="rPrim">von</span> <span class="Pn" title="nSgPersGenv3Ms|PnSgPersGenv3Nt|PnSgPossGenvFm3|PnSgPossGenvPl3|PnSgPossDatvFm3">seiner</span> <span class="Xy" title="y">Absicht</span> <span class="Sb" title="bSgFm|SbSgFm">Kunde</span> <span class="Pr" title="rPrim">zu</span> <span class="Vb" title="bSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">geben</span> <span class="Cj" title="j">und</span> <span class="Un" title="n">ohne</span> <span class="Ex" title="xNrul|Cj">daß</span>
<span class="Pn" title="nUndtNomv">jemand</span> <span class="Pn" title="nSgPersAccv3Ms">ihn</span> <span class="Vb" title="bSIp11|VbSIp13">sah</span><span class="Pu" title="u">,</span> <span class="Vb" title="bPa1F">bewehrte</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Pn" title="nReflSg3|PnReflPl3">sich</span> <span class="Ar" title="rUndtGenvSgMs|ArUndtGenvSgNt|PnUndtNomvNt">eines</span> <span class="Av" title="vTime">Morgens</span> <span class="Pr" title="rPrim">vor</span> <span class="Xy" title="y">Anbruch</span> <span class="Ar" title="rDetmGenvSgMs|ArDetmGenvSgNt">des</span>
<span class="Sb" title="bSgGe|SbSgGe">Tages</span> <span class="Pu" title="u">-</span> <span class="Pn" title="nSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Vb" title="bSIp11|VbSIp13">war</span> <span class="Ar" title="rUndtGenvSgFm|ArUndtDatvSgFm|PnUndtNomvMs">einer</span> <span class="Ar" title="rDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Vb" title="bSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">heißen</span> <span class="Xy" title="y">Julitage</span> <span class="Pu" title="u">-</span> <span class="Pr" title="rPrim">mit</span> <span class="Pn" title="nSgPersGenv3Ms|PnSgPersGenv3Nt|PnSgPossGenvFm3|PnSgPossGenvPl3|PnSgPossDatvFm3">seiner</span> <span class="Aj" title="jQant|AjXP|AjXP">ganzen</span>
<span class="Sb" title="bSgFm">Rüstung</span><span class="Pu" title="u">,</span> <span class="Vb" title="bSIp11|VbSIp13">stieg</span> <span class="Pr" title="rPrim">auf</span> <span class="Ar" title="rDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Nm" title="mFmZool">Rosinante</span><span class="Pu" title="u">,</span> <span class="Pr" title="r">nachdem</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Pn" title="nSgPossDatvPl3|PnSgPossAccvMs3">seinen</span>
<span class="Vb" title="bPa1A">zusammengeflickten</span> <span class="Xy" title="y">Turnierhelm</span> <span class="Vb" title="bIm92">aufgesetzt</span><span class="Pu" title="u">,</span> <span class="Vb" title="bPa1F">faßte</span> <span class="Pn" title="nSgPossNomvFm3|PnSgPossNomvPl3|PnSgPossAccvFm3|PnSgPossAccvPl3">seine</span> <span class="Sb" title="bSgFm|SbSgFm">Tartsche</span>
<span class="Pr" title="rPrim">in</span> <span class="Ar" title="rDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Sb" title="bSgMsBody|SbSgMsBody">Arm</span><span class="Pu" title="u">,</span> <span class="Vb" title="bSIp11|VbSIp13">nahm</span> <span class="Pn" title="nSgPossDatvPl3|PnSgPossAccvMs3">seinen</span> <span class="Sb" title="bSgMs|SbSgMs">Speer</span> <span class="Cj" title="j">und</span> <span class="Vb" title="bSIp11|VbSIp13">zog</span> <span class="Pr" title="r">durch</span> <span class="Ar" title="rDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="y">Hinterpforte</span>
<span class="Pn" title="nSgPossGenvMs3|PnSgPossGenvNt3">seines</span> <span class="Sb" title="bSgGe|SbSgGe">Hofes</span> <span class="Pr" title="r">hinaus</span> <span class="Pr" title="rShor">aufs</span> <span class="Sb" title="bSgNt|SbSgNt">Feld</span><span class="Pu" title="u">,</span> <span class="Pr" title="rPrim">mit</span> <span class="Aj" title="jXC|AjXP|AjXC|AjXP">gewaltiger</span> <span class="Sb" title="bSgFm">Befriedigung</span> <span class="Cj" title="j">und</span>
<span class="Xy" title="y">Herzensfreude</span> <span class="Av" title="vModlAnct">darob</span><span class="Pu" title="u">,</span> <span class="Pr" title="rPrim">mit</span> <span class="Ir" title="rPrim">wie</span> <span class="Aj" title="jXP">großer</span> <span class="Sb" title="bSgFm">Leichtigkeit</span> <span class="Pn" title="nSgPersNomvMs3">er</span> <span class="Vb" title="bSIn0|VbSIm91|PnSgPossNomvMs3|PnSgPossNomvNt3|PnSgPossAccvNt3">sein</span>
<span class="Aj" title="jXP|AjXP">löbliches</span> <span class="Vb" title="bRtWeak">Vorhaben</span> <span class="Vb" title="bSCt93|VbSCt91">auszuführen</span> <span class="Vb" title="bSPa0">begonnen</span><span class="Pu" title="u">.</span>
<br /><br />Morphems: <span class="Aj">Aj</span> 8
<span class="Ar">Ar</span> 19
<span class="Av">Av</span> 3
<span class="Cj">Cj</span> 4
<span class="Ex">Ex</span> 1
<span class="Ir">Ir</span> 1
<span class="Nm">Nm</span> 1
<span class="Pn">Pn</span> 24
<span class="Pr">Pr</span> 20
<span class="Pu">Pu</span> 26
<span class="Sb">Sb</span> 17
<span class="Un">Un</span> 3
<span class="Vb">Vb</span> 31
<span class="Xy">Xy</span> 12
<br />
<strong>92.9%</strong> = 158 recognized and 12 unknown out of 170 total words<br />
Highlight: <a href="#" title="Click to switch" onclick="activateStyles('all');    return false;">all found</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('vbav');   return false;">Vb+Av</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('sbajar'); return false;">Sb+Aj+Ar</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('nmnu');   return false;">Nm+Nu</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('prcj');   return false;">Pr+Cj+Cc+Un</a> 
<a href="#" title="Click to switch" onclick="activateStyles('puxy');   return false;">Pu+Xy</a> 
<br />
</body></html>