<?xml version="1.0" encoding="UTF-8"?>
<html><head><title>Colored Word Types</title>
<link rel="stylesheet" title="all"    type="text/css" href="all.css"    />
<link rel="stylesheet" title="vbav"   type="text/css" href="vbav.css"   />
<link rel="stylesheet" title="sbajar" type="text/css" href="sbajar.css" />
<link rel="stylesheet" title="nmnu"   type="text/css" href="nmnu.css"   />
<link rel="stylesheet" title="prcj"   type="text/css" href="prcj.css"   />
<link rel="stylesheet" title="puxy"   type="text/css" href="puxy.css"   />
<script type="text/javascript" src="javascript.js"></script> /
<body><h2>Colored Word Types</h2>

<span class="Pu" title="Pu">-</span> <span class="Ab" title="AbSbFm">EU</span> <span class="Vb" title="VbSPr11|VbSPr13|VbSIm12">will</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Aj" title="AjXP">deutschen</span> <span class="Xy" title="Xy">Kandidaten</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span><span class="Pu" title="Pu">-</span><span class="Nm" title="NmFmGeogFlum|NmFmGeogFlum">Weser</span> <span class="Pr" title="PrPrim">als</span> <span class="Sb" title="SbSgMsPersForg|SbSgMsPersForg">Chef</span> <span class="Ar" title="ArDetmGenvSgMs|ArDetmGenvSgNt">des</span> <span class="Xy" title="Xy">IWF</span>

<span class="Nm" title="NmGeogCity">Porto</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Aj" title="AjXP">Europaeische</span> <span class="Sb" title="SbSgFm">Union</span> <span class="Ex" title="ExUE|VbSPr13">haelt</span> <span class="Pr" title="PrShor">am</span> <span class="Aj" title="AjXP">deutschen</span> <span class="Xy" title="Xy">Kandidaten</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span><span class="Pu" title="Pu">-</span><span class="Nm" title="NmFmGeogFlum|NmFmGeogFlum">Weser</span> <span class="Ex" title="ExUE|PrPrim">fuer</span>
<span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Xy" title="Xy">Chefposten</span> <span class="Ar" title="ArDetmGenvSgMs|ArDetmGenvSgNt">des</span> <span class="Aj" title="AjXP">Internationalen</span> <span class="Xy" title="Xy">Waehrungsfonds</span> <span class="Aj" title="AjRoot">fest</span><span class="Pu" title="Pu">.</span> <span class="Aj" title="AjQant">Dies</span> <span class="Vb" title="VbPa1F">erklaerte</span>
<span class="Nm" title="NmGeogCtry">Portugals</span> <span class="Sb" title="SbSgMsProf">Regierungschef</span> <span class="Xy" title="Xy">Guiterrez</span> <span class="Pr" title="PrPrim">als</span> <span class="Vb" title="VbGe1M">amtierender</span> <span class="Ab" title="AbSbFm">EU</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Ratspraesident</span><span class="Pu" title="Pu">.</span>
<span class="Xy" title="Xy">Guiterrez</span> <span class="Vb" title="VbSIp11|VbSIp13">hatte</span> <span class="Pr" title="Pr">zuvor</span> <span class="Pr" title="PrPrim">mit</span> <span class="Sb" title="SbSgMsProf">Bundeskanzler</span> <span class="Nm" title="NmPersSurn">Schroeder</span> <span class="Vb" title="VbSPa0">gesprochen</span><span class="Pu" title="Pu">.</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span><span class="Pu" title="Pu">-</span><span class="Nm" title="NmFmGeogFlum|NmFmGeogFlum">Weser</span> <span class="Vb" title="VbSIp11|VbSIp13">hatte</span>
<span class="Pr" title="PrPrim">bei</span> <span class="Ar" title="ArUndtGenvSgFm|ArUndtDatvSgFm|PnUndtNomvMs">einer</span> <span class="Sb" title="SbSgFm">Testabstimmung</span> <span class="Pr" title="PrShor">im</span> <span class="Xy" title="Xy">Waehrungsfonds</span> <span class="Aj" title="AjQant|AjXP">keine</span> <span class="Xy" title="Xy">absolute</span> <span class="Sb" title="SbSgFm">Mehrheit</span> <span class="Vb" title="VbRtWeak">erhalten</span><span class="Pu" title="Pu">.</span>
<span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Ab" title="AbSbFm">USA</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">wollen</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span><span class="Pu" title="Pu">-</span><span class="Nm" title="NmFmGeogFlum|NmFmGeogFlum">Weser</span> <span class="Un" title="Un">nicht</span> <span class="Pr" title="PrPrim">auf</span> <span class="Aj" title="AjQant|AjXP">diesem</span> <span class="Xy" title="Xy">Chefposten</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">haben</span><span class="Pu" title="Pu">,</span> <span class="Xy" title="Xy">Hintergrund</span> <span class="Vb" title="VbSPr13">ist</span>
<span class="Ar" title="ArUndtNomvSgMs|ArUndtNomvSgNt|ArUndtAccvSgNt">ein</span> <span class="Xy" title="Xy">Richtungsstreit</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Ab" title="AbSbFm">USA</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">wollen</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="CjPrim|ExUE|ExNrul">dass</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Xy" title="Xy">IWF</span> <span class="Pr" title="PrPrim">weiter</span> <span class="Ar" title="ArUndtAccvSgMs|PnUndtAccv">einen</span> <span class="Aj" title="AjRoot">strikt</span>
<span class="Aj" title="AjXP">marktwirtschaftlichen</span> <span class="Sb" title="SbSgMs|SbSgMs">Kurs</span> <span class="Xy" title="Xy">beibehaelt</span> <span class="Cj" title="Cj">und</span> <span class="Pr" title="PrPrim">bei</span> <span class="Xy" title="Xy">Waehrungskrisen</span> <span class="Un" title="Un">ohne</span>
<span class="Aj" title="AjXP">sozilpolitische</span> <span class="Aj" title="AjXP">Ruecksichten</span> <span class="Vb" title="VbIm92">handelt</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Sb" title="SbPl|SbPl">Chancen</span> <span class="Ex" title="ExUE|PrPrim">fuer</span> <span class="Sb" title="SbSgNt">Merkel</span> <span class="Pr" title="PrPrim">auf</span> <span class="Sb" title="SbSgMs|SbSgMs|SbPl|SbPl">Posten</span> <span class="Ar" title="ArDetmGenvSgMs|ArDetmGenvSgNt">des</span> <span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Vorsitzes</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">steigen</span>

<span class="Sb" title="SbSgFmProf">Berlin</span><span class="Pu" title="Pu">.</span> <span class="Nm" title="NmMsPren|NmMsPren|SbSgMsPers|SbSgMsPers">Volker</span> <span class="Xy" title="Xy">Ruehe</span> <span class="Vb" title="VbSPr11|VbSPr13|VbSIm12">will</span> <span class="Un" title="Un">nicht</span> <span class="Ex" title="ExUE|PrPrim">fuer</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Sb" title="SbSgMs|SbSgMs|SbPl|SbPl">Posten</span> <span class="Ar" title="ArDetmGenvSgMs|ArDetmGenvSgNt">des</span> <span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">-</span><span class="Vb" title="VbGe1A">Vorsitzenden</span>
<span class="Vb" title="VbRtWeak">kandidieren</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgNt|ArDetmAccvSgNt|PnReltNomvSgNt|PnReltAccvSgNt">Das</span> <span class="Vb" title="VbSPr13">hat</span> <span class="Xy" title="Xy">Ruehe</span> <span class="Pr" title="PrPrim">in</span> <span class="Ar" title="ArUndtDatvSgMs|ArUndtDatvSgNt|PnUndtDatv">einem</span> <span class="Xy" title="Xy">Interview</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="SbSgFm|SbSgFm">Welt</span> <span class="Pr" title="PrShor">am</span> <span class="Sb" title="SbSgMsTimeWeek.7">Sonntag</span> <span class="Vb" title="VbIm92">gesagt</span><span class="Pu" title="Pu">.</span>
<span class="Aj" title="AjXP">Gleichzeitig</span> <span class="Vb" title="VbPa1F">wiederholte</span> <span class="Xy" title="Xy">Ruehe</span> <span class="Pn" title="PnSgPossNomvFm3|PnSgPossNomvPl3|PnSgPossAccvFm3|PnSgPossAccvPl3">seine</span> <span class="Sb" title="SbSgFm">Forderung</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="CjPrim|ExUE|ExNrul">dass</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Aj" title="AjXP">kuenftige</span> <span class="Sb" title="SbSgMsProf">Parteichef</span>
<span class="Ar" title="ArUndtNomvSgMs|ArUndtNomvSgNt|ArUndtAccvSgNt">ein</span> <span class="Xy" title="Xy">Ministerpraesident</span> <span class="Vb" title="VbSIn0|VbSIm91|PnSgPossNomvMs3|PnSgPossNomvNt3|PnSgPossAccvNt3">sein</span> <span class="Vb" title="VbSCs11|VbSCs13">solle</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">Der</span> <span class="Aj" title="AjXP">ehemalige</span> <span class="Xy" title="Xy">Verteidigungsminister</span> <span class="Vb" title="VbIm92">setzt</span>
<span class="Pr" title="PrPrim">auf</span> <span class="Ar" title="ArUndtNomvSgFm|ArUndtAccvSgFm|PnUndtNomvFm">eine</span> <span class="Sb" title="SbSgFm">Kandidatur</span> <span class="Pr" title="PrPrim">von</span> <span class="Sb" title="SbSgGe|SbSgGe|SbSgGe|SbSgGe">Sachsens</span> <span class="Xy" title="Xy">Regierungspraesident</span> <span class="Nm" title="NmGeogCity.De">Biedenkopf</span> <span class="Pr" title="PrPrim">um</span> <span class="Ar" title="ArUndtAccvSgMs|PnUndtAccv">einen</span>
<span class="Xy" title="Xy">Erfolg</span> <span class="Pr" title="PrPrim">von</span> <span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Generalsekretaerin</span> <span class="Nm" title="NmPersPrenFm">Angela</span> <span class="Sb" title="SbSgNt">Merkel</span> <span class="Pr" title="PrPrim">zu</span> <span class="Vb" title="VbRtWeak">verhindern</span><span class="Pu" title="Pu">.</span> <span class="Aj" title="AjXP">Ruehes</span> <span class="Xy" title="Xy">Rueckzug</span>
<span class="Vb" title="VbSIm12">muss</span> <span class="Av" title="Av">daher</span> <span class="Pr" title="PrPrim">als</span> <span class="Aj" title="AjXP|AjXP">taktisches</span> <span class="Xy" title="Xy">Manoever</span> <span class="Vb" title="VbIm92">gewertet</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">werden</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="CjPrim">da</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Aj" title="AjXP">offenbar</span> <span class="Pr" title="PrPrim">bei</span> <span class="Ar" title="ArUndtDatvSgMs|ArUndtDatvSgNt|PnUndtDatv">einem</span>
<span class="Sb" title="SbSgNtForg|SbSgNtForg">Duell</span> <span class="Av" title="AvMove|PrPrim">gegen</span> <span class="Sb" title="SbSgNt">Merkel</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Xy" title="Xy">Kuerzeren</span> <span class="Vb" title="VbSIp91|VbSIp93|VbSCt91|VbSCt93|VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">ziehen</span> <span class="Ex" title="ExUE|VbSCt11|ExUE|VbSCt13">wuerde</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Vb" title="VbRtWeak">Umfragen</span> <span class="Vb" title="VbRtWeak">belegen</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">es</span><span class="Pu" title="Pu">.</span> <span class="Cj" title="CjPrim">Doch</span>
<span class="Av" title="AvLoct|AvLoct">innerhalb</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Ab" title="AbSbFm">CDU</span> <span class="Vb" title="VbSPr13">gibt</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Vb" title="VbSCt13|VbSCt11|AjXP">erhebliche</span> <span class="Xy" title="Xy">Widerstaende</span> <span class="Av" title="AvMove|PrPrim">gegen</span> <span class="Ar" title="ArUndtNomvSgFm|ArUndtAccvSgFm|PnUndtNomvFm">eine</span> <span class="Sb" title="SbSgFm">Uebergangsloesung</span>
<span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Un" title="Un">etwa</span> <span class="Ex" title="ExUE|NmGeogRegn.De">Thueringens</span> <span class="Xy" title="Xy">Ministerpraesident</span> <span class="Sb" title="SbSgMsZool|SbSgMsZool">Vogel</span> <span class="Cj" title="Cj">und</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Aj" title="AjXP">nordrheinwestfaelische</span>
<span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">-</span><span class="Vb" title="VbGe1F">Vorsitzende</span> <span class="Xy" title="Xy">Ruettgers</span> <span class="Xy" title="Xy">unisono</span> <span class="Vb" title="VbRtWeak">ablehnen</span><span class="Pu" title="Pu">.</span> <span class="Pr" title="Pr">Nachdem</span> <span class="Nm" title="NmMsPren|NmMsPren|SbSgMsPers|SbSgMsPers">Volker</span> <span class="Xy" title="Xy">Ruehe</span> <span class="Pr" title="PrPrim">auf</span> <span class="Ar" title="ArUndtNomvSgFm|ArUndtAccvSgFm|PnUndtNomvFm">eine</span>
<span class="Sb" title="SbSgFm">Kanditatur</span> <span class="Ex" title="ExUE|PrPrim">fuer</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">-</span><span class="Vb" title="VbSIm12">Vorsitz</span> <span class="Vb" title="VbIm92">verzichtet</span> <span class="Vb" title="VbSPr13">hat</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">steigen</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbPl|SbPl">Chancen</span> <span class="Pr" title="PrPrim">von</span> <span class="Nm" title="NmPersPrenFm">Angela</span>
<span class="Sb" title="SbSgNt">Merkel</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArUndtNomvSgMs|ArUndtNomvSgNt|ArUndtAccvSgNt">Ein</span> <span class="Vb" title="VbPa1M">Vertrauter</span> <span class="Ar" title="ArDetmGenvSgMs|ArDetmGenvSgNt">des</span> <span class="Aj" title="AjXP">saechsischen</span> <span class="Xy" title="Xy">Ministerpraesidenten</span> <span class="Nm" title="NmGeogCity.De">Biedenkopf</span>
<span class="Vb" title="VbPa1F">deutete</span> <span class="Pr" title="PrPrim">an</span><span class="Pu" title="Pu">,</span> <span class="Un" title="Un">auch</span> <span class="Nm" title="NmGeogCity.De">Biedenkopf</span> <span class="Vb" title="VbSIm12|VbSCs11|VbSCs13">sei</span> <span class="Pr" title="PrPrim">mit</span> <span class="Ar" title="ArUndtGenvSgFm|ArUndtDatvSgFm|PnUndtNomvMs">einer</span> <span class="Vb" title="VbGe1A">Vorsitzenden</span> <span class="Sb" title="SbSgNt">Merkel</span> <span class="Vb" title="VbSPa0|VbSIp93|VbSIp91|VbSIp93|VbSIp91">einverstanden</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Aj" title="AjXP">Hessische</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Vb" title="VbIm92">entscheidet</span> <span class="Pn" title="PnReflSg3|PnReflPl3">sich</span> <span class="Pr" title="PrPrim">auf</span> <span class="Xy" title="Xy">Parteitag</span> <span class="Ex" title="ExUE|PrPrim">fuer</span> <span class="Vb" title="VbSIm12">Erhalt</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="SbSgFm|SbSgFm">Koalition</span>

<span class="Nm" title="NmGeogCity.De">Rothenburg</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Aj" title="AjXP">hessische</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Vb" title="VbIm92">diskutiert</span> <span class="Pr" title="PrPrim">auf</span> <span class="Pn" title="PnSgPossDatvMs3|PnPlPossDatvMs3|PnSgPossDatvNt3|PnPlPossDatvNt3">ihrem</span> <span class="Xy" title="Xy">Parteitag</span> <span class="Ex" title="ExUE|PrPrim">ueber</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span>
<span class="Sb" title="SbSgFm|SbSgFm">Koalition</span> <span class="Pr" title="PrPrim">mit</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Vb" title="VbSPr13|VbSPr92|VbSIm92|VbSCs92">steht</span> <span class="Pr" title="PrPrim">weiter</span> <span class="Pr" title="PrPrim">zu</span> <span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Ministerpraesident</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span><span class="Pu" title="Pu">.</span>
<span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">Der</span> <span class="Aj" title="AjXP">ausserordentliche</span> <span class="Xy" title="Xy">Parteitag</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Aj" title="AjXP">Liberalen</span> <span class="Vb" title="VbPa1F">lehnte</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Pr" title="PrPrim">mit</span> <span class="Nu" title="Nu">166</span> <span class="Pr" title="PrPrim">zu</span> <span class="Nu" title="Nu">132</span> <span class="Vb" title="VbRtWeak">Stimmen</span>
<span class="Pr" title="PrPrim">ab</span><span class="Pu" title="Pu">,</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span> <span class="Cj" title="CjPrim">wegen</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Ab" title="AbSbFm">CDU</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Schwarzgeldaffaire</span> <span class="Pr" title="PrShor">zum</span> <span class="Vb" title="VbSIm12|VbSPr13|VbSIp13|VbSIp11">Ruecktritt</span> <span class="Vb" title="VbRtWeak">aufzufordern</span><span class="Pu" title="Pu">.</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">Es</span> <span class="Vb" title="VbSIp11|VbSIp13">war</span>
<span class="Cj" title="CjPrim">zwar</span> <span class="Aj" title="AjRoot">knapp</span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbSPr13">hat</span> <span class="Cj" title="Cj">aber</span> <span class="Ex" title="ExUE|PrPrim">fuer</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbSgFm|SbSgFm">Koalition</span> <span class="Pr" title="PrPrim">in</span> <span class="Nm" title="NmGeogCity.De">Wiesbaden</span> <span class="Cj" title="Cj">und</span> <span class="Ex" title="ExUE|PrPrim">fuer</span>
<span class="Xy" title="Xy">Ministerpraesident</span> <span class="Nm" title="NmPersPrenMs">Roland</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span> <span class="Vb" title="VbIm92">gereicht</span><span class="Pu" title="Pu">.</span> <span class="Pr" title="PrPrim">Nach</span> <span class="Aj" title="AjXC|AjXP|AjXC|AjXP">fuenfstuendiger</span> <span class="Sb" title="SbSgFm">Beratung</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">haben</span>
<span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Vb" title="VbPa1A">Delegierten</span> <span class="Vb" title="VbSCt93|VbSCt91|VbSIp93|VbSIp91">entschieden</span><span class="Pu" title="Pu">,</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Vb" title="VbSPr13">wird</span> <span class="Nm" title="NmPersPrenMs">Roland</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span> <span class="Un" title="Un">nicht</span> <span class="Pr" title="PrShor">zum</span> <span class="Vb" title="VbSIm12|VbSPr13|VbSIp13|VbSIp11">Ruecktritt</span>
<span class="Vb" title="VbRtWeak">auffordern</span><span class="Pu" title="Pu">.</span> <span class="Av" title="AvModl|Cj">Allerdings</span> <span class="Pr" title="PrPrim">in</span> <span class="Ar" title="ArUndtDatvSgMs|ArUndtDatvSgNt|PnUndtDatv">einem</span> <span class="Pr" title="Pr">zuvor</span> <span class="Vb" title="VbPa1A">verabschiedeten</span> <span class="Vb" title="VbSIm12">Antrag</span> <span class="Ex" title="ExUE|VbSPr12|ExUE|VbSPr13|ExUE|VbSPr92|ExUE|VbSIm92|ExUE|VbSCs92">heisst</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Un" title="Un">auch</span><span class="RelCl"><span class="Pu" title="Pu">,</span>
<span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Ab" title="AbSbFm">CDU</span> <span class="Vb" title="VbSIm12">muss</span> <span class="Sb" title="SbPl">Konsequenzen</span> <span class="Vb" title="VbSIp91|VbSIp93|VbSCt91|VbSCt93|VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">ziehen</span></span><span class="Pu" title="Pu">,</span> <span class="Vb" title="VbSPr11|VbSPr13|VbSIm12">darf</span> <span class="Un" title="Un">nicht</span> <span class="Aj" title="AjQant">einfach</span> <span class="Pr" title="PrShor">zur</span> <span class="Sb" title="SbSgFm">Tagesordnung</span>
<span class="Vb" title="VbRtWeak">uebergehen</span><span class="Pu" title="Pu">.</span> <span class="Ex" title="ExUE|PrPrim">Fuer</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Ab" title="AbSbFm">FDP</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Bundesvorsitzenden</span> <span class="Nm" title="NmPersPrenMs">Wolfgang</span> <span class="Nm" title="NmPersPrenMs">Gerhardt</span> <span class="Vb" title="VbSPr13">ist</span> <span class="Ar" title="ArDetmNomvSgNt|ArDetmAccvSgNt|PnReltNomvSgNt|PnReltAccvSgNt">das</span> <span class="Ar" title="ArUndtNomvSgMs|ArUndtNomvSgNt|ArUndtAccvSgNt">ein</span>
<span class="Vb" title="VbSIm12|VbSIp13|VbSIp11">Nackenschlag</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="CjPrim">da</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Pn" title="PnReflSg3|PnReflPl3">sich</span> <span class="Aj" title="AjXP">massiv</span> <span class="Av" title="AvMove|PrPrim">gegen</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span> <span class="Vb" title="VbIm92">eingesetzt</span> <span class="Vb" title="VbSIp11|VbSIp13">hatte</span><span class="Pu" title="Pu">.</span> <span class="Cj" title="CjPrim">Doch</span>
<span class="Vb" title="VbSPa0|VbSIp93|VbSIp91">abgeschlossen</span> <span class="Vb" title="VbSPr13">ist</span> <span class="Ar" title="ArDetmNomvSgNt|ArDetmAccvSgNt|PnReltNomvSgNt|PnReltAccvSgNt">das</span> <span class="Sb" title="SbSgNt">Kapitel</span> <span class="Sb" title="SbSgMsProf|SbSgMsProf">Koch</span> <span class="Ex" title="ExUE|PrPrim">fuer</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Cj" title="Cj">noch</span> <span class="Aj" title="AjXP|VbPr11">lange</span> <span class="Un" title="Un">nicht</span><span class="Pu" title="Pu">.</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">Es</span> <span class="Vb" title="VbSPr13">wird</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span>
<span class="Aj" title="AjXP">Liberalen</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="Cj">und</span> <span class="Av" title="Av">damit</span> <span class="Vb" title="VbSPr13">hat</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Av" title="AvTime">heute</span> <span class="Xy" title="Xy">unterlegene</span> <span class="Xy" title="Xy">Bundesvorsitzende</span> <span class="Nm" title="NmPersPrenMs">Gerhardt</span>
<span class="Xy" title="Xy">gewissrecht</span><span class="Pu" title="Pu">,</span> <span class="Av" title="AvFreq">immer</span> <span class="Av" title="AvFreq">wieder</span> <span class="Vb" title="VbRtWeak">einholen</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="Cj">wenn</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">Untersuchungsausschuesse</span> <span class="Pr" title="PrPrim">in</span>
<span class="Sb" title="SbSgFmProf">Berlin</span> <span class="Cj" title="Cj">und</span> <span class="Nm" title="NmGeogCity.De">Wiesbaden</span> <span class="Cj" title="Cj">und</span> <span class="Un" title="Un">auch</span> <span class="Ar" title="ArDetmNomvSgNt|ArDetmAccvSgNt|PnReltNomvSgNt|PnReltAccvSgNt">das</span> <span class="Xy" title="Xy">Wahlpruefungsgericht</span> <span class="Xy" title="Xy">neue</span> <span class="Sb" title="SbPl">Erkenntnisse</span> <span class="Pr" title="PrPrim">zu</span>
<span class="Sb" title="SbPl|SbPl">Tage</span> <span class="Vb" title="VbRtWeak">foerdern</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Ab" title="AbSbFm">SPD</span><span class="Pu" title="Pu">-</span><span class="Sb" title="SbSgMsProf">Fraktionschef</span> <span class="Xy" title="Xy">Struck</span> <span class="Vb" title="VbSPr13">empfiehlt</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Sb" title="SbSgFm">Einberufung</span> <span class="Ar" title="ArUndtGenvSgMs|ArUndtGenvSgNt|PnUndtNomvNt">eines</span> <span class="Av" title="AvTime">Bundesparteitags</span>

<span class="Sb" title="SbSgFmProf">Berlin</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">Der</span> <span class="Ab" title="AbSbFm">SPD</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Fraktionsvorsitzende</span> <span class="Xy" title="Xy">Struck</span> <span class="Vb" title="VbSPr13">hat</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Pr" title="PrShor">zur</span> <span class="Sb" title="SbSgFm">Einberufung</span> <span class="Ar" title="ArUndtGenvSgMs|ArUndtGenvSgNt|PnUndtNomvNt">eines</span>
<span class="Aj" title="AjXP">Bundesparteitages</span> <span class="Vb" title="VbIm92">aufgefordert</span><span class="Pu" title="Pu">.</span> <span class="Cj" title="Cj">Wenn</span> <span class="Nm" title="NmPersPrenMs">Wolfgang</span> <span class="Nm" title="NmPersPrenMs">Gerhardt</span> <span class="Pn" title="PnSgPersNomvNt3|PnSgPersAccv3Nt">es</span> <span class="Pr" title="PrPrim">mit</span> <span class="Sb" title="SbSgFm">Glaubwuerdigkeit</span>
<span class="Cj" title="Cj">und</span> <span class="Xy" title="Xy">Fuehrungsanspruch</span> <span class="Aj" title="AjRoot">ernst</span> <span class="Pn" title="PnSgPossNomvFm1|PnSgPossNomvPl1|PnSgPossAccvFm1|PnSgPossAccvPl1">meine</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="CjPrim">dann</span> <span class="Vb" title="VbSCs11|VbSCs13">solle</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Av" title="AvTime">jetzt</span> <span class="Ar" title="ArUndtAccvSgMs|PnUndtAccv">einen</span> <span class="Xy" title="Xy">Sonderparteitag</span>
<span class="Vb" title="VbRtWeak">einberufen</span><span class="Pu" title="Pu">.</span> <span class="Cj" title="CjPrim">Dann</span> <span class="Ex" title="ExUE|VbSCs11|ExUE|VbSCs13">koenne</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">gesamte</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Ex" title="ExUE|AvLoct">darueber</span> <span class="Vb" title="VbRtWeak">entscheiden</span><span class="Pu" title="Pu">,</span> <span class="Cj" title="CjPrim">ob</span> <span class="Aj" title="AjXP">politische</span>
<span class="Sb" title="SbSgFm">Glaubwuerdigkeit</span> <span class="Aj" title="AjXC|AjXP|AjXC|AjXP">wichtiger</span> <span class="Vb" title="VbSIm12|VbSCs11|VbSCs13">sei</span> <span class="Pr" title="PrPrim">als</span> <span class="Xy" title="Xy">Ministerposten</span> <span class="Vb" title="VbPa1F">sagte</span> <span class="Xy" title="Xy">Struck</span> <span class="Pr" title="PrPrim">in</span> <span class="Ar" title="ArUndtGenvSgFm|ArUndtDatvSgFm|PnUndtNomvMs">einer</span>
<span class="Sb" title="SbSgFm|SbSgFm">Reaktion</span> <span class="Pr" title="PrPrim">auf</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbSgFm">Entscheidung</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Ab" title="AbSbFm">FDP</span> <span class="Pr" title="PrPrim">in</span> <span class="Nm" title="NmGeogRegn|NmGeogRegn">Hessen</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Xy" title="Xy">Lufthansa</span> <span class="Vb" title="VbIm92">droht</span> <span class="Sb" title="SbSgFm">Regierung</span> <span class="Pr" title="PrPrim">mit</span> <span class="Sb" title="SbSgFm|SbSgFm">Klage</span> <span class="Cj" title="CjPrim">wegen</span> <span class="Aj" title="AjXC|AjXP">mangelhafter</span> <span class="Sb" title="SbSgFm">Flugsicherung</span>

<span class="Nm" title="NmGeogCity.De">Frankfurt</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Xy" title="Xy">Lufthansa</span> <span class="Vb" title="VbIm92">droht</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="SbSgFm">Bundesregierung</span> <span class="Pr" title="PrPrim">mit</span> <span class="Ar" title="ArUndtGenvSgFm|ArUndtDatvSgFm|PnUndtNomvMs">einer</span> <span class="Sb" title="SbSgFm|SbSgFm">Klage</span><span class="Pu" title="Pu">.</span> <span class="Pn" title="PnPlPersNomv3Honr|PnPlPersAccv3Honr">Sie</span> <span class="Vb" title="VbSPr11|VbSPr13|VbSIm12">will</span>
<span class="Ar" title="ArUndtNomvSgFm|ArUndtAccvSgFm|PnUndtNomvFm">eine</span> <span class="Vb" title="VbPr11">bessere</span> <span class="Sb" title="SbSgFm">Flugsicherung</span> <span class="Vb" title="VbRtWeak">durchsetzen</span><span class="Pu" title="Pu">.</span> <span class="Xy" title="Xy">Lufthansa</span><span class="Pu" title="Pu">-</span><span class="Sb" title="SbSgMsPersForg|SbSgMsPersForg">Chef</span> <span class="Sb" title="SbSgMs|SbSgMs|SbSgMsPers|SbSgMsPers">Weber</span> <span class="Vb" title="VbPa1F">erklaerte</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span>
<span class="Sb" title="SbSgFm|SbSgFm">Welt</span> <span class="Pr" title="PrShor">am</span> <span class="Sb" title="SbSgMsTimeWeek.7">Sonntag</span><span class="Pu" title="Pu">,</span> <span class="Aj" title="AjRoot">rund</span> <span class="Nu" title="Nu">40</span> <span class="Xy" title="Xy">Prozent</span> <span class="Aj" title="AjQant">aller</span> <span class="Sb" title="SbPl">Verspaetungen</span> <span class="Vb" title="VbSIp91|VbSIp93|VbSCt91|VbSCt93">gingen</span> <span class="Pr" title="PrPrim">auf</span> <span class="Ar" title="ArDetmNomvSgNt|ArDetmAccvSgNt|PnReltNomvSgNt|PnReltAccvSgNt">das</span> <span class="Sb" title="SbSgNtForg|SbSgNtForg">Konto</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span>
<span class="Sb" title="SbSgFm">Flugsicherung</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Xy" title="Xy">Lufthansa</span> <span class="Av" title="AvPers">allein</span> <span class="Vb" title="VbPr11">zahle</span> <span class="Aj" title="AjXP">jaehrlich</span> <span class="Un" title="Un">fast</span> <span class="Ar" title="ArUndtNomvSgFm|ArUndtAccvSgFm|PnUndtNomvFm">eine</span> <span class="Xy" title="Xy">Milliarde</span> <span class="Ab" title="AbSbFm">DM</span> <span class="Pr" title="PrPrim">an</span>
<span class="Vb" title="VbRtWeak">Gebuehren</span> <span class="Un" title="Un">ohne</span> <span class="Cj" title="CjPrim|ExUE|ExNrul">dass</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="SbSgFmProf">Service</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Xy" title="Xy">Fluglotsen</span> <span class="Vb" title="VbPr11">funktioniere</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Xy" title="Xy">Bundesbahn</span> <span class="Vb" title="VbSPr11|VbSPr13|VbSIm12">will</span> <span class="Pn" title="PnReflSg3|PnReflPl3">sich</span> <span class="Aj" title="AjXP|VbSCs13|VbSCs11|VbSPr11">teilweise</span> <span class="Pr" title="PrPrim">aus</span> <span class="Ar" title="ArDetmDatvSgMs|ArDetmDatvSgNt|PnReltDatvSgMs|PnReltDatvSgNt">dem</span> <span class="Xy" title="Xy">Gueterverkehr</span> <span class="Vb" title="VbRtWeak">zurueckziehen</span>

<span class="Nm" title="NmGeogCity.De">Frankfurt</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Sb" title="SbSgFm|SbSgFm">Bahn</span> <span class="Vb" title="VbSPr11|VbSPr13|VbSIm12">will</span> <span class="Pn" title="PnReflSg3|PnReflPl3">sich</span> <span class="Aj" title="AjXP">offenbar</span> <span class="Aj" title="AjXP|VbSCs13|VbSCs11|VbSPr11">teilweise</span> <span class="Pr" title="PrPrim">aus</span> <span class="Ar" title="ArDetmDatvSgMs|ArDetmDatvSgNt|PnReltDatvSgMs|PnReltDatvSgNt">dem</span> <span class="Xy" title="Xy">Gueterverkehr</span>
<span class="Vb" title="VbRtWeak">zurueckziehen</span><span class="Pu" title="Pu">.</span> <span class="Pr" title="PrPrim">Nach</span> <span class="Sb" title="SbPl|SbPl">Informationen</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Xy" title="Xy">Sueddeutschen</span> <span class="Sb" title="SbSgFm">Zeitung</span> <span class="Vb" title="VbRtWeak">planen</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span>
<span class="Aj" title="AjXC|AjXP">Bahnmanager</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">Guetertransporte</span> <span class="Pr" title="PrPrim">auf</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="SbSgFm|SbSgFm">Schiene</span> <span class="Cj" title="CjPrim">bis</span> <span class="Nu" title="Nu">2004</span> <span class="Pr" title="PrPrim">um</span> <span class="Un" title="Un">etwa</span> <span class="Ar" title="ArUndtNomvSgMs|ArUndtNomvSgNt|ArUndtAccvSgNt">ein</span> <span class="Sb" title="SbSgNt">Viertel</span>
<span class="Pr" title="PrPrim">zu</span> <span class="Vb" title="VbRtWeak">verringern</span><span class="Pu" title="Pu">.</span> <span class="Pn" title="PnPlPersNomv3Honr|PnPlPersAccv3Honr">Sie</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">wollen</span> <span class="Pn" title="PnReflSg3|PnReflPl3">sich</span> <span class="Pr" title="PrPrim">auf</span> <span class="Xy" title="Xy">ertragsstarke</span> <span class="Vb" title="VbRtWeak">Strecken</span> <span class="Vb" title="VbRtWeak">konzentrieren</span><span class="Pu" title="Pu">.</span> <span class="Sb" title="SbSgFm">Dabei</span>
<span class="Vb" title="VbSIm12|VbSCs11|VbSCs13">sei</span> <span class="Vb" title="VbIm92">geplant</span><span class="Pu" title="Pu">,</span> <span class="Nu" title="Nu">20000</span> <span class="Xy" title="Xy">Arbeitsplaetze</span> <span class="Pr" title="PrPrim">zu</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">streichen</span> <span class="Vb" title="VbIm92">berichtet</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Xy" title="Xy">Sueddeutsche</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span>
<span class="Sb" title="SbSgFm|SbSgFm">Bahn</span> <span class="Vb" title="VbIm92">lehnt</span> <span class="Av" title="AvTime">bisher</span> <span class="Ar" title="ArUndtNomvSgFm|ArUndtAccvSgFm|PnUndtNomvFm">eine</span> <span class="Sb" title="SbSgFm">Stellungnahme</span> <span class="Pr" title="PrPrim">ab</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Xy" title="Xy">Bundesbahn</span> <span class="Vb" title="VbSPr11|VbSPr13|VbSIm12">will</span> <span class="Pr" title="PrPrim">bei</span> <span class="Aj" title="AjQant">allen</span> <span class="Sb" title="SbSgFm|SbSgFm">Neige</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">ICEs</span> <span class="Xy" title="Xy">Ventile</span> <span class="Vb" title="VbRtWeak">austauschen</span>

<span class="Sb" title="SbSgFmProf">Berlin</span><span class="Pu" title="Pu">.</span> <span class="Pr" title="PrPrim">An</span> <span class="Aj" title="AjQant">allen</span> <span class="Nu" title="Nu.11">elf</span> <span class="Xy" title="Xy">ICEs</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span> <span class="Sb" title="SbSgFm|SbSgFm">Bahn</span> <span class="Pr" title="PrPrim">mit</span> <span class="Sb" title="SbSgFm">Neugetechnik</span> <span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">werden</span> <span class="Ex" title="ExUE|PrPrim">ueber</span> <span class="Ar" title="ArDetmNomvSgNt|ArDetmAccvSgNt|PnReltNomvSgNt|PnReltAccvSgNt">das</span>
<span class="Sb" title="SbSgFmTime">Wochenende</span> <span class="Xy" title="Xy">Ventile</span> <span class="Vb" title="VbIm92">ausgewechselt</span><span class="Pu" title="Pu">.</span> <span class="Sb" title="SbPl|SbPl">Wegen</span> <span class="Ar" title="ArUndtGenvSgMs|ArUndtGenvSgNt|PnUndtNomvNt">eines</span> <span class="Xy" title="Xy">defekten</span> <span class="Xy" title="Xy">Ventils</span> <span class="Vb" title="VbSIp11|VbSIp13">war</span> <span class="Pr" title="PrPrim">in</span> <span class="Sb" title="SbSgFmProf">Berlin</span>
<span class="Ar" title="ArUndtNomvSgMs|ArUndtNomvSgNt|ArUndtAccvSgNt">ein</span> <span class="Aj" title="AjXP">leerer</span> <span class="Xy" title="Xy">ICE</span> <span class="Vb" title="VbIm92">entgleist</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Sb" title="SbSgMsPers|SbSgMsPers">Schalker</span> <span class="Sb" title="SbSgMsPersForg.En|SbSgMsPersForg.En">Fan</span> <span class="Aj" title="AjXP">Initiative</span> <span class="Xy" title="Xy">erhaelt</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Xy" title="Xy">Anti</span><span class="Pu" title="Pu">-</span><span class="Sb" title="SbSgMs">Rassismus</span><span class="Pu" title="Pu">-</span><span class="Sb" title="SbSgMs|SbSgMs">Preis</span>

<span class="Nm" title="NmGeogCity.De">Gelsenkirchen</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">Die</span> <span class="Sb" title="SbSgFmProf">nordrhein</span><span class="Pu" title="Pu">-</span><span class="Aj" title="AjXP">westfaelische</span> <span class="Sb" title="SbSgFmProf|SbSgFmProf">Jugendministerin</span> <span class="Sb" title="SbSgMs|SbSgMs">Fischer</span> <span class="Vb" title="VbSPr13">hat</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">der</span>
<span class="Sb" title="SbSgMsPers|SbSgMsPers">Schalker</span> <span class="Sb" title="SbSgMsPersForg.En|SbSgMsPersForg.En">Fan</span><span class="Pu" title="Pu">-</span><span class="Aj" title="AjXP">Initiative</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Aj" title="AjXP">diesjaehrigen</span> <span class="Xy" title="Xy">Anti</span><span class="Pu" title="Pu">-</span><span class="Sb" title="SbSgMs">Rassismus</span><span class="Pu" title="Pu">-</span><span class="Sb" title="SbSgMs|SbSgMs">Preis</span> <span class="Vb" title="VbIm92">ueberreicht</span><span class="Pu" title="Pu">.</span>
<span class="Pr" title="PrPrim">Vor</span> <span class="Ar" title="ArDetmDatvSgMs|ArDetmDatvSgNt|PnReltDatvSgMs|PnReltDatvSgNt">dem</span> <span class="Sb" title="SbSgNt|SbSgNt">Spiel</span> <span class="Nm" title="NmGeogCity.De|NmGeogCity.De">Schalke</span> <span class="Av" title="AvMove|PrPrim">gegen</span> <span class="Nm" title="NmGeogCity.De">Duisburg</span> <span class="Vb" title="VbSIp11|VbSIp13">wurde</span> <span class="Ar" title="ArDetmNomvSgFm|ArDetmNomvPl|ArDetmAccvSgFm|ArDetmAccvPl|PnReltNomvSgFm|PnReltNomvPl|PnReltAccvSgFm|PnReltAccvPl">die</span> <span class="Sb" title="SbSgMsPersForg.En|SbSgMsPersForg.En">Fan</span><span class="Pu" title="Pu">-</span><span class="Sb" title="SbSgFm|SbSgFm">Gruppe</span> <span class="Av" title="Av">damit</span> <span class="Ex" title="ExUE|PrPrim">fuer</span> <span class="Ar" title="ArUndtAccvSgMs|PnUndtAccv">einen</span>
<span class="Aj" title="AjXP">vorbildlichen</span> <span class="Sb" title="SbSgMs">Einsatz</span> <span class="Av" title="AvMove|PrPrim">gegen</span> <span class="Xy" title="Xy">Gewalt</span> <span class="Cj" title="Cj">und</span> <span class="Sb" title="SbSgMs">Rassismus</span> <span class="Pr" title="PrPrim">in</span> <span class="Ar" title="ArDetmDatvPl|ArDetmAccvSgMs|PnReltAccvSgMs">den</span> <span class="Sb" title="SbPl">Fussballstadien</span>
<span class="Vb" title="VbIm92">geehrt</span><span class="Pu" title="Pu">.</span> <span class="Ar" title="ArDetmNomvSgMs|ArDetmGenvSgFm|ArDetmGenvPl|ArDetmDatvSgFm|PnReltNomvSgMs|PnReltDatvSgFm">Der</span> <span class="Sb" title="SbSgMs|SbSgMs">Preis</span> <span class="Vb" title="VbSPr13">wird</span> <span class="Pr" title="PrPrim">seit</span> <span class="Nu" title="Nu">12</span> <span class="Xy" title="Xy">Jahren</span> <span class="Vb" title="VbSCt93|VbSCt91|VbSIp93|VbSIp91">verliehen</span><span class="Pu" title="Pu">.</span>


<span class="Pu" title="Pu">-</span> <span class="Sb" title="SbPl">Ergebnisse</span> <span class="Ar" title="ArDetmGenvSgMs|ArDetmGenvSgNt">des</span> <span class="Sb" title="SbSgFm">Skisprung</span> <span class="Xy" title="Xy">Weltcups</span> <span class="Pr" title="PrPrim">in</span> <span class="Xy" title="Xy">Lahti</span>

<span class="Xy" title="Xy">Lahti</span><span class="Pu" title="Pu">.</span> <span class="Nm" title="NmPersPrenMs">Sven</span> <span class="Xy" title="Xy">Hannawald</span> <span class="Vb" title="VbSPr13">ist</span> <span class="Pr" title="PrShor">beim</span> <span class="Sb" title="SbSgFm">Skisprung</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">Weltcup</span> <span class="Pr" title="PrPrim">in</span> <span class="Xy" title="Xy">Lahti</span> <span class="Xy" title="Xy">Zweiter</span> <span class="Pr" title="PrPrim">hinter</span> <span class="Ar" title="ArDetmDatvSgMs|ArDetmDatvSgNt|PnReltDatvSgMs|PnReltDatvSgNt">dem</span>
<span class="Xy" title="Xy">Finnen</span> <span class="Xy" title="Xy">Janne</span> <span class="Xy" title="Xy">Ahonen</span> <span class="Vb" title="VbSPa0">geworden</span><span class="Pu" title="Pu">.</span> <span class="Sb" title="SbSgFmProf">Martin</span> <span class="Nm" title="NmPersSurn">Schmitt</span> <span class="Vb" title="VbSIp11|VbSIp13">wurde</span> <span class="Nu" title="Nu">13</span><span class="Pu" title="Pu">-</span><span class="Xy" title="Xy">ter</span><span class="Pu" title="Pu">,</span> <span class="Pn" title="PnSgPersNomvMs3">er</span> <span class="Ex" title="ExUE|VbSCt92">fuehrt</span> <span class="Pr" title="PrPrim">weiter</span>
<span class="Pr" title="PrShor">im</span> <span class="Xy" title="Xy">Gesamtweltcup</span> <span class="Pr" title="PrPrim">vor</span> <span class="Ar" title="ArDetmDatvSgMs|ArDetmDatvSgNt|PnReltDatvSgMs|PnReltDatvSgNt">dem</span> <span class="Aj" title="AjXC|AjXP">Oesterreicher</span> <span class="Nm" title="NmBibl">Andreas</span> <span class="Sb" title="SbSgNt">Widhoelzel</span><span class="Pu" title="Pu">.</span>


<span class="Vb" title="VbSIn0|VbSPr91|VbSPr93|VbSIm91|VbSCs91|VbSCs93">Quellen</span>
<br /><br />Morphems:
<span class="Ab">Ab</span> 27
<span class="Aj">Aj</span> 51
<span class="Ar">Ar</span> 104
<span class="Av">Av</span> 17
<span class="Cj">Cj</span> 26
<span class="Ex">Ex</span> 19
<span class="Nm">Nm</span> 33
<span class="Nu">Nu</span> 8
<span class="Pn">Pn</span> 21
<span class="Pr">Pr</span> 76
<span class="Pu">Pu</span> 107
<span class="Sb">Sb</span> 107
<span class="Un">Un</span> 13
<span class="Vb">Vb</span> 122
<span class="Xy">Xy</span> 96
<br />
<strong>88.4%</strong> = 731 recognized and 96 unknown out of 827 total words<br />
Highlight:
<a href="#" title="Click to switch" onclick="activateStyles('all');    return false;">all found</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('vbav');   return false;">Vb+Av</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('sbajar'); return false;">Sb+Aj+Ar</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('nmnu');   return false;">Nm+Nu</a>, 
<a href="#" title="Click to switch" onclick="activateStyles('prcj');   return false;">Pr+Cj+Cc+Un</a> 
<a href="#" title="Click to switch" onclick="activateStyles('puxy');   return false;">Pu+Xy</a> 
<br />
</body></html>