testTableLookup(setzen), state = 0
testTableLookup(setzen), state = 1
getRoots(setzen): serv =VbRtWeak,ieren,null
getRoots(setzen): sequestr =VbRtWeak,ieren,null
getRoots(setzen): separ =VbRtWeak,ieren,null
getRoots(setzen): sensibilis =VbRtWeak,ieren,null
getRoots(setzen): selten =AjRoot,null,null
getRoots(setzen): selektion =VbRtWeak,ieren,null
getRoots(setzen): selekt =VbRtWeak,ieren,null
getRoots(setzen): seleg =VbRtWeak,ieren,null
getRoots(setzen): selbiges =AjQant,selbig,AjRootQant
getRoots(setzen): selbiger =AjQant,selbig,AjRootQant
getRoots(setzen): selbigen =AjQant,selbig,AjRootQant
getRoots(setzen): selbigem =AjQant,selbig,AjRootQant
getRoots(setzen): selbige =AjQant,selbig,AjRootQant
getRoots(setzen): selb =AjRoot,null,null
getRoots(setzen): sekund =VbRtWeak,ieren,null
getRoots(setzen): sekret =VbRtWeak,ieren,null
testTableLookup(setzen), state = 2
getXiffus(setzen/neztes): enzen = SbPl,null,null
getXiffus(setzen/neztes): anzen = SbPl,null,null
getXiffus(setzen/neztes): schmölzen = VbSCt93,schmelzen,null
getXiffus(setzen/neztes): schmölzen = VbSCt91,schmelzen,null
getXiffus(setzen/neztes): geschmolzen = VbSPa0,schmelzen,null
getXiffus(setzen/neztes): schmolzen = VbSIp93,schmelzen,null
getXiffus(setzen/neztes): schmolzen = VbSIp91,schmelzen,null
getXiffus(setzen/neztes): schmoelzen = ExUE,schmölzen,VbSCt93
getXiffus(setzen/neztes): schmoelzen = ExUE,schmölzen,VbSCt91
getXiffus(setzen/neztes): schmelzen = VbSCs93,schmelzen,null
getXiffus(setzen/neztes): schmelzen = VbSCs91,schmelzen,null
getXiffus(setzen/neztes): schmelzen = VbSIm91,schmelzen,null
getXiffus(setzen/neztes): schmelzen = VbSPr93,schmelzen,null
getXiffus(setzen/neztes): schmelzen = VbSPr91,schmelzen,null
getXiffus(setzen/neztes): schmelzen = VbSIn0,schmelzen,null
getXiffus(setzen/neztes): gesalzen = VbSPa0,salzen,null
testTableLookup(setzen), state = 3
testVariants(setzen), state = 4
testTableLookup(Setzen), state = 0
testTableLookup(Setzen), state = 1
getRoots(Setzen): Setter =SbSgMsZool,,
getRoots(Setzen): Set =SbSgNtForg.En,,
getRoots: add Set =SbSgNtForg.En,,
getRoots(Setzen): Sessel =SbSgMs,,
getRoots(Setzen): Server =SbSgMsForg.En,,
getRoots(Setzen): Serge =NmMsPrenForg.Fr,,
getRoots(Setzen): Serbien =NmGeogCtry.Yu,,
getRoots(Setzen): Serbe =SbSgMsPersGeogRegn,,
getRoots(Setzen): Seppel =NmMsPrenDimt,,
getRoots(Setzen): Sepp =NmMsPrenDial,,
getRoots(Setzen): Sense =SbSgFm,,
getRoots(Setzen): Senner =SbSgMs,,
getRoots(Setzen): Senne =SbSgMsProf,,
getRoots(Setzen): Senn =SbSgMsProf,,
getRoots(Setzen): Senker =SbSgMs,,
getRoots(Setzen): Senkel =SbSgMs,,
getRoots(Setzen): Senke =SbSgFm,,
testTableLookup(Setzen), state = 2
getXiffus(Setzen/nezteS): enzen = SbPl,null,null
getXiffus(Setzen/nezteS): anzen = SbPl,null,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt93,schmelzen,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt91,schmelzen,null
getXiffus(Setzen/nezteS): geschmolzen = VbSPa0,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp93,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp91,schmelzen,null
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt93
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt91
getXiffus(Setzen/nezteS): schmelzen = VbSCs93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSCs91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIm91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIn0,schmelzen,null
getXiffus(Setzen/nezteS): gesalzen = VbSPa0,salzen,null
testTableLookup(Setzen), state = 3
testVariants(setzen), state = 12
testTableLookup(Setzen), state = 0
testTableLookup(Setzen), state = 1
getRoots(Setzen): Setter =SbSgMsZool,,
getRoots(Setzen): Set =SbSgNtForg.En,,
getRoots: add Set =SbSgNtForg.En,,
getRoots(Setzen): Sessel =SbSgMs,,
getRoots(Setzen): Server =SbSgMsForg.En,,
getRoots(Setzen): Serge =NmMsPrenForg.Fr,,
getRoots(Setzen): Serbien =NmGeogCtry.Yu,,
getRoots(Setzen): Serbe =SbSgMsPersGeogRegn,,
getRoots(Setzen): Seppel =NmMsPrenDimt,,
getRoots(Setzen): Sepp =NmMsPrenDial,,
getRoots(Setzen): Sense =SbSgFm,,
getRoots(Setzen): Senner =SbSgMs,,
getRoots(Setzen): Senne =SbSgMsProf,,
getRoots(Setzen): Senn =SbSgMsProf,,
getRoots(Setzen): Senker =SbSgMs,,
getRoots(Setzen): Senkel =SbSgMs,,
getRoots(Setzen): Senke =SbSgFm,,
testTableLookup(Setzen), state = 2
getXiffus(Setzen/nezteS): enzen = SbPl,null,null
getXiffus(Setzen/nezteS): anzen = SbPl,null,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt93,schmelzen,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt91,schmelzen,null
getXiffus(Setzen/nezteS): geschmolzen = VbSPa0,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp93,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp91,schmelzen,null
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt93
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt91
getXiffus(Setzen/nezteS): schmelzen = VbSCs93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSCs91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIm91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIn0,schmelzen,null
getXiffus(Setzen/nezteS): gesalzen = VbSPa0,salzen,null
testTableLookup(Setzen), state = 3
testVariants(setzen), state = 20
testTableLookup(Setzen), state = 0
testTableLookup(Setzen), state = 1
getRoots(Setzen): Setter =SbSgMsZool,,
getRoots(Setzen): Set =SbSgNtForg.En,,
getRoots: add Set =SbSgNtForg.En,,
getRoots(Setzen): Sessel =SbSgMs,,
getRoots(Setzen): Server =SbSgMsForg.En,,
getRoots(Setzen): Serge =NmMsPrenForg.Fr,,
getRoots(Setzen): Serbien =NmGeogCtry.Yu,,
getRoots(Setzen): Serbe =SbSgMsPersGeogRegn,,
getRoots(Setzen): Seppel =NmMsPrenDimt,,
getRoots(Setzen): Sepp =NmMsPrenDial,,
getRoots(Setzen): Sense =SbSgFm,,
getRoots(Setzen): Senner =SbSgMs,,
getRoots(Setzen): Senne =SbSgMsProf,,
getRoots(Setzen): Senn =SbSgMsProf,,
getRoots(Setzen): Senker =SbSgMs,,
getRoots(Setzen): Senkel =SbSgMs,,
getRoots(Setzen): Senke =SbSgFm,,
testTableLookup(Setzen), state = 2
getXiffus(Setzen/nezteS): enzen = SbPl,null,null
getXiffus(Setzen/nezteS): anzen = SbPl,null,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt93,schmelzen,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt91,schmelzen,null
getXiffus(Setzen/nezteS): geschmolzen = VbSPa0,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp93,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp91,schmelzen,null
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt93
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt91
getXiffus(Setzen/nezteS): schmelzen = VbSCs93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSCs91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIm91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIn0,schmelzen,null
getXiffus(Setzen/nezteS): gesalzen = VbSPa0,salzen,null
testTableLookup(Setzen), state = 3
testVariants(setzen), state = 28
testTableLookup(Setzen), state = 0
testTableLookup(Setzen), state = 1
getRoots(Setzen): Setter =SbSgMsZool,,
getRoots(Setzen): Set =SbSgNtForg.En,,
getRoots: add Set =SbSgNtForg.En,,
getRoots(Setzen): Sessel =SbSgMs,,
getRoots(Setzen): Server =SbSgMsForg.En,,
getRoots(Setzen): Serge =NmMsPrenForg.Fr,,
getRoots(Setzen): Serbien =NmGeogCtry.Yu,,
getRoots(Setzen): Serbe =SbSgMsPersGeogRegn,,
getRoots(Setzen): Seppel =NmMsPrenDimt,,
getRoots(Setzen): Sepp =NmMsPrenDial,,
getRoots(Setzen): Sense =SbSgFm,,
getRoots(Setzen): Senner =SbSgMs,,
getRoots(Setzen): Senne =SbSgMsProf,,
getRoots(Setzen): Senn =SbSgMsProf,,
getRoots(Setzen): Senker =SbSgMs,,
getRoots(Setzen): Senkel =SbSgMs,,
getRoots(Setzen): Senke =SbSgFm,,
testTableLookup(Setzen), state = 2
getXiffus(Setzen/nezteS): enzen = SbPl,null,null
getXiffus(Setzen/nezteS): anzen = SbPl,null,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt93,schmelzen,null
getXiffus(Setzen/nezteS): schmölzen = VbSCt91,schmelzen,null
getXiffus(Setzen/nezteS): geschmolzen = VbSPa0,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp93,schmelzen,null
getXiffus(Setzen/nezteS): schmolzen = VbSIp91,schmelzen,null
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt93
getXiffus(Setzen/nezteS): schmoelzen = ExUE,schmölzen,VbSCt91
getXiffus(Setzen/nezteS): schmelzen = VbSCs93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSCs91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIm91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr93,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSPr91,schmelzen,null
getXiffus(Setzen/nezteS): schmelzen = VbSIn0,schmelzen,null
getXiffus(Setzen/nezteS): gesalzen = VbSPa0,salzen,null
testTableLookup(Setzen), state = 3
setzen	Xy

words(Sie): Sie =PnPlPersNomv3Honr,null,null
words(Sie): Sie =PnPlPersAccv3Honr,null,null
Sie	PnPlPersNomv3Honr
Sie	PnPlPersAccv3Honr

words(sich): sich =PnReflSg3,null,null
words(sich): sich =PnReflPl3,null,null
sich	PnReflSg3
sich	PnReflPl3

testTableLookup(Pfeifer), state = 0
testTableLookup(Pfeifer), state = 1
getRoots(Pfeifer): Pfeifer =NmSurnPers,,
getRoots: add Pfeifer =NmSurnPers,,
getRoots(Pfeifer): Pfeife =SbSgFm,,
getRoots: add Pfeife =SbSgFm,,
getRoots(Pfeifer): Pfeffer =SbSgMsNutr,,
getRoots(Pfeifer): Pfau =SbSgMsZool,,
getRoots(Pfeifer): Pfarrer =SbSgMsProf,,
getRoots(Pfeifer): Pfarre =SbSgFm,,
getRoots(Pfeifer): Pfanne =SbSgFm,,
getRoots(Pfeifer): Pfand =SbSgNt,,
getRoots(Pfeifer): Pfalz =NmFmGeogRegn,,
getRoots(Pfeifer): Pfahl =SbSgMs,,
getRoots(Pfeifer): Pfaffe =SbSgMsPers,,
getRoots(Pfeifer): Pfad =SbSgMs,,
getRoots(Pfeifer): Petzer =SbSgMs,,
getRoots(Pfeifer): Petze =SbSgFm,,
getRoots(Pfeifer): Peter =NmMsPren,,
getRoots(Pfeifer): Pest =SbSgFmMedc,,
Pfeifer	NmSurnPers

testTableLookup(6), state = 0
testTableLookup(6), state = 1
getRoots(6): /üb =VbRtWeak,en,VbIn
getRoots(6): /öl =VbRtWeak,en,VbIn
getRoots(6): /öhmd =VbRtWeak,en,VbIn
getRoots(6): /öffn =VbRtWeak,en,VbIn
getRoots(6): /öd =VbRtWeak,en,VbIn
getRoots(6): /äuß =VbRtWeak,ern,VbIn
getRoots(6): /ätz =VbRtWeak,en,VbIn
getRoots(6): /äs =VbRtWeak,en,VbIn
getRoots(6): /ärg =VbRtWeak,ern,VbIn
getRoots(6): /ängstig =VbRtWeak,en,VbIn
getRoots(6): /änd =VbRtWeak,ern,VbIn
getRoots(6): /ähn =VbRtWeak,eln,VbIn
getRoots(6): /ächz =VbRtWeak,en,VbIn
getRoots(6): /ächt =VbRtWeak,en,VbIn
getRoots(6): /zürn =VbRtWeak,en,VbIn
getRoots(6): /züng =VbRtWeak,eln,VbIn
testTableLookup(6), state = 2
testTableLookup(6), state = 3
6	Nu

