words(ja): ja =Rp,null,null
ja	Rp

testTableLookup(macht), state = 0
testTableLookup(macht), state = 1
getRoots(macht): lüstr =VbRtWeak,ieren,null
getRoots(macht): längst =AjSupl,lang,AjPost
getRoots(macht): länger =AjCmpr,lang,AjPost
getRoots(macht): läd =VbRtWeak,ieren,null
getRoots(macht): luxur =VbRtWeak,ieren,null
getRoots(macht): lux =VbRtWeak,ieren,null
getRoots(macht): lustr =VbRtWeak,ieren,null
getRoots(macht): lust/wand =VbRtWeak,eln,VbIn
getRoots(macht): luminesz =VbRtWeak,ieren,null
getRoots(macht): luestr =ExUE,lüstr,VbRtWeak
getRoots(macht): los/zieh =VbRtWeak,en,VbIn
getRoots(macht): los/wirtschaft =VbRtWeak,en,VbIn
getRoots(macht): los/werd =VbRtWeak,en,VbIn
getRoots(macht): los/stürz =VbRtWeak,en,VbIn
getRoots(macht): los/steu =VbRtWeak,ern,VbIn
getRoots(macht): los/sprech =VbRtWeak,en,VbIn
testTableLookup(macht), state = 2
getXiffus(macht/thcam): gedacht = VbSPa0,denken,null
getXiffus(macht/thcam): saht = VbSIp92,sehen,null
getXiffus(macht/thcam): geschaht = VbSIp92,geschehen,null
getXiffus(macht/thcam): trügt = VbSCs92,trügen,null
getXiffus(macht/thcam): trügt = VbSIm92,trügen,null
getXiffus(macht/thcam): trügt = VbSPr92,trügen,null
getXiffus(macht/thcam): trügt = VbSPr13,trügen,null
getXiffus(macht/thcam): trügt = VbSCt92,tragen,null
getXiffus(macht/thcam): schlügt = VbSCt92,schlagen,null
getXiffus(macht/thcam): lügt = VbSCs92,lügen,null
getXiffus(macht/thcam): lügt = VbSIm92,lügen,null
getXiffus(macht/thcam): lügt = VbSPr92,lügen,null
getXiffus(macht/thcam): lügt = VbSPr13,lügen,null
getXiffus(macht/thcam): zögt = VbSCt92,ziehen,null
getXiffus(macht/thcam): erwögt = VbSCt92,erwägen,null
getXiffus(macht/thcam): bewögt = VbSCt92,bewegen,null
testTableLookup(macht), state = 3
testVariants(macht), state = 4
testTableLookup(Macht), state = 0
testTableLookup(Macht), state = 1
getRoots(Macht): Macht =SbSgFm,,
getRoots: add Macht =SbSgFm,,
getRoots(Macht): Macher =SbSgMs,,
getRoots(Macht): Mache =SbSgFm,,
getRoots(Macht): Mach =SbSgNtMeas,,
getRoots: add Mach =SbSgNtMeas,,
getRoots(Macht): Mac =SbSgMsTitlForg.En,,
getRoots: add Mac =SbSgMsTitlForg.En,,
getRoots(Macht): Maat =SbSgMsProf,,
getRoots(Macht): Maas =NmGeogFlumForg.Be,,
getRoots(Macht): Lüster =SbSgMs,,
getRoots(Macht): Lümmel =SbSgMsPers,,
getRoots(Macht): Lügner =SbSgMs,,
getRoots(Macht): Lüge =SbSgFm,,
getRoots(Macht): Lüfter =SbSgMs,,
getRoots(Macht): Lüftchen =SbSgNtDimtMeto,,
getRoots(Macht): Lücke =SbSgFm,,
getRoots(Macht): Lübke =NmSurn,,
getRoots(Macht): Löß =SbSgMs,,
Macht	SbSgFm

words(nur): nur =Un,null,null
nur	Un

words(einen): einen =ArUndtAccvSgMs,null,null
words(einen): einen =PnUndtAccv,null,null
einen	ArUndtAccvSgMs
einen	PnUndtAccv

testTableLookup(Plan), state = 0
testTableLookup(Plan), state = 1
getRoots(Plan): Plan =SbSgMs,,
getRoots: add Plan =SbSgMs,,
getRoots(Plan): Plaid =SbSgNtForg,,
getRoots(Plan): Plage =SbSgFm,,
getRoots(Plan): Piz =SbSgMsGeogMontForg,,
getRoots(Plan): Pixel =SbSgNtForg,,
getRoots(Plan): Piste =SbSgFm,,
getRoots(Plan): Pisser =SbSgMsPers,,
getRoots(Plan): Pisse =SbSgFm,,
getRoots(Plan): Pirsch =SbSgFm,,
getRoots(Plan): Pipe =SbSgFmForg.En,,
getRoots(Plan): Pinte =SbSgFm,,
getRoots(Plan): Pint =SbSgFmForg,,
getRoots(Plan): Pinsel =SbSgMs,,
getRoots(Plan): Pinscher =SbSgMsZool,,
getRoots(Plan): Pinne =SbSgFm,,
getRoots(Plan): Pinkel =SbSgMs,,
Plan	SbSgMs

words(und): und =Cj,null,null
und	Cj

words(seid): seid =VbSPr92,sein,null
words(seid): seid =VbSIm92,sein,null
words(seid): seid =VbSCs92,sein,null
seid	VbSPr92	sein
seid	VbSIm92	sein
seid	VbSCs92	sein

words(ein): ein =ArUndtNomvSgMs,null,null
words(ein): ein =ArUndtNomvSgNt,null,null
words(ein): ein =ArUndtAccvSgNt,null,null
ein	ArUndtNomvSgMs
ein	ArUndtNomvSgNt
ein	ArUndtAccvSgNt

testTableLookup(großes), state = 0
testTableLookup(großes), state = 1
getRoots(großes): groß/zieh =VbRtWeak,en,VbIn
getRoots(großes): groß/schreib =VbRtWeak,en,VbIn
getRoots(großes): groß =AjRoot,null,null
getRoots: add groß =AjRoot,null,null
getRoots(großes): gross/zieh =ExUE,groß/zieh,VbRtWeak
getRoots(großes): gross/schreib =ExUE,groß/schreib,VbRtWeak
getRoots(großes): gross =ExUE,groß,AjRoot
getRoots(großes): groesst =ExUE,größt,AjSupl
getRoots(großes): groesser =ExUE,größer,AjCmpr
getRoots(großes): groebst =ExUE,gröbst,AjSupl
getRoots(großes): groeber =ExUE,gröber,AjCmpr
getRoots(großes): grob =AjRoot,null,null
getRoots(großes): grimass =VbRtWeak,ieren,null
getRoots(großes): grill =VbRtWeak,ieren,null
getRoots(großes): gravit =VbRtWeak,ieren,null
getRoots(großes): grav =VbRtWeak,ieren,null
getRoots(großes): grau =AjColr.C0C0C0,null,null
es	AjXP

testTableLookup(Licht), state = 0
testTableLookup(Licht), state = 1
getRoots(Licht): Licht =SbSgNt,,
getRoots: add Licht =SbSgNt,,
getRoots(Licht): Lex =SbSgNtForg.Lt,,
getRoots(Licht): Level =SbSgMsForg.En,,
getRoots(Licht): Leute =SbPlPers,,
getRoots(Licht): Leutchen =SbSgNtDimtPers,,
getRoots(Licht): Leugner =SbSgMsPers,,
getRoots(Licht): Leuchter =SbSgMs,,
getRoots(Licht): Leuchte =SbSgFm,,
getRoots(Licht): Leu =SbSgMsZool,,
getRoots(Licht): Lettner =SbSgMs,,
getRoots(Licht): Lettland =NmGeogCtry.Lv,,
getRoots(Licht): Letter =SbSgFm,,
getRoots(Licht): Letten =SbPlPersGeogCtry.Lv,,
getRoots(Licht): Lette =SbSgMsPersGeogCtry.Lv,,
getRoots(Licht): Leser =SbSgMsPers,,
getRoots(Licht): Lesbe =SbSgFmPers,,
Licht	SbSgNt

und	Cj

Macht	SbSgFm

words(noch): noch =Cj,null,null
noch	Cj

einen	ArUndtAccvSgMs
einen	PnUndtAccv

testTableLookup(andern), state = 0
testTableLookup(andern), state = 1
getRoots(andern): anderes =AjQant,ander,AjRootQant
getRoots(andern): anderer =AjQant,ander,AjRootQant
getRoots(andern): anderen =AjQant,ander,AjRootQant
getRoots(andern): anderem =AjQant,ander,AjRootQant
getRoots(andern): andere =AjQant,ander,AjRootQant
getRoots(andern): anatom =VbRtWeak,ieren,null
getRoots(andern): anathematis =VbRtWeak,ieren,null
getRoots(andern): analys =VbRtWeak,ieren,null
getRoots(andern): anaesthetis =ExUE,anästhetis,VbRtWeak
getRoots(andern): anaesthes =ExUE,anästhes,VbRtWeak
getRoots(andern): an/öd =VbRtWeak,en,VbIn
getRoots(andern): an/zünd =VbRtWeak,en,VbIn
getRoots(andern): an/zähl =VbRtWeak,en,VbIn
getRoots(andern): an/zwitsch =VbRtWeak,ern,VbIn
getRoots(andern): an/zweif =VbRtWeak,eln,VbIn
getRoots(andern): an/zweck =VbRtWeak,en,VbIn
testTableLookup(andern), state = 2
getXiffus(andern/nredna): tion = SbSgFm,null,null
getXiffus(andern/nredna): ion = SbSgFm,null,null
getXiffus(andern/nredna): phon = SbSgNt,null,null
getXiffus(andern/nredna): fon = SbSgNt,null,null
getXiffus(andern/nredna): gewinn = VbSIm12,gewinnen,null
getXiffus(andern/nredna): besinn = VbSIm12,besinnen,null
getXiffus(andern/nredna): sinn = VbSIm12,sinnen,null
getXiffus(andern/nredna): rinn = VbSIm12,rinnen,null
getXiffus(andern/nredna): spinn = VbSIm12,spinnen,null
getXiffus(andern/nredna): beginn = VbSIm12,beginnen,null
getXiffus(andern/nredna): brenn = VbSIm12,brennen,null
getXiffus(andern/nredna): renn = VbSIm12,rennen,null
getXiffus(andern/nredna): nenn = VbSIm12,nennen,null
getXiffus(andern/nredna): kenn = VbSIm12,kennen,null
getXiffus(andern/nredna): gewann = VbSIp13,gewinnen,null
getXiffus(andern/nredna): gewann = VbSIp11,gewinnen,null
testTableLookup(andern), state = 3
testVariants(andern), state = 4
testTableLookup(Andern), state = 0
testTableLookup(Andern), state = 1
getRoots(Andern): Anden =NmGeogMontForg.Ar,,
getRoots(Andern): Amt =SbSgNt,,
getRoots(Andern): Amsel =SbSgFmZool,,
getRoots(Andern): Amper =NmGeogFlum,,
getRoots(Andern): Ampel =SbSgFm,,
getRoots(Andern): Ammer =NmGeogFlum,,
getRoots(Andern): Amme =SbSgFmProf,,
getRoots(Andern): Alter =SbSgNt,,
getRoots(Andern): Alte =SbSgFm,,
getRoots(Andern): Alster =NmGeogFlum,,
getRoots(Andern): Alp =SbSgMs,,
getRoots(Andern): Alm =SbSgFm,,
getRoots(Andern): Alge =SbSgFmBota,,
getRoots(Andern): Ale =SbSgNtNutr,,
getRoots(Andern): Albe =SbSgFm,,
getRoots(Andern): Alb =SbSgMs,,
testTableLookup(Andern), state = 2
getXiffus(Andern/nrednA): tion = SbSgFm,null,null
getXiffus(Andern/nrednA): ion = SbSgFm,null,null
getXiffus(Andern/nrednA): phon = SbSgNt,null,null
getXiffus(Andern/nrednA): fon = SbSgNt,null,null
getXiffus(Andern/nrednA): gewinn = VbSIm12,gewinnen,null
getXiffus(Andern/nrednA): besinn = VbSIm12,besinnen,null
getXiffus(Andern/nrednA): sinn = VbSIm12,sinnen,null
getXiffus(Andern/nrednA): rinn = VbSIm12,rinnen,null
getXiffus(Andern/nrednA): spinn = VbSIm12,spinnen,null
getXiffus(Andern/nrednA): beginn = VbSIm12,beginnen,null
getXiffus(Andern/nrednA): brenn = VbSIm12,brennen,null
getXiffus(Andern/nrednA): renn = VbSIm12,rennen,null
getXiffus(Andern/nrednA): nenn = VbSIm12,nennen,null
getXiffus(Andern/nrednA): kenn = VbSIm12,kennen,null
getXiffus(Andern/nrednA): gewann = VbSIp13,gewinnen,null
getXiffus(Andern/nrednA): gewann = VbSIp11,gewinnen,null
testTableLookup(Andern), state = 3
testVariants(andern), state = 12
testTableLookup(Andern), state = 0
testTableLookup(Andern), state = 1
getRoots(Andern): Anden =NmGeogMontForg.Ar,,
getRoots(Andern): Amt =SbSgNt,,
getRoots(Andern): Amsel =SbSgFmZool,,
getRoots(Andern): Amper =NmGeogFlum,,
getRoots(Andern): Ampel =SbSgFm,,
getRoots(Andern): Ammer =NmGeogFlum,,
getRoots(Andern): Amme =SbSgFmProf,,
getRoots(Andern): Alter =SbSgNt,,
getRoots(Andern): Alte =SbSgFm,,
getRoots(Andern): Alster =NmGeogFlum,,
getRoots(Andern): Alp =SbSgMs,,
getRoots(Andern): Alm =SbSgFm,,
getRoots(Andern): Alge =SbSgFmBota,,
getRoots(Andern): Ale =SbSgNtNutr,,
getRoots(Andern): Albe =SbSgFm,,
getRoots(Andern): Alb =SbSgMs,,
testTableLookup(Andern), state = 2
getXiffus(Andern/nrednA): tion = SbSgFm,null,null
getXiffus(Andern/nrednA): ion = SbSgFm,null,null
getXiffus(Andern/nrednA): phon = SbSgNt,null,null
getXiffus(Andern/nrednA): fon = SbSgNt,null,null
getXiffus(Andern/nrednA): gewinn = VbSIm12,gewinnen,null
getXiffus(Andern/nrednA): besinn = VbSIm12,besinnen,null
getXiffus(Andern/nrednA): sinn = VbSIm12,sinnen,null
getXiffus(Andern/nrednA): rinn = VbSIm12,rinnen,null
getXiffus(Andern/nrednA): spinn = VbSIm12,spinnen,null
getXiffus(Andern/nrednA): beginn = VbSIm12,beginnen,null
getXiffus(Andern/nrednA): brenn = VbSIm12,brennen,null
getXiffus(Andern/nrednA): renn = VbSIm12,rennen,null
getXiffus(Andern/nrednA): nenn = VbSIm12,nennen,null
getXiffus(Andern/nrednA): kenn = VbSIm12,kennen,null
getXiffus(Andern/nrednA): gewann = VbSIp13,gewinnen,null
getXiffus(Andern/nrednA): gewann = VbSIp11,gewinnen,null
testTableLookup(Andern), state = 3
testVariants(andern), state = 20
testTableLookup(Andern), state = 0
testTableLookup(Andern), state = 1
getRoots(Andern): Anden =NmGeogMontForg.Ar,,
getRoots(Andern): Amt =SbSgNt,,
getRoots(Andern): Amsel =SbSgFmZool,,
getRoots(Andern): Amper =NmGeogFlum,,
getRoots(Andern): Ampel =SbSgFm,,
getRoots(Andern): Ammer =NmGeogFlum,,
getRoots(Andern): Amme =SbSgFmProf,,
getRoots(Andern): Alter =SbSgNt,,
getRoots(Andern): Alte =SbSgFm,,
getRoots(Andern): Alster =NmGeogFlum,,
getRoots(Andern): Alp =SbSgMs,,
getRoots(Andern): Alm =SbSgFm,,
getRoots(Andern): Alge =SbSgFmBota,,
getRoots(Andern): Ale =SbSgNtNutr,,
getRoots(Andern): Albe =SbSgFm,,
getRoots(Andern): Alb =SbSgMs,,
testTableLookup(Andern), state = 2
getXiffus(Andern/nrednA): tion = SbSgFm,null,null
getXiffus(Andern/nrednA): ion = SbSgFm,null,null
getXiffus(Andern/nrednA): phon = SbSgNt,null,null
getXiffus(Andern/nrednA): fon = SbSgNt,null,null
getXiffus(Andern/nrednA): gewinn = VbSIm12,gewinnen,null
getXiffus(Andern/nrednA): besinn = VbSIm12,besinnen,null
getXiffus(Andern/nrednA): sinn = VbSIm12,sinnen,null
getXiffus(Andern/nrednA): rinn = VbSIm12,rinnen,null
getXiffus(Andern/nrednA): spinn = VbSIm12,spinnen,null
getXiffus(Andern/nrednA): beginn = VbSIm12,beginnen,null
getXiffus(Andern/nrednA): brenn = VbSIm12,brennen,null
getXiffus(Andern/nrednA): renn = VbSIm12,rennen,null
getXiffus(Andern/nrednA): nenn = VbSIm12,nennen,null
getXiffus(Andern/nrednA): kenn = VbSIm12,kennen,null
getXiffus(Andern/nrednA): gewann = VbSIp13,gewinnen,null
getXiffus(Andern/nrednA): gewann = VbSIp11,gewinnen,null
testTableLookup(Andern), state = 3
testVariants(andern), state = 28
testTableLookup(Andern), state = 0
testTableLookup(Andern), state = 1
getRoots(Andern): Anden =NmGeogMontForg.Ar,,
getRoots(Andern): Amt =SbSgNt,,
getRoots(Andern): Amsel =SbSgFmZool,,
getRoots(Andern): Amper =NmGeogFlum,,
getRoots(Andern): Ampel =SbSgFm,,
getRoots(Andern): Ammer =NmGeogFlum,,
getRoots(Andern): Amme =SbSgFmProf,,
getRoots(Andern): Alter =SbSgNt,,
getRoots(Andern): Alte =SbSgFm,,
getRoots(Andern): Alster =NmGeogFlum,,
getRoots(Andern): Alp =SbSgMs,,
getRoots(Andern): Alm =SbSgFm,,
getRoots(Andern): Alge =SbSgFmBota,,
getRoots(Andern): Ale =SbSgNtNutr,,
getRoots(Andern): Albe =SbSgFm,,
getRoots(Andern): Alb =SbSgMs,,
testTableLookup(Andern), state = 2
getXiffus(Andern/nrednA): tion = SbSgFm,null,null
getXiffus(Andern/nrednA): ion = SbSgFm,null,null
getXiffus(Andern/nrednA): phon = SbSgNt,null,null
getXiffus(Andern/nrednA): fon = SbSgNt,null,null
getXiffus(Andern/nrednA): gewinn = VbSIm12,gewinnen,null
getXiffus(Andern/nrednA): besinn = VbSIm12,besinnen,null
getXiffus(Andern/nrednA): sinn = VbSIm12,sinnen,null
getXiffus(Andern/nrednA): rinn = VbSIm12,rinnen,null
getXiffus(Andern/nrednA): spinn = VbSIm12,spinnen,null
getXiffus(Andern/nrednA): beginn = VbSIm12,beginnen,null
getXiffus(Andern/nrednA): brenn = VbSIm12,brennen,null
getXiffus(Andern/nrednA): renn = VbSIm12,rennen,null
getXiffus(Andern/nrednA): nenn = VbSIm12,nennen,null
getXiffus(Andern/nrednA): kenn = VbSIm12,kennen,null
getXiffus(Andern/nrednA): gewann = VbSIp13,gewinnen,null
getXiffus(Andern/nrednA): gewann = VbSIp11,gewinnen,null
testTableLookup(Andern), state = 3
andern	Xy

Plan	SbSgMs

testTableLookup(gehn), state = 0
testTableLookup(gehn), state = 1
getRoots(gehn): geheim =AjRoot,null,null
getRoots(gehn): gehab =VbRtWeak,en,VbIn
getRoots(gehn): gegenüber/tret =VbRtWeak,en,VbIn
getRoots(gehn): gegenüber/stell =VbRtWeak,en,VbIn
getRoots(gehn): gegenüber/steh =VbRtWeak,en,VbIn
getRoots(gehn): gegenüber/sitz =VbRtWeak,en,VbIn
getRoots(gehn): gegenüber/seh =VbRtWeak,en,VbIn
getRoots(gehn): gegenüber/lieg =VbRtWeak,en,VbIn
getRoots(gehn): gegenueber/tret =ExUE,gegenüber/tret,VbRtWeak
getRoots(gehn): gegenueber/stell =ExUE,gegenüber/stell,VbRtWeak
getRoots(gehn): gegenueber/steh =ExUE,gegenüber/steh,VbRtWeak
getRoots(gehn): gegenueber/sitz =ExUE,gegenüber/sitz,VbRtWeak
getRoots(gehn): gegenueber/seh =ExUE,gegenüber/seh,VbRtWeak
getRoots(gehn): gegenueber/lieg =ExUE,gegenüber/lieg,VbRtWeak
getRoots(gehn): gegen/zeichn =VbRtWeak,en,VbIn
getRoots(gehn): gegen/les =VbRtWeak,en,VbIn
testTableLookup(gehn), state = 2
getXiffus(gehn/nheg): säßen = VbSCt93,sitzen,null
getXiffus(gehn/nheg): säßen = VbSCt91,sitzen,null
getXiffus(gehn/nheg): fräßen = VbSCt93,fressen,null
getXiffus(gehn/nheg): fräßen = VbSCt91,fressen,null
getXiffus(gehn/nheg): gemäßen = AjXP,null,null
getXiffus(gehn/nheg): mäßen = VbSCt93,messen,null
getXiffus(gehn/nheg): mäßen = VbSCt91,messen,null
getXiffus(gehn/nheg): vergäßen = VbSCt93,vergessen,null
getXiffus(gehn/nheg): vergäßen = VbSCt91,vergessen,null
getXiffus(gehn/nheg): äßen = VbSCt93,essen,null
getXiffus(gehn/nheg): äßen = VbSCt91,essen,null
getXiffus(gehn/nheg): gestoßen = VbSPa0,stoßen,null
getXiffus(gehn/nheg): stoßen = VbSCs93,stoßen,null
getXiffus(gehn/nheg): stoßen = VbSCs91,stoßen,null
getXiffus(gehn/nheg): stoßen = VbSIm91,stoßen,null
getXiffus(gehn/nheg): stoßen = VbSPr93,stoßen,null
testTableLookup(gehn), state = 3
testVariants(gehn), state = 4
testTableLookup(Gehn), state = 0
testTableLookup(Gehn), state = 1
getRoots(Gehn): Geher =SbSgMs,,
getRoots(Gehn): Gegner =SbSgMs,,
getRoots(Gehn): Gefecht =SbSgNt,,
getRoots(Gehn): Gedanke =SbSgMs,,
getRoots(Gehn): Geck =SbSgMsPers,,
getRoots(Gehn): Gebäck =SbSgNt,,
getRoots(Gehn): Geburt =SbSgFm,,
getRoots(Gehn): Gebot =SbSgNt,,
getRoots(Gehn): Geber =SbSgMs,,
getRoots(Gehn): Gaze =SbSgFmForg.Fr,,
getRoots(Gehn): Gauß =NmSurn,,
getRoots(Gehn): Gautscher =SbSgMs,,
getRoots(Gehn): Gauner =SbSgMsPers,,
getRoots(Gehn): Gaumen =SbSgMsBody,,
getRoots(Gehn): Gaulle =NmSurnForg.Fr,,
getRoots(Gehn): Gaul =SbSgMsZool,,
testTableLookup(Gehn), state = 2
getXiffus(Gehn/nheG): säßen = VbSCt93,sitzen,null
getXiffus(Gehn/nheG): säßen = VbSCt91,sitzen,null
getXiffus(Gehn/nheG): fräßen = VbSCt93,fressen,null
getXiffus(Gehn/nheG): fräßen = VbSCt91,fressen,null
getXiffus(Gehn/nheG): gemäßen = AjXP,null,null
getXiffus(Gehn/nheG): mäßen = VbSCt93,messen,null
getXiffus(Gehn/nheG): mäßen = VbSCt91,messen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt93,vergessen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt91,vergessen,null
getXiffus(Gehn/nheG): äßen = VbSCt93,essen,null
getXiffus(Gehn/nheG): äßen = VbSCt91,essen,null
getXiffus(Gehn/nheG): gestoßen = VbSPa0,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs93,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSIm91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSPr93,stoßen,null
testTableLookup(Gehn), state = 3
testVariants(gehn), state = 12
testTableLookup(Gehn), state = 0
testTableLookup(Gehn), state = 1
getRoots(Gehn): Geher =SbSgMs,,
getRoots(Gehn): Gegner =SbSgMs,,
getRoots(Gehn): Gefecht =SbSgNt,,
getRoots(Gehn): Gedanke =SbSgMs,,
getRoots(Gehn): Geck =SbSgMsPers,,
getRoots(Gehn): Gebäck =SbSgNt,,
getRoots(Gehn): Geburt =SbSgFm,,
getRoots(Gehn): Gebot =SbSgNt,,
getRoots(Gehn): Geber =SbSgMs,,
getRoots(Gehn): Gaze =SbSgFmForg.Fr,,
getRoots(Gehn): Gauß =NmSurn,,
getRoots(Gehn): Gautscher =SbSgMs,,
getRoots(Gehn): Gauner =SbSgMsPers,,
getRoots(Gehn): Gaumen =SbSgMsBody,,
getRoots(Gehn): Gaulle =NmSurnForg.Fr,,
getRoots(Gehn): Gaul =SbSgMsZool,,
testTableLookup(Gehn), state = 2
getXiffus(Gehn/nheG): säßen = VbSCt93,sitzen,null
getXiffus(Gehn/nheG): säßen = VbSCt91,sitzen,null
getXiffus(Gehn/nheG): fräßen = VbSCt93,fressen,null
getXiffus(Gehn/nheG): fräßen = VbSCt91,fressen,null
getXiffus(Gehn/nheG): gemäßen = AjXP,null,null
getXiffus(Gehn/nheG): mäßen = VbSCt93,messen,null
getXiffus(Gehn/nheG): mäßen = VbSCt91,messen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt93,vergessen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt91,vergessen,null
getXiffus(Gehn/nheG): äßen = VbSCt93,essen,null
getXiffus(Gehn/nheG): äßen = VbSCt91,essen,null
getXiffus(Gehn/nheG): gestoßen = VbSPa0,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs93,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSIm91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSPr93,stoßen,null
testTableLookup(Gehn), state = 3
testVariants(gehn), state = 20
testTableLookup(Gehn), state = 0
testTableLookup(Gehn), state = 1
getRoots(Gehn): Geher =SbSgMs,,
getRoots(Gehn): Gegner =SbSgMs,,
getRoots(Gehn): Gefecht =SbSgNt,,
getRoots(Gehn): Gedanke =SbSgMs,,
getRoots(Gehn): Geck =SbSgMsPers,,
getRoots(Gehn): Gebäck =SbSgNt,,
getRoots(Gehn): Geburt =SbSgFm,,
getRoots(Gehn): Gebot =SbSgNt,,
getRoots(Gehn): Geber =SbSgMs,,
getRoots(Gehn): Gaze =SbSgFmForg.Fr,,
getRoots(Gehn): Gauß =NmSurn,,
getRoots(Gehn): Gautscher =SbSgMs,,
getRoots(Gehn): Gauner =SbSgMsPers,,
getRoots(Gehn): Gaumen =SbSgMsBody,,
getRoots(Gehn): Gaulle =NmSurnForg.Fr,,
getRoots(Gehn): Gaul =SbSgMsZool,,
testTableLookup(Gehn), state = 2
getXiffus(Gehn/nheG): säßen = VbSCt93,sitzen,null
getXiffus(Gehn/nheG): säßen = VbSCt91,sitzen,null
getXiffus(Gehn/nheG): fräßen = VbSCt93,fressen,null
getXiffus(Gehn/nheG): fräßen = VbSCt91,fressen,null
getXiffus(Gehn/nheG): gemäßen = AjXP,null,null
getXiffus(Gehn/nheG): mäßen = VbSCt93,messen,null
getXiffus(Gehn/nheG): mäßen = VbSCt91,messen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt93,vergessen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt91,vergessen,null
getXiffus(Gehn/nheG): äßen = VbSCt93,essen,null
getXiffus(Gehn/nheG): äßen = VbSCt91,essen,null
getXiffus(Gehn/nheG): gestoßen = VbSPa0,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs93,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSIm91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSPr93,stoßen,null
testTableLookup(Gehn), state = 3
testVariants(gehn), state = 28
testTableLookup(Gehn), state = 0
testTableLookup(Gehn), state = 1
getRoots(Gehn): Geher =SbSgMs,,
getRoots(Gehn): Gegner =SbSgMs,,
getRoots(Gehn): Gefecht =SbSgNt,,
getRoots(Gehn): Gedanke =SbSgMs,,
getRoots(Gehn): Geck =SbSgMsPers,,
getRoots(Gehn): Gebäck =SbSgNt,,
getRoots(Gehn): Geburt =SbSgFm,,
getRoots(Gehn): Gebot =SbSgNt,,
getRoots(Gehn): Geber =SbSgMs,,
getRoots(Gehn): Gaze =SbSgFmForg.Fr,,
getRoots(Gehn): Gauß =NmSurn,,
getRoots(Gehn): Gautscher =SbSgMs,,
getRoots(Gehn): Gauner =SbSgMsPers,,
getRoots(Gehn): Gaumen =SbSgMsBody,,
getRoots(Gehn): Gaulle =NmSurnForg.Fr,,
getRoots(Gehn): Gaul =SbSgMsZool,,
testTableLookup(Gehn), state = 2
getXiffus(Gehn/nheG): säßen = VbSCt93,sitzen,null
getXiffus(Gehn/nheG): säßen = VbSCt91,sitzen,null
getXiffus(Gehn/nheG): fräßen = VbSCt93,fressen,null
getXiffus(Gehn/nheG): fräßen = VbSCt91,fressen,null
getXiffus(Gehn/nheG): gemäßen = AjXP,null,null
getXiffus(Gehn/nheG): mäßen = VbSCt93,messen,null
getXiffus(Gehn/nheG): mäßen = VbSCt91,messen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt93,vergessen,null
getXiffus(Gehn/nheG): vergäßen = VbSCt91,vergessen,null
getXiffus(Gehn/nheG): äßen = VbSCt93,essen,null
getXiffus(Gehn/nheG): äßen = VbSCt91,essen,null
getXiffus(Gehn/nheG): gestoßen = VbSPa0,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs93,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSCs91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSIm91,stoßen,null
getXiffus(Gehn/nheG): stoßen = VbSPr93,stoßen,null
testTableLookup(Gehn), state = 3
gehn	Xy

words(tun): tun =VbSIn0,tun,null
words(tun): tun =VbSPr91,tun,null
words(tun): tun =VbSPr93,tun,null
words(tun): tun =VbSIm91,tun,null
tun	VbSIn0	tun
tun	VbSPr91	tun
tun	VbSPr93	tun
tun	VbSIm91	tun

words(sie): sie =PnSgPersNomvFm3,null,null
words(sie): sie =PnPlPersNomv3,null,null
words(sie): sie =PnSgPersAccv3Fm,null,null
words(sie): sie =PnPlPersAccv3,null,null
sie	PnSgPersNomvFm3
sie	PnPlPersNomv3
sie	PnSgPersAccv3Fm
sie	PnPlPersAccv3

testTableLookup(beide), state = 0
testTableLookup(beide), state = 1
getRoots(beide): beide =AjQant,beid,AjRootQant
getRoots: add beide =AjQant,beid,AjRootQant
getRoots(beide): beibehalt =VbRtWeak,en,VbIn
getRoots(beide): bei/zieh =VbRtWeak,en,VbIn
getRoots(beide): bei/wohn =VbRtWeak,en,VbIn
getRoots(beide): bei/tret =VbRtWeak,en,VbIn
getRoots(beide): bei/treib =VbRtWeak,en,VbIn
getRoots(beide): bei/trag =VbRtWeak,en,VbIn
getRoots(beide): bei/stimm =VbRtWeak,en,VbIn
getRoots(beide): bei/steh =VbRtWeak,en,VbIn
getRoots(beide): bei/spring =VbRtWeak,en,VbIn
getRoots(beide): bei/setz =VbRtWeak,en,VbIn
getRoots(beide): bei/schlag =VbRtWeak,en,VbIn
getRoots(beide): bei/schlaf =VbRtWeak,en,VbIn
getRoots(beide): bei/schieß =VbRtWeak,en,VbIn
getRoots(beide): bei/pflicht =VbRtWeak,en,VbIn
getRoots(beide): bei/pack =VbRtWeak,en,VbIn
beide	AjQant	beid	AjRootQant

words(nicht): nicht =Un,null,null
nicht	Un

