#!/usr/bin/perl

#
#  Copyright 2006 Dr. Georg Fischer <punctum at punctum dot kom>
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# @(#) $Id: books.pl 36 2008-09-08 06:05:06Z gfis $
# generate raw INSERT values for 'infos' table 
# 2007-02-20, Dr. Georg Fischer <punctum@punctum.com>
# activation:
#   perl books.pl | $(DBAT) -m csv -s "#" -r infos
#
# caution, this file is UTF-8 encoded: äöüÄÖÜ
#
# For each DATA line below, the following rows for table INFOS
# (with dict columns ENTRY, MORPH, ENREL, MOREL) are generated:
# 1. ($en_abbr  , "en.abbr" , $bookno   , ""        )
# 2. ($en_name  , "en.name" , $bookno   , "5"       )
# 3. ($book_no  , "book.no" , $abbr     , "en.abbr" )
# n. ($de_name  , "de.name" , $bookno   , "2"       ) <- maybe multiple
#
# Any punctuation and whitespace is removed from the whole line.
# If any of the name fields contains a digit, this digit is moved to MOREL.
#----------------------------------------------------------------
use strict;
use utf8;
    binmode(STDOUT, ":utf8");
    my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
    my $timestamp = sprintf ("%04d-%02d-%02dT%02d:%02d:%02d"
            , $year + 1900, $mon + 1, $mday, $hour, $min, $sec);
    # print "# generated by books.pl at $timestamp - do not edit here\n";

# evaluate arguments
    my $code = shift(@ARGV);
    
# read DATA
    while (<DATA>) {
        s/\r?\n//; # chompr
        s/[\. ]//g; # remove whitespace and punctuation
        my ($book_no, $en_abbr, $en_name, @de_names) = split (/\#/);;
        my $ab_ord  = ""; # ($en_abbr =~ s/(\d)//) > 0 ? $1 : "";
        my $en_ord  = ($en_name =~ s/(\d)//) > 0 ? $1 : "";
        print <<"GFis";
$en_abbr#en.abbr#$book_no#$ab_ord
$en_name#en.name#$book_no#$en_ord
$book_no#book.no#$en_abbr#en.abbr
GFis
        foreach my $de_name(@de_names) {
            my $de_ord  = ($de_name =~ s/(\d)//) > 0 ? $1 : "";
            print <<"GFis";
$de_name#de.name#$book_no#$de_ord
GFis
        } # foreach $de_name
    } # while DATA
# 00    UTF-8-äöüÄÖÜß    key English_name    German_name
__DATA__
01#Ge#Genesis#1. Mose#1 Mos#Gen
02#Ex#Exodus#2. Mose#2 Mos#Ex
03#Le#Leviticus#3. Mose#3 Mos#Lev
04#Nu#Numbers#4. Mose#4 Mos#Num#Nu
05#De#Deuteronomy#5. Mose#5 Mos#Deu#De
06#Jos#Joshua#Josua#Jos
07#Jud#Judges#Richter#Richt
08#Ru#Ruth#Rut#Ruth#
09#1Sa#1 Samuel#1. Samuel#1 Sam
10#2Sa#2 Samuel#2. Samuel#2 Sam
11#1Ki#1 Kings#1. Könige#1 Kön
12#2Ki#2 Kings#2. Könige#2 Kön
13#1Ch#1 Chronicles#1. Chronik#1 Chr
14#2Ch#2 Chronicles#2. Chronik#2 Chr
15#Ezr#Ezra#Esra#Esr
16#Ne#Nehemiah#Nehemia#Neh#Ne
17#Es#Esther#Ester#Est#Es
18#Job#Job#Hiob#Iob
19#Ps#Psalms#Psalmen#Ps#Psalm
20#Pr#Proverbs#Sprüche#Spr
21#Ec#Ecclesiastes#Prediger#Pred#Koholet#Koh
22#So#Song of Solomon#Hohelied#Hoh
23#Isa#Isaiah#Jesaja#Jes
24#Jer#Jeremiah#Jeremia#Jer
25#La#Lamentations#Klagelieder#Klgl#Klgld
26#Eze#Ezekiel#Hesekiel#Hes#Hese#Hezekiel#Hez
27#Da#Daniel#Daniel#Dan#
28#Ho#Hosea#Hosea#Hos
29#Joe#Joel#Joel#Joe
30#Am#Amos#Amos#Am
31#Ob#Obadiah#Obadja#Oba Ob
32#Jon#Jonah#Jona#Jon
33#Mic#Micah#Micha#Mic#Mi
34#Na#Nahum#Nahum#Nah#Na
35#Hab#Habakkuk#Habakuk#Hab
36#Zep#Zephaniah#Zephanja#Zeph#Zep#Zef Zefania
37#Hag#Haggai#Haggai#Hag
38#Zec#Zechariah#Sacharja#Sach#Sac
39#Mal#Malachi#Maleachi#Mal
40#Mt#Matthew#Matthäus#Matth#Mat#Mt
41#Mr#Mark#Markus#Mark#Mar#Mr#Mk
42#Lu#Luke#Lukas#Luk#Lk
43#Joh#John#Johannes#Joh
44#Ac#Acts#Apostelgeschichte#Apg
45#Ro#Romans#Römer#Röm
46#1Co#1 Corinthians#1. Korinther#1 Kor
47#2Co#2 Corinthians#2. Korinther#2 Kor
48#Ga#Galatians#Galater#Gal
49#Eph#Ephesians#Epheser#Eph
50#Php#Philippians#Philipper#Phil
51#Col#Colossians#Kolosser#Kol
52#1Th#1 Thessalonians#1. Thessalonicher#1 Thess#1 The
53#2Th#2 Thessalonians#2. Thessalonicher#2 Thess#2 The
54#1Ti#1 Timothy#1. Timotheus#1 Tim
55#2Ti#2 Timothy#2. Timotheus#2 Tim
56#Tit#Titus#Titus#Tit
57#Phm#Philemon#Philemon#Phim
58#Heb#Hebrews#Hebräer#Heb#Hebr
59#Jas#James#Jakobus#Jak
60#1Pe#1 Peter#1. Petrus#1 Petr#1 Pet
61#2Pe#2 Peter#2. Petrus#2 Petr#2 Pet
62#1Jo#1 John#1. Johannes#1 Joh#
63#2Jo#2 John#2. Johannes#2 Joh
64#3Jo#3 John#3. Johannes#3 Joh
65#Jude#Jude#Judas#Jud#
66#Re#Revelation#Offenbarung#Offenb#Offb
67#Tob#Tobit#Tobit#Tob
68#Jdi#Judit#Judit#Jud
69#1Mc#1 Maccabeans#1. Makkabäer#1 Mak
70#2Mc#2 Maccabeans#2. Makkabäer#2 Mak
71#Wis#Wisdom#Weisheit#Weis#Weish
72#Sir#Sirach#Sirach#Sir
73#Bar#Baruch#Baruch#Bar
