#!/usr/bin/perl

#
#  Copyright 2006 Dr. Georg Fischer <punctum at punctum dot kom>
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# list of 207 German rivers with length >= 50 km
# from http://de.wikipedia.org/wiki/Liste_der_Fl%C3%BCsse_in_Deutschland
# take single words only
# @(#) $Id: de_river.pl 36 2008-09-08 06:05:06Z gfis $
# 2006-08-13, Georg Fischer

use strict;
    binmode(STDOUT, ":utf8");

    while (<DATA>) {
        my $genus = "Fm";
        $genus = "Ms" if substr($_, 11,1) eq "m";
        m/\[\[([^\(\|\]]+)/;
        my $river = $1;
        $river =~ s/ $//;
        next if ($river =~ m/ /);
        print "$river   =Nm${genus}GeogFlum.De\n";
    }
__DATA__
# 2.888 km - [[Donau]] - <small>mit Quellfluss [[Breg]]</small> (Schwarzes Meer)
# 1.320 km m [[Rhein]] (Nordsee)
# 1.091 km - [[Elbe]] (Nordsee)
#   866 km - [[Oder]] (Ostsee)
#   545 km - [[Mosel]] (Rhein)
#   524 km m [[Main]] - <small>längster Fluss der ausschließlich in Deutschland verläuft</small> (Rhein)
#   517 km m [[Inn]] (Donau)
#   452 km - [[Weser]] - <small>mit Werra 744 km lang; wasserreichster Fluss der ausschließlich in Deutschland verläuft</small> (Nordsee)
#   413 km - [[Saale]] (Elbe)
#   382 km - [[Spree]] (Havel)
#   371 km - [[Ems]] (Nordsee)
#   367 km m [[Neckar]] (Rhein)
#   325 km - [[Havel]] (Elbe)
#   295 km - [[Isar]] (Donau)
#   292 km - [[Werra]] (<small>rechter Quellfluss der</small> Weser) (* 
#   291 km - [[Eger (Fluss)|Eger]] (Elbe) 
#   285 km m [[Lech]] (Donau)
#   257 km - [[Weiße Elster]] (Saale)
#   256 km - [[Lausitzer Neiße]] (Oder) 
#   255 km - [[Lippe (Fluss)|Lippe]] (Rhein)
#   246 km - [[Saar]] (Mosel)
#   242 km - [[Lahn (Fluss)|Lahn]] (Rhein)
#   241 km - [[Leine (Fluss)|Leine]] (Aller)
#   225 km - [[Salzach]] (Inn)
#   220 km - [[Altmühl]] (Donau)
#   220 km - [[Elde]] (Elbe)
#   218 km - [[Fulda (Fluss)|Fulda]] (<small>linker Quellfluss der</small> Weser)
#   217 km - [[Ruhr (Fluss)|Ruhr]] (Rhein)
#   211 km - [[Aller]] (Weser)
#   198 km - [[Hunte]] (Weser)
#   196 km - [[Jagst]] (Neckar)
#   193 km - [[Hase (Fluss)|Hase]] (Else/Ems)
#   192 km - [[Unstrut]] (Saale)
#   188 km - [[Eider]] (Nordsee)
#   188 km - [[Schwarze Elster]] (Elbe)
#   185 km - [[Amper|Ammer-Amper]] (Isar)
#   182 km m [[Kocher (Fluss)|Kocher]] (Neckar)
#   177 km - [[Eder]] (Fulda)
#   173 km - [[Sauer (Fluss)|Sauer]] (Mosel)
#   170 km - [[Rur]] (Maas)
#   167 km - [[Vechte]] (Zwarte Water) 
#   166 km - [[Zwickauer Mulde]] (<small>linker Quellfluss der Mulde</small>) 
#   165 km - [[Naab]] - <small>mit Quellfluss Waldnaab</small> (Donau)
#   165 km m [[Regen (Fluss)|Regen]] (Donau)
#   156 km - [[Peene]] (Ostsee)
#   153 km - [[Oste]] (Nordsee)
#   153 km - [[Sieg (Fluss)|Sieg]] (Rhein)
#   151 km - [[Wertach (Fluss)|Wertach]] (Lech)
#   151 km - [[Warnow (Fluss)|Warnow]] (Ostsee) 
#   147 km - [[Iller]] (Donau)
#   142 km - [[Fränkische Saale]] (Main)
#   142 km - [[Kyll]] (Mosel)
#   140 km - [[Bode]] (Saale)
#   140 km - [[Wied (Fluss)|Wied]] (Rhein)
#   134 km - [[Paar (Fluss)|Paar]] (Donau)
#   132 km - [[Wörnitz (Fluss)|Wörnitz]] (Donau)
#   129 km - [[Ilm (Thüringen)|Ilm]] (Saale) 
#   128 km - [[Lenne (Fluss)|Lenne]] (Ruhr)
#   128 km - [[Zschopau (Fluss)|Zschopau]] (Freiberger Mulde)
#   125 km - [[Rhin]] (Havel)
#   124 km - [[Freiberger Mulde]] (<small>rechter Quellfluss der</small> Mulde)
#   124 km - [[Mulde (Fluss)|Mulde]] (Elbe)
#   124 km - [[Trave]] (Ostsee) 
#   122 km m [[Tauber]] (Main)
#   120 km - [[Vils (Donau)|Vils]] (Donau)
#   116 km - [[Nahe (Fluss)|Nahe]] (Rhein)
#   116 km - [[Niers]] (Maas)
#   115 km - [[Pegnitz (Fluss)|Pegnitz]] (<small>rechter Quellfluss der</small> Regnitz)
#   114 km - [[Loisach]] (Isar)
#   114 km - [[Wupper]] (Rhein)
#   112 km - [[Enz]] (Neckar)
#   110 km - [[Friedberger Ach]] (Donau)
#   110 km - [[Berkel]] (IJssel) 
#   110 km - [[Ohre]] (Elbe)
#   109 km - [[Rott (Fluss)|Rott]] (Inn)
#   108 km - [[Wümme]] (Lesum) 
#   107 km - [[Ilmenau (Fluss)|Ilmenau]] (Elbe) 
#   105 km - [[Diemel]] (Weser)
#   105 km - [[Oker]] (Aller)
#   103 km - [[Erft]] (Rhein)
#   103 km - [[Mies (Fluss)|Mies]] (Berounka)
#   103 km - [[Saalach]] (Salzach)
#   103 km - [[Uecker]] - <small>(in Brandenburg: ''Ucker''</small>) - (Ostsee)
#   102 km - [[Nied (Fluss)|Nied]] (Saar)
#    99 km - [[Blies]] (Saar)
#    98 km - [[Fuhse]] (Aller)
#    98 km - [[Nidda (Fluss)|Nidda]] (Main)
#    98 km - [[Werre]] (Weser)
#    97 km - [[Schwalm (Fluss in Hessen)|Schwalm]] (Eder)
#    97 km - [[Milde (Fluss)|Milde]]-[[Biese]]-[[Aland (Fluss)|Aland]] (Elbe)
#    95 km - [[Dahme (Fluss)|Dahme]] (Spree)
#    95 km - [[Innerste]] (Leine)
#    95 km - [[Kinzig (Schwarzwald)|Kinzig]] <small>(Baden-Württemberg)</small> (Rhein)
#    94 km - [[Dosse]] (Havel)
#    93 km - [[Dinkel (Fluss)|Dinkel]] (Vechte)
#    93 km - [[Wipper (Hainleite)|Wipper]] <small>(Thüringen)</small> (Unstrut) 
#    92 km - [[Nagold (Fluss)|Nagold]] (Enz)
#    90 km - [[Große Röder]] (Schwarze Elster) 
#    90 km - [[Pleiße]] (Weiße Elster)
#    87 km - [[Stör (Fluss)|Stör]] (Elbe)
#    87 km - [[Vils (Naab)|Vils]] (Naab)
#    86 km - [[Ahr]] (Rhein) 
#    86 km - [[Wutach]] (Rhein)
#    85 km - [[Gera (Fluss)|Gera]] (Unstrut)
#    85 km - [[Große Laber]] (Donau)
#    85 km - [[Wipper (Harz)|Wipper]] <small>(Sachsen-Anhalt)</small> (Saale)
#    84 km - [[Emscher]] (Rhein)
#    84 km - [[Stepenitz (Elbe)|Stepenitz]] <small>(Brandenburg)</small> (Elbe)
#    84 km - [[Prüm (Fluss)|Prüm]] (Sauer)
#    83 km - [[Wesenitz]] (Elbe)
#    82 km - [[Kinzig (Hessen)|Kinzig]] <small>(Hessen)</small> (Main)
#    82 km - [[Ilm (Bayern)|Ilm]] <small>(Bayern)</small> (Abens) 
#    80 km - [[Itz]] (Mainz)
#    80 km - [[Rems]] (Neckar)
#    79 km - [[Tiroler Achen]] (Alz)
#    78 km - [[Flöha (Fluss)|Flöha]] (Zschopau)
#    78 km - [[Our]] (Sauer)
#    78 km - [[Wiesent (Fluss)|Wiesent]] (Regnitz)
#    76 km - [[Abens]] (Donau)
#    76 km - [[Isen (Fluss)|Isen]] (Inn)
#    76 km - [[Schmutter]] (Donau)
#    76 km - [[Schwarze Laber]] (Donau)
#    75 km - [[Aisch]] (Regnitz)
#    75 km - [[Mindel]] (Donau)
#    74 km - [[Trebel (Fluss)|Trebel]] (Peene)
#    73 km - [[Böhme (Fluss)|Böhme]] (Aller)
#    73 km - [[Jeetze (Fluss)|Jeetze]]-[[Jeetzel]] (Elbe)
#    73 km - [[Treene]] (Eider)
#    72 km - [[Argen]]-[[Untere Argen]] <small>mit Quellfluss Weitnauer Bach</small> (Rhein)
#    72 km - [[Recknitz]] (Saaler Bodden / Ostsee)
#    72 km - [[Sude]] (Elbe)
#    71 km - [[Jäglitz|Alte und Neue Jäglitz]] (Havel und Dosse)
#    70 km - [[Issel|Issel mit Oude Ijssel]]
#    70 km - [[Murg (Nordschwarzwald)]] (Rhein)
#    70 km - [[Sauer (Elsass)|Sauer (Pfalz/Elsass)]] (Rhein)
#    68 km - [[Dill (Fluss)|Dill]] (Lahn)
#    68 km - [[Glan (Pfalz)|Glan]] <small>(Rheinland-Pfalz)</small> (Nahe)
#    68 km - [[Randow]] (Uecker) 
#    68 km - [[Tollense]] (Peene)
#    68 km - [[Wetter (Fluss)|Wetter]] (Nidda)
#    67 km - [[Werse]] (Ems)
#    67 km - [[Chemnitz (Fluss)|Chemnitz]] (Zwickauer Mulde)
#    67 km - [[Selke]] (Bode)
#    66 km - [[Löcknitz (Fluss)|Löcknitz]] (Elbe)
#    65 km - [[Bille]] (Elbe)
#    65 km - [[Fränkische Rezat]] (Rednitz)
#    65 km - [[Helme (Fluss)|Helme]] (Unstrut)
#    65 km - [[Ilz (Fluss)|Ilz]] (Donau) 
#    65 km - [[Nuthe]] <small>(Brandenburg)</small> (Havel)
#    68 km - [[Agger]] (Sieg)
#    64 km - [[Haune]] (Fulda)
#    64 km - [[Nister (Fluss)|Nister]] (Sieg)
#    63 km - [[Alz]] (Inn)
#    63 km - [[Fils (Fluss)|Fils]] (Neckar)
#    63 km - [[Nidder]] (Nidda)
#    63 km - [[Salm (Fluss)|Salm]] (Mosel)
#    63 km - [[Weida (Fluss)|Weida]] (Weiße Elster)
#    62 km - [[Schussen]] (Rhein)
#    62 km - [[Schwentine]] (Kieler Förde / Ostsee) 
#    61 km - [[Selz (Fluss)|Selz]] (Rhein)
#    61 km - [[Weißeritz|Weißeritz mit Wilder Weißeritz]] (Elbe)
#    60 km - [[Nebel (Fluss)|Nebel]] (Warnow)
#    60 km - [[Pfinz]] (Rhein)
#    60 km - [[Pulsnitz (Fluss)|Pulsnitz]] (Schwarzen Elster)
#    60 km - [[Schwarzach (Naab)|Schwarzach]] (Naab) 
#    60 km - [[Schwarzach (Rednitz)|Schwarzach]] (Rednitz)
#    60 km - [[Sempt]] (Isar)
#    60 km - [[Speyerbach]] (Rhein) 
#    60 km - [[Weschnitz]] (Rhein) 
#    60 km - [[Zusam]] (Donau)
#    59 km - [[Nims]] (Prüm)
#    59 km - [[Ohm (Fluss)|Ohm]] (Lahn)
#    59 km - [[Rench]] (Rhein)
#    59 km - [[Roter Main]] (<small>linker Quellfluss des</small> Mains)
#    58 km - [[Löbauer Wasser]]
#    58 km - [[Luhe (Ilmenau)|Luhe]] (Ilmenau)
#    58 km - [[Mangfall]] (Inn)
#    58 km - [[Regnitz]] (Main) 
#    57 km - [[Alsenz (Fluss)|Alsenz]] (Nahe)
#    57 km - [[Helbe]] (Unstrut)
#    57 km - [[Kammel]] (Mindel)
#    57 km - [[Plane (Fluss)|Plane]] (Havel)
#    57 km - [[Schunter]] (Oker)
#    57 km - [[Steinach (zum Main)|Steinach]] (Rodach)
#    57 km - [[Weida (Fluss)|Weida]] (Weiße Elster)
#    56 km - [[Hörsel]] mit "Kleine Leina" (Werra)
#    56 km - [[Lauchert]] (Donau)
#    56 km - [[Stecknitz]] (Trave)
#    56 km - [[Ulster (Fluss)|Ulster]] (Werra)
#    55 km - [[Brenz (Fluss)|Brenz]] (Donau) 
#    55 km - [[Günz]] (Donau) 
#    55 km - [[Lauter (Rhein)|Lauter]] (Rhein)
#    55 km - [[Lieser (Fluss)|Lieser]] (Mosel)
#    55 km - [[Örtze]] (Aller)
#    55 km - [[Wiese (Fluss)|Wiese]] (Rhein)
#    55 km - [[Wisenta]] (Saale)
#    54 km - [[Eyach (Neckar)|Eyach]] (Neckar)
#    54 km - [[Rot (Donau)|Rot]] (Donau)
#    54 km - [[Stever]] (Lippe)
#    53 km - [[Schwarza (Saale)|Schwarza]] (Saale)
#    53 km - [[Alf (Fluss)|Alf]] (Mosel)
#    53 km - [[Alster]] (Elbe)
#    53 km - [[Wurm (Fluss)|Wurm]] (Rur) 
#    52 km - [[Nesse (Fluss)|Nesse]] (Hörsel)
#    52 km - [[Queich]] (Rhein)
#    52 km - [[Rodach (zum Main)|Rodach]] (Main) 
#    52 km - [[Stepenitz (Trave)|Stepenitz]] <small>(Mecklenburg)</small> (Trave)
#    51 km - [[Bocholter Aa]] (Oude Ijssel) 
#    51 km - [[Bühler (Fluss)|Bühler]] (Kocher)
#    51 km - [[Chamb]] (Regen)
#    51 km - [[Murr (Fluss)|Murr]] (Neckar)
#    51 km - [[Prims]] (Saar)
#    50 km - [[Ise (Fluss)|Ise]] (Aller)
#    50 km - [[Möhne]] (Ruhr) 
#    50 km - [[Mümling]] (Main)
#    50 km m [[Schwarzbach (Pfalz)]] (Blies)
#    50 km m [[Simmerbach]] (Nahe)
#    50 km - [[Sinn (Fluss)|Sinn]] (Fränkische Saale)
#    50 km - [[Urft]] (Rur) 
#    50 km - [[Volme]] (Ruhr)
#    50 km - [[Weil (Fluss)|Weil]] (Lahn)
#    50 km - [[Würm (Gäu)]] (Nagold)
