#!/usr/bin/perl

#
#  Copyright 2006 Dr. Georg Fischer <punctum at punctum dot kom>
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# all German towns
# Die '''Liste der Städte in Deutschland''' enthält eine 
# vollständige Auflistung aller 2074 [[Stadt|Städte]] in [[Deutschland]] 
# in alphabetischer Reihenfolge (Stand: 29. März 2006).
# from http://de.wikipedia.org/wiki/Liste_der_St%C3%A4dte_in_Deutschland
# take single words only
# @(#) $Id: de_town.pl 36 2008-09-08 06:05:06Z gfis $
# 2006-08-13, Georg Fischer

use strict;
    binmode(STDOUT, ":utf8");

    while (<DATA>) {
        next if ! m/\:\[\[/;
        m/\[\[([^\(\|\]]+)/;
        my $city = $1;
        $city =~ s/ [abcdefghijklmnopqrstuvwäöü].*//; # remove "am ...", "im ..." etc.
        $city =~ s/ $//;
        $city =~ s/^Bad //;
        $city =~ s/^St\. //;
        $city =~ s/^Sankt //;
        foreach my $loc (split (/[\- ]/, $city)) {
            print "$loc =NmGeogCity.De\n";
        }
    }
__DATA__
Die '''Liste der Städte in Deutschland''' enthält eine vollständige Auflistung aller 2074 [[Stadt|Städte]] in [[Deutschland]] in alphabetischer Reihenfolge (Stand: 29. März 2006).
:[[Aach (Hegau)|Aach]] (Baden-Württemberg)
:[[Aachen]] (Nordrhein-Westfalen)
:[[Aalen]] (Baden-Württemberg)
:[[Abenberg]] (Bayern)
:[[Abensberg]] (Bayern)
:[[Achern]] (Baden-Württemberg)
:[[Achim (Weser)|Achim]] (Niedersachsen)
:[[Adelsheim]] (Baden-Württemberg)
:[[Adenau]] (Rheinland-Pfalz)
:[[Adorf (Vogtland)|Adorf]] (Sachsen)
:[[Ahaus]] (Nordrhein-Westfalen)
:[[Ahlen]] (Nordrhein-Westfalen)
:[[Ahrensburg]] (Schleswig-Holstein)
:[[Aichach]] (Bayern)
:[[Aichtal]] (Baden-Württemberg)
:[[Aken (Elbe)]] (Sachsen-Anhalt)
:[[Albstadt]] (Baden-Württemberg)
:[[Alfeld (Leine)]] (Niedersachsen)
:[[Allendorf (Lumda)]] (Hessen)
:[[Allstedt]] (Sachsen-Anhalt)
:[[Alpirsbach]] (Baden-Württemberg)
:[[Alsfeld]] (Hessen)
:[[Alsdorf (Rheinland)|Alsdorf]] (Nordrhein-Westfalen)
| width="400" valign="top" |
:[[Alsleben (Saale)]] (Sachsen-Anhalt)
:[[Altdorf bei Nürnberg]] (Bayern)
:[[Altena]] (Nordrhein-Westfalen)
:[[Altenau, Bergstadt]] (Niedersachsen)
:[[Altenberg (Erzgebirge)|Altenberg]] (Sachsen)
:[[Altenburg]] (Thüringen)
:[[Altenkirchen (Westerwald)]] (Rheinl.-Pfalz)
:[[Altensteig]] (Baden-Württemberg)
:[[Altentreptow]] (Mecklenburg-Vorpommern)
:[[Altlandsberg]] (Brandenburg)
:[[Altötting]] (Bayern)
:[[Alzenau in Unterfranken]] (Bayern)
:[[Alzey]] (Rheinland-Pfalz)
:[[Amberg]] (Bayern)
:[[Amöneburg |Amöneburg]] (Hessen)
:[[Amorbach]] (Bayern)
:[[Andernach]] (Rheinland-Pfalz)
:[[Angermünde]] (Brandenburg)
:[[Anklam]] (Mecklenburg-Vorpommern)
:[[Annaberg-Buchholz]] (Sachsen)
:[[Annaburg]] (Sachsen-Anhalt)
:[[Annweiler am Trifels]] (Rheinland-Pfalz)
:[[Ansbach]] (Bayern)
| width="400" valign="top" |
:[[Apolda]] (Thüringen)
:[[Arendsee (Altmark)]] (Sachsen-Anhalt)
:[[Arneburg]] (Sachsen-Anhalt)
:[[Arnis (Stadt)|Arnis]] (Schleswig-Holstein)
:[[Arnsberg]] (Nordrhein-Westfalen)
:[[Arnstadt]] (Thüringen)
:[[Arnstein]] (Bayern)
:[[Artern/Unstrut]] (Thüringen)
:[[Arzberg (Oberfranken)|Arzberg]] (Bayern)
:[[Aschaffenburg]] (Bayern)
:[[Aschersleben]] (Sachsen-Anhalt)
:[[Asperg]] (Baden-Württemberg)
:[[Aßlar]] (Hessen)
:[[Attendorn]] (Nordrhein-Westfalen)
:[[Aub]] (Bayern)
:[[Aue (Sachsen)|Aue]] (Sachsen)
:[[Auerbach in der Oberpfalz]] (Bayern)
:[[Auerbach/Vogtl.]] (Sachsen)
:[[Augsburg]] (Bayern)
:[[Augustusburg]] (Sachsen)
:[[Aulendorf]] (Baden-Württemberg)
:[[Auma]] (Thüringen)
:[[Aurich]] (Niedersachsen)
|}
{{TOC}}

===B===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Babenhausen (Hessen)|Babenhausen]] (Hessen)
:[[Bacharach]] (Rheinland-Pfalz)
:[[Backnang]] (Baden-Württemberg)
:[[Bad Aibling]] (Bayern)
:[[Bad Arolsen]] (Hessen)
:[[Bad Bentheim]] (Niedersachsen)
:[[Bad Bergzabern]] (Rheinland-Pfalz)
:[[Bad Berka]] (Thüringen)
:[[Bad Berleburg]] (Nordrhein-Westfalen)
:[[Bad Berneck im Fichtelgebirge]] (Bayern)
:[[Bad Bevensen]] (Niedersachsen)
:[[Bad Bibra]] (Sachsen-Anhalt)
:[[Bad Blankenburg]] (Thüringen)
:[[Bad Bramstedt]] (Schleswig-Holstein)
:[[Bad Breisig]] (Rheinland-Pfalz)
:[[Bad Brückenau]] (Bayern)
:[[Bad Buchau]] (Baden-Württemberg)
:[[Bad Camberg]] (Hessen)
:[[Bad Colberg-Heldburg]] (Thüringen)
:[[Bad Doberan]] (Mecklenburg-Vorp.)
:[[Bad Driburg]] (Nordrhein-Westfalen)
:[[Bad Düben]] (Sachsen)
:[[Bad Dürkheim]] (Rheinland-Pfalz)
:[[Bad Dürrenberg]] (Sachsen-Anhalt)
:[[Bad Dürrheim]] (Baden-Württemberg)
:[[Bad Elster]] (Sachsen)
:[[Bad Ems]] (Rheinland-Pfalz)
:[[Baden-Baden]] (Baden-Württemberg)
:[[Bad Fallingbostel]] (Niedersachsen)
:[[Bad Frankenhausen/Kyffhäuser]] (Thür.)
:[[Bad Freienwalde (Oder)]] (Brandenburg)
:[[Bad Friedrichshall]] (Baden-Württ.)
:[[Bad Gandersheim]] (Niedersachsen)
:[[Bad Gottleuba-Berggießhübel]] (Sachs.)
:[[Bad Griesbach im Rottal]] (Bayern)
:[[Bad Grund (Harz)]] (Niedersachsen)
:[[Bad Harzburg]] (Niedersachsen)
:[[Bad Herrenalb]] (Baden-Württemberg)
:[[Bad Hersfeld]] (Hessen)
:[[Bad Homburg vor der Höhe]] (Hessen)
:[[Bad Honnef]] (Nordrhein-Westfalen)
:[[Bad Hönningen]] (Rheinland-Pfalz)
:[[Bad Iburg]] (Niedersachsen)
:[[Bad Karlshafen]] (Hessen)
:[[Bad Kissingen]] (Bayern)
:[[Bad König]] (Hessen)
:[[Bad Königshofen im Grabfeld]] (Bayern)
:[[Bad Kösen]] (Sachsen-Anhalt)
:[[Bad Köstritz]] (Thüringen)
:[[Bad Kötzting]] (Bayern)
:[[Bad Kreuznach]] (Rheinland-Pfalz)
:[[Bad Krozingen]] (Baden-Württemberg)
:[[Bad Laasphe]] (Nordrhein-Westfalen)
:[[Bad Langensalza]] (Thüringen)
:[[Bad Lauchstädt]] (Sachsen-Anhalt)
:[[Bad Lausick]] (Sachsen)
:[[Bad Lauterberg im Harz]] (Nieders.)
:[[Bad Liebenstein]] (Thüringen)
:[[Bad Liebenwerda]] (Brandenburg)
:[[Bad Liebenzell]] (Baden-Württemberg)
:[[Bad Lippspringe]] (Nordrhein-Westfalen)
:[[Bad Lobenstein]] (Thüringen)
:[[Bad Marienberg]] (Rheinl.-Pf.)
:[[Bad Mergentheim]] (Baden-Württ.)
:[[Bad Münder am Deister]] (Nieders.)
:[[Bad Münster am Stein-Ebernburg]] (R.P.)
:[[Bad Münstereifel]] (Nordrhein-Westfalen)
:[[Bad Muskau]] (Sachsen)
:[[Bad Nauheim]] (Hessen)
:[[Bad Nenndorf]] (Niedersachsen)
:[[Bad Neuenahr-Ahrweiler]] (Rheinl.-Pfalz)
:[[Bad Neustadt an der Saale]] (Bayern)
:[[Bad Oeynhausen]] (Nordrhein-Westfalen)
:[[Bad Oldesloe]] (Schleswig-Holstein)
:[[Bad Orb]] (Hessen)
:[[Bad Pyrmont]] (Niedersachsen)
:[[Bad Rappenau]] (Baden-Württemberg)
:[[Bad Reichenhall]] (Bayern)
:[[Bad Rodach]] (Bayern)
:[[Bad Sachsa]] (Niedersachsen)
:[[Bad Säckingen]] (Baden-Württ.)
:[[Bad Salzdetfurth]] (Niedersachsen)
:[[Bad Salzuflen]] (Nordrhein-Westf.)
:[[Bad Salzungen]] (Thüringen)
:[[Bad Saulgau]] (Baden-Württemberg)
:[[Bad Schandau]] (Sachsen)
:[[Bad Schmiedeberg]] (Sachsen-Anh.)
:[[Bad Schussenried]] (Baden-Württ.)
:[[Bad Schwalbach]] (Hessen)
:[[Bad Schwartau]] (Schleswig-Holst.)
:[[Bad Segeberg]] (Schleswig-Holstein)
| width="400" valign="top" |
:[[Bad Sobernheim]] (Rheinland-Pfalz)
:[[Bad Soden am Taunus]] (Hessen)
:[[Bad Soden-Salmünster]] (Hessen)
:[[Bad Sooden-Allendorf]] (Hessen)
:[[Bad Staffelstein]] (Bayern)
:[[Bad Sulza]] (Thüringen)
:[[Bad Sülze]] (Mecklenburg-Vorp.)
:[[Bad Teinach-Zavelstein]] (Baden-W.)
:[[Bad Tennstedt]] (Thüringen)
:[[Bad Tölz]] (Bayern)
:[[Bad Urach]] (Baden-Württemberg)
:[[Bad Vilbel]] (Hessen)
:[[Bad Waldsee]] (Baden-Württemberg)
:[[Bad Wildbad]] (Baden-Württemberg)
:[[Bad Wildungen]] (Hessen)
:[[Bad Wilsnack]] (Brandenburg)
:[[Bad Wimpfen]] (Baden-Württemberg)
:[[Bad Windsheim]] (Bayern)
:[[Bad Wörishofen]] (Bayern)
:[[Bad Wünnenberg]] (Nordrh.-Westf.)
:[[Bad Wurzach]] (Baden-Württemberg)
:[[Baesweiler]] (Nordrhein-Westfalen)
:[[Baiersdorf]] (Bayern)
:[[Balingen]] (Baden-Württemberg)
:[[Ballenstedt]] (Sachsen-Anhalt)
:[[Balve]] (Nordrhein-Westfalen)
:[[Bamberg]] (Bayern)
:[[Barby (Elbe)]] (Sachsen-Anhalt)
:[[Bargteheide]] (Schleswig-Holstein)
:[[Barmstedt]] (Schleswig-Holstein)
:[[Bärnau]] (Bayern)
:[[Barntrup]] (Nordrhein-Westfalen)
:[[Barsinghausen]] (Niedersachsen)
:[[Barth]] (Mecklenburg-Vorpommern)
:[[Baruth/Mark]] (Brandenburg)
:[[Bassum]] (Niedersachsen)
:[[Battenberg (Eder)]] (Hessen)
:[[Baumholder]] (Rheinland-Pfalz)
:[[Baunach]] (Bayern)
:[[Baunatal]] (Hessen)
:[[Bautzen]] (Sachsen)
:[[Bayreuth]] (Bayern)
:[[Bebra]] (Hessen)
:[[Beckum]] (Nordrhein-Westfalen)
:[[Bedburg]] (Nordrhein-Westfalen)
:[[Beelitz]] (Brandenburg)
:[[Beerfelden]] (Hessen)
:[[Beeskow]] (Brandenburg)
:[[Beilngries]] (Bayern)
:[[Beilstein (Württemberg)|Beilstein]] (Baden-Württemberg)
:[[Belgern]] (Sachsen)
:[[Belzig]] (Brandenburg)
:[[Bendorf]] (Rheinland-Pfalz)
:[[Benneckenstein (Harz)]] (Sachsen-Anhalt)
:[[Bensheim]] (Hessen)
:[[Berching]] (Bayern)
:[[Berga/Elster]] (Thüringen)
:[[Bergen (Landkreis Celle)|Bergen]] (Niedersachsen)
:[[Bergen auf Rügen]] (Mecklenburg-Vorp.)
:[[Bergheim]] (Nordrhein-Wedtfalen)
:[[Bergisch Gladbach]] (Nordrhein-Westf.)
:[[Bergkamen]] (Nordrhein-Westfalen)
:[[Bergneustadt]] (Nordrhein-Westfalen)
:[[Berka/Werra]] (Thüringen)
:[[Berlin]] (Land Berlin / Bundeshauptstadt)
:[[Bernau bei Berlin]] (Brandenburg)
:[[Bernburg (Saale)]] (Sachsen-Anhalt)
:[[Bernkastel-Kues]] (Rheinland-Pfalz)
:[[Bernsdorf (Oberlausitz)|Bernsdorf]] (Sachsen)
:[[Bernstadt a. d. Eigen]] (Sachsen)
:[[Bersenbrück]] (Niedersachsen)
:[[Besigheim]] (Baden-Württemberg)
:[[Betzdorf (Sieg)|Betzdorf]] (Rheinland-Pfalz)
:[[Betzenstein]] (Bayern)
:[[Beverungen]] (Nordrhein-Westfalen)
:[[Bexbach]] (Saarland)
:[[Biberach an der Riß]] (Baden-Württ.)
:[[Biedenkopf]] (Hessen)
:[[Bielefeld]] (Nordrhein-Westfalen)
:[[Biesenthal]] (Brandenburg)
:[[Bietigheim-Bissingen]] (Baden-Württ.)
:[[Billerbeck]] (Nordrhein-Westfalen)
:[[Bingen am Rhein]] (Rheinland-Pfalz)
:[[Birkenfeld (Nahe)|Birkenfeld]] (Rheinland-Pfalz)
:[[Bischofsheim an der Rhön]] (Bayern)
:[[Bischofswerda]] (Sachsen)
:[[Bismark (Altmark)]] (Sachsen-Anhalt)
:[[Bitburg]] (Rheinland-Pfalz)
:[[Bitterfeld]] (Sachsen-Anhalt)
:[[Blankenburg (Harz)]] (Sachsen-Anhalt)
:[[Blankenhain]] (Thüringen)
| width="400" valign="top" |
:[[Blaubeuren]] (Baden-Württemberg)
:[[Bleckede]] (Niedersachsen)
:[[Bleicherode]] (Thüringen)
:[[Blieskastel]] (Saarland)
:[[Blomberg (Lippe)|Blomberg]] (Nordrhein-Westfalen)
:[[Blumberg (Schwarzwald)|Blumberg]] (Baden-Württemberg)
:[[Bobingen]] (Bayern)
:[[Böblingen]] (Baden-Württemberg)
:[[Bocholt]] (Nordrhein-Westfalen)
:[[Bochum]] (Nordrhein-Westfalen)
:[[Bockenem]] (Niedersachsen)
:[[Bodenwerder]] (Niedersachsen)
:[[Bogen (Stadt)|Bogen]] (Bayern)
:[[Böhlen (Sachsen)|Böhlen]] (Sachsen)
:[[Boizenburg/Elbe]] (Mecklenburg-Vorp.)
:[[Bonn]] (Nordrhein-Westfalen)
:[[Bonndorf im Schwarzwald]] (Baden-W.)
:[[Bönnigheim]] (Baden-Württemberg)
:[[Bopfingen]] (Baden-Württemberg)
:[[Boppard]] (Rheinland-Pfalz)
:[[Borgentreich]] (Nordrhein-Westfalen)
:[[Borgholzhausen]] (Nordrhein-Westfalen)
:[[Borken]] (Nordrhein-Westfalen)
:[[Borken (Hessen)]] (Hessen)
:[[Borkum]] (Niedersachsen)
:[[Borna]] (Sachsen)
:[[Bornheim (Rheinland)|Bornheim]] (Nordrhein-Westfalen)
:[[Bottrop]] (Nordrhein-Westfalen)
:[[Boxberg (Baden)|Boxberg]] (Baden-Württemberg)
:[[Brackenheim]] (Baden-Württemberg)
:[[Brake (Unterweser)]] (Niedersachsen)
:[[Brakel]] (Nordrhein-Westfalen)
:[[Bramsche]] (Niedersachsen)
:[[Brandenburg an der Havel]] (Brandenb.)
:[[Brand-Erbisdorf]] (Sachsen)
:[[Brandis (Sachsen)|Brandis]] (Sachsen)
:[[Braubach]] (Rheinland-Pfalz)
:[[Braunfels]] (Hessen)
:[[Braunlage]] (Niedersachsen)
:[[Bräunlingen]] (Baden-Württemberg)
:[[Braunsbedra]] (Sachsen-Anhalt)
:[[Braunschweig]] (Niedersachsen)
:[[Breckerfeld]] (Nordrhein-Westfalen)
:[[Bredstedt]] (Schleswig-Holstein)
:[[Brehna]] (Sachsen-Anhalt)
:[[Breisach am Rhein]] (Baden-Württemb.)
:[[Bremen]] (Land Bremen / Freie Hansestadt)
:[[Bremerhaven]] (Land Bremen)
:[[Bremervörde]] (Niedersachsen)
:[[Bretten]] (Baden-Württemberg)
:[[Breuberg]] (Hessen)
:[[Brilon]] (Nordrhein-Westfalen)
:[[Brotterode]] (Thüringen)
:[[Bruchköbel]] (Hessen)
:[[Bruchsal]] (Baden-Württemberg)
:[[Brück]] (Brandenburg)
:[[Brüel]] (Mecklenburg-Vorpommern)
:[[Brühl (Rheinland)|Brühl]] (Nordrhein-Westfalen)
:[[Brunsbüttel]] (Schleswig-Holstein)
:[[Brüssow]] (Brandenburg)
:[[Buchen (Odenwald)]] (Baden-Württ.)
:[[Buchholz in der Nordheide]] (Nieders.)
:[[Buchloe]] (Bayern)
:[[Bückeburg]] (Niedersachsen)
:[[Buckow (Märkische Schweiz)]] (Brandenburg)
:[[Büdelsdorf]] (Schleswig-Holstein)
:[[Büdingen (Hessen)|Büdingen]] (Hessen)
:[[Bühl (Landkreis Rastatt)|Bühl]] (Baden-Württemberg)
:[[Bünde]] (Nordrhein-Westfalen)
:[[Büren (Westfalen)|Büren]] (Nordrhein-Westfalen)
:[[Burg (bei Magdeburg)|Burg]] (Sachsen-Anhalt)
:[[Burgau (Schwaben)|Burgau]] (Bayern)
:[[Burgbernheim]] (Bayern)
:[[Burgdorf (Hannover)|Burgdorf]] (Niedersachsen)
:[[Bürgel (Thüringen)|Bürgel]] (Thüringen)
:[[Burghausen]] (Bayern)
:[[Burgkunstadt]] (Bayern)
:[[Burglengenfeld]] (Bayern)
:[[Burgstädt]] (Sachsen)
:[[Burg Stargard]] (Mecklenburg-Vorp.)
:[[Burgwedel]] (Niedersachsen)
:[[Burladingen]] (Baden-Württemberg)
:[[Burscheid]] (Nordrhein-Westfalen)
:[[Bürstadt]] (Hessen)
:[[Buttelstedt]] (Thüringen)
:[[Buttstädt]] (Thüringen)
:[[Butzbach]] (Hessen)
:[[Bützow]] (Mecklenburg-Vorpommern)
:[[Buxtehude]] (Niedersachsen)
|}
{{TOC}}

===C===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Calau]] (Brandenburg)
:[[Calbe (Saale)]] (Sachsen-Anhalt)
:[[Calw]] (Baden-Württemberg)
:[[Camburg]] (Thüringen)
:[[Castrop-Rauxel]] (Nordrhein-Westfalen)
:[[Celle]] (Niedersachsen)
:[[Cham (Oberpfalz)|Cham]] (Bayern)
:[[Chemnitz]] (Sachsen)
:[[Clausthal-Zellerfeld]] (Nieders.)
| width="400" valign="top" |
:[[Clingen]] (Thüringen)
:[[Cloppenburg]] (Niedersachsen)
:[[Coburg]] (Bayern)
:[[Cochem]] (Rheinland-Pfalz)
:[[Coesfeld]] (Nordrhein-Westfalen)
:[[Colditz]] (Sachsen)
:[[Coswig (Sachsen)|Coswig]] (Sachsen)
:[[Coswig (Anhalt)]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Cottbus]] (Brandenburg)
:[[Crailsheim]] (Baden-Württemberg)
:[[Creglingen]] (Baden-Württemberg)
:[[Creußen]] (Bayern)
:[[Creuzburg]] (Thüringen)
:[[Crimmitschau]] (Sachsen)
:[[Crivitz]] (Mecklenburg-Vorpommern)
:[[Cuxhaven]] (Niedersachsen)
|}
{{TOC}}
===D===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Dachau]] (Bayern)
:[[Dahlen (Sachsen)|Dahlen]] (Sachsen)
:[[Dahme/Mark]] (Brandenburg)
:[[Dahn]] (Rheinland-Pfalz)
:[[Damme (Landkreis Vechta)|Damme]] (Niedersachsen)
:[[Dannenberg (Elbe)]] (Niedersachsen)
:[[Dargun]] (Mecklenburg-Vorpommern)
:[[Darmstadt]] (Hessen)
:[[Dassel]] (Niedersachsen)
:[[Dassow]] (Mecklenburg-Vorpommern)
:[[Datteln]] (Nordrhein-Westfalen)
:[[Daun]] (Rheinland-Pfalz)
:[[Deggendorf]] (Bayern)
:[[Deidesheim]] (Rheinland-Pfalz)
:[[Delbrück]] (Nordrhein-Westfalen)
:[[Delitzsch]] (Sachsen)
:[[Delmenhorst]] (Niedersachsen)
:[[Demmin]] (Mecklenburg-Vorpommern)
:[[Derenburg]] (Sachsen-Anhalt)
:[[Dessau]] (Sachsen-Anhalt)
:[[Detmold]] (Nordrhein-Westfalen)
:[[Dettelbach]] (Bayern)
:[[Dieburg]] (Hessen)
| width="400" valign="top" |
:[[Diemelstadt]] (Hessen)
:[[Diepholz]] (Niedersachsen)
:[[Dierdorf]] (Rheinland-Pfalz)
:[[Dietenheim]] (Baden-Württemberg)
:[[Dietfurt an der Altmühl]] (Bayern)
:[[Dietzenbach]] (Hessen)
:[[Diez]] (Rheinland-Pfalz)
:[[Dillenburg]] (Hessen)
:[[Dillingen an der Donau]] (Bayern)
:[[Dillingen/Saar]] (Saarland)
:[[Dingelstädt]] (Thüringen)
:[[Dingolfing]] (Bayern)
:[[Dinkelsbühl]] (Bayern)
:[[Dinklage]] (Niedersachsen)
:[[Dinslaken]] (Nordrhein-Westfalen)
:[[Dippoldiswalde]] (Sachsen)
:[[Dissen am Teutoburger Wald]] (Nieders.)
:[[Ditzingen]] (Baden-Württemberg)
:[[Döbeln]] (Sachsen)
:[[Doberlug-Kirchhain]] (Brandenburg)
:[[Döbern]] (Brandenburg)
:[[Dohna]] (Sachsen)
:[[Dömitz]] (Mecklenburg-Vorpommern)
| width="400" valign="top" |
:[[Dommitzsch]] (Sachsen)
:[[Donaueschingen]] (Baden-Württemberg)
:[[Donauwörth]] (Bayern)
:[[Donzdorf]] (Baden-Württemberg)
:[[Dorfen]] (Bayern)
:[[Dormagen]] (Nordrhein-Westfalen)
:[[Dornburg/Saale]] (Thüringen)
:[[Dornhan]] (Baden-Württemberg)
:[[Dornstetten]] (Baden-Württemberg)
:[[Dorsten]] (Nordrhein-Westfalen)
:[[Dortmund]] (Nordrhein-Westfalen)
:[[Dransfeld]] (Niedersachsen)
:[[Drebkau]] (Brandenburg)
:[[Dreieich]] (Hessen)
:[[Drensteinfurt]] (Nordrhein-Westfalen)
:[[Dresden]] (Landeshauptstadt von Sachsen)
:[[Drolshagen]] (Nordrhein-Westfalen)
:[[Duderstadt]] (Niedersachsen)
:[[Duisburg]] (Nordrhein-Westfalen)
:[[Dülmen]] (Nordrhein-Westfalen)
:[[Düren]] (Nordrhein-Westfalen)
:[[Düsseldorf]] (Landeshauptstadt von NRW)
|}
{{TOC}}

===E===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Ebeleben]] (Thüringen)
:[[Eberbach (Baden)|Eberbach]] (Baden-Württemberg)
:[[Ebermannstadt]] (Bayern)
:[[Ebern]] (Bayern)
:[[Ebersbach an der Fils]] (Baden-Württ.)
:[[Ebersbach/Sa.]] (Sachsen)
:[[Ebersberg]] (Bayern)
:[[Eberswalde]] (Brandenburg)
:[[Eckartsberga]] (Sachsen-Anhalt)
:[[Eckernförde]] (Schleswig-Holstein)
:[[Edenkoben]] (Rheinland-Pfalz)
:[[Egeln]] (Sachsen-Anhalt)
:[[Eggenfelden]] (Bayern)
:[[Eggesin]] (Mecklenburg-Vorpommern)
:[[Ehingen (Donau)]] (Baden-Württemberg)
:[[Ehrenfriedersdorf]] (Sachsen)
:[[Eibelstadt]] (Bayern)
:[[Eibenstock]] (Sachsen)
:[[Eichstätt]] (Bayern)
:[[Eilenburg]] (Sachsen)
:[[Einbeck]] (Niedersachsen)
:[[Eisenach]] (Thüringen)
:[[Eisenberg (Thüringen)|Eisenberg]] (Thüringen)
:[[Eisenberg (Pfalz)]] (Rheinland-Pfalz)
:[[Eisenhüttenstadt]] (Brandenburg)
:[[Eisfeld]] (Thüringen)
:[[Eisleben]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Eislingen/Fils]] (Baden-Württemberg)
:[[Elbingerode (Harz)]] (Sachsen-Anhalt)
:[[Ellingen]] (Bayern)
:[[Ellrich]] (Thüringen)
:[[Ellwangen (Jagst)]] (Baden-Württemberg)
:[[Elmshorn]] (Schleswig-Holstein)
:[[Elsfleth]] (Niedersachsen)
:[[Elsterberg]] (Sachsen)
:[[Elsterwerda]] (Brandenburg)
:[[Elstra]] (Sachsen)
:[[Elterlein]] (Sachsen)
:[[Eltmann]] (Bayern)
:[[Eltville am Rhein]] (Hessen)
:[[Elzach]] (Baden-Württemberg)
:[[Elze]] (Niedersachsen)
:[[Emden]] (Niedersachsen)
:[[Emmendingen]] (Baden-Württemberg)
:[[Emmerich am Rhein]] (Nordrhein-Westf.)
:[[Emsdetten]] (Nordrhein-Westfalen)
:[[Endingen am Kaiserstuhl]] (Baden-Württ.)
:[[Engen]] (Baden-Württemberg)
:[[Enger]] (Nordrhein-Westfalen)
:[[Ennepetal]] (Nordrhein-Westfalen)
:[[Ennigerloh]] (Nordrhein-Westfalen)
:[[Eppelheim]] (Baden-Württemberg)
:[[Eppingen]] (Baden-Württemberg)
| width="400" valign="top" |
:[[Eppstein]] (Hessen)
:[[Erbach (Donau)|Erbach]] (Baden-Württemberg)
:[[Erbach (Odenwald)]] (Hessen)
:[[Erbendorf]] (Bayern)
:[[Erding]] (Bayern)
:[[Erftstadt]] (Nordrhein-Westfalen)
:[[Erfurt]] (Landeshauptstadt von Thüringen)
:[[Erkelenz]] (Nordrhein-Westfalen)
:[[Erkner]] (Brandenburg)
:[[Erkrath]] (Nordrhein-Westfalen)
:[[Erlangen]] (Bayern)
:[[Erlenbach am Main]] (Bayern)
:[[Erwitte]] (Nordrhein-Westfalen)
:[[Eschborn]] (Hessen)
:[[Eschenbach in der Oberpfalz]] (Bayern)
:[[Eschershausen]] (Niedersachsen)
:[[Eschwege]] (Hessen)
:[[Eschweiler]] (Nordrhein-Westfalen)
:[[Esens]] (Niedersachsen)
:[[Espelkamp]] (Nordrhein-Westfalen)
:[[Essen]] (Nordrhein-Westfalen)
:[[Esslingen am Neckar]] (Baden-Württ.)
:[[Ettenheim]] (Baden-Württemberg)
:[[Ettlingen]] (Baden-Württemberg)
:[[Euskirchen]] (Nordrhein-Westfalen)
:[[Eutin]] (Schleswig-Holstein)
|}
{{TOC}}

===F===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Falkenberg/Elster]] (Brandenburg)
:[[Falkensee]] (Brandenburg)
:[[Falkenstein/Harz]] (Sachsen-Anhalt)
:[[Falkenstein/Vogtl.]] (Sachsen)
:[[Fehmarn]] (Schleswig-Holstein)
:[[Fellbach]] (Baden-Württemberg)
:[[Felsberg (Hessen)|Felsberg]] (Hessen))
:[[Feuchtwangen]] (Bayern)
:[[Filderstadt]] (Baden-Württemberg)
:[[Finsterwalde]] (Brandenburg)
:[[Fladungen]] (Bayern)
:[[Flensburg]] (Schleswig-Holstein)
:[[Flöha]] (Sachsen)
:[[Flörsheim am Main]] (Hessen)
:[[Forchheim]] (Bayern)
:[[Forchtenberg]] (Baden-Württemberg)
:[[Forst (Lausitz)]] (Brandenburg)
:[[Frankenau]] (Hessen)
:[[Frankenberg (Eder)]] (Hessen)
:[[Frankenberg/Sa.]] (Sachsen)
:[[Frankenthal (Pfalz)]] (Rheinland-Pfalz)
:[[Frankfurt am Main]] (Hessen)
| width="400" valign="top" |
:[[Frankfurt (Oder)]] (Brandenburg)
:[[Franzburg]] (Mecklenburg-Vorpommern)
:[[Frauenstein (Erzgebirge)|Frauenstein]] (Sachsen)
:[[Frechen]] (Nordrhein-Westfalen)
:[[Freiberg am Neckar]] (Baden-Württemb.)
:[[Freiberg (Sachsen)|Freiberg]] (Sachsen)
:[[Freiburg im Breisgau]] (Baden-Württemb.)
:[[Freilassing]] (Bayern)
:[[Freinsheim]] (Rheinland-Pfalz)
:[[Freising]] (Bayern)
:[[Freital]] (Sachsen)
:[[Freren]] (Niedersachsen)
:[[Freudenberg (Baden)|Freudenberg]] (Baden-Württemberg)
:[[Freudenberg (Siegerland)|Freudenberg]] (Nordrhein-Westfalen)
:[[Freudenstadt]] (Baden-Württemberg)
:[[Freyburg (Unstrut)]] (Sachsen-Anhalt)
:[[Freystadt (Oberpfalz)|Freystadt]] (Bayern)
:[[Freyung]] (Bayern)
:[[Fridingen an der Donau]] (Baden-Württ.)
:[[Friedberg (Bayern)|Friedberg]] (Bayern)
:[[Friedberg (Hessen)]] (Hessen)
| width="400" valign="top" |
:[[Friedland (Mecklenburg)|Friedland]] (Mecklenburg-Vorpommern)
:[[Friedland (Niederlausitz)|Friedland]] (Brandenburg)
:[[Friedrichroda]] (Thüringen)
:[[Friedrichsdorf (Taunus)|Friedrichsdorf]] (Hessen)
:[[Friedrichshafen]] (Baden-Württemberg)
:[[Friedrichstadt]] (Schleswig-Holstein)
:[[Friedrichsthal (Saar)|Friedrichsthal]] (Saarland)
:[[Friesack]] (Brandenburg)
:[[Friesoythe]] (Niedersachsen)
:[[Fritzlar]] (Hessen)
:[[Frohburg]] (Sachsen)
:[[Fröndenberg/Ruhr]] (Nordrhein-Westfalen)
:[[Fulda]] (Hessen)
:[[Fürstenau (Stadt)|Fürstenau]] (Niedersachsen)
:[[Fürstenberg/Havel]] (Brandenburg)
:[[Fürstenfeldbruck]] (Bayern)
:[[Fürstenwalde/Spree]] (Brandenburg)
:[[Fürth]] (Bayern)
:[[Furth im Wald]] (Bayern)
:[[Furtwangen im Schwarzwald]] (Baden-W.)
:[[Füssen]] (Bayern)
|}
{{TOC}}

===G===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Gadebusch]] (Mecklenburg-Vorpommern)
:[[Gaggenau]] (Baden-Württemberg)
:[[Gaildorf]] (Baden-Württemberg)
:[[Gammertingen]] (Baden-Württemberg)
:[[Garbsen]] (Niedersachsen)
:[[Garching bei München]] (Bayern)
:[[Gardelegen]] (Sachsen-Anhalt)
:[[Garding]] (Schleswig-Holstein)
:[[Gartz (Oder)]] (Brandenburg)
:[[Garz/Rügen]] (Mecklenburg-Vorpomm.)
:[[Gau-Algesheim]] (Rheinland-Pfalz)
:[[Gebesee]] (Thüringen)
:[[Gedern]] (Hessen)
:[[Geesthacht]] (Schleswig-Holstein)
:[[Gefell (bei Schleiz)|Gefell]] (Thüringen)
:[[Gefrees]] (Bayern)
:[[Gehrden]] (Niedersachsen)
:[[Gehren]] (Thüringen)
:[[Geilenkirchen]] (Nordrhein-Westfalen)
:[[Geisa]] (Thüringen)
:[[Geiselhöring]] (Bayern)
:[[Geisenfeld]] (Bayern)
:[[Geisenheim]] (Hessen)
:[[Geising]] (Sachsen)
:[[Geisingen]] (Baden-Württemberg)
:[[Geislingen (bei Balingen)|Geislingen]] (Baden-Württemberg)
:[[Geislingen an der Steige]] (Baden-Württ.)
:[[Geithain]] (Sachsen)
:[[Geldern]] (Nordrhein-Westfalen)
:[[Gelnhausen]] (Hessen)
:[[Gelsenkirchen]] (Nordrhein-Westfalen)
:[[Gemünden am Main]] (Bayern)
:[[Gemünden (Wohra)]] (Hessen)
:[[Gengenbach]] (Baden-Württemberg)
:[[Genthin]] (Sachsen-Anhalt)
:[[Georgsmarienhütte]] (Niedersachsen)
:[[Gera]] (Thüringen)
:[[Gerabronn]] (Baden-Württemberg)
:[[Gerbstedt]] (Sachsen-Anhalt)
:[[Geretsried]] (Bayern)
:[[Geringswalde]] (Sachsen)
:[[Gerlingen]] (Baden-Württemberg)
:[[Germering]] (Bayern)
:[[Germersheim]] (Rheinland-Pfalz)
| width="400" valign="top" |
:[[Gernrode]] (Sachsen-Anhalt)
:[[Gernsbach]] (Baden-Württemberg)
:[[Gernsheim]] (Hessen)
:[[Gerolstein]] (Rheinland-Pfalz)
:[[Gerolzhofen]] (Bayern)
:[[Gersfeld (Rhön)]] (Hessen)
:[[Gersthofen]] (Bayern)
:[[Gescher]] (Nordrhein-Westfalen)
:[[Geseke]] (Nordrhein-Westfalen)
:[[Gevelsberg]] (Nordrhein-Westfalen)
:[[Geyer]] (Sachsen)
:[[Giengen an der Brenz]] (Baden-Württ.)
:[[Gießen]] (Hessen)
:[[Gifhorn]] (Niedersachsen)
:[[Gladbeck]] (Nordrhein-Westfalen)
:[[Gladenbach]] (Hessen)
:[[Glashütte (Sachsen)|Glashütte]] (Sachsen)
:[[Glauchau]] (Sachsen)
:[[Glinde (Stormarn)|Glinde]] (Schleswig-Holstein)
:[[Glücksburg (Ostsee)]] (Schleswig-Holst.)
:[[Glückstadt]] (Schleswig-Holstein)
:[[Gnoien]] (Mecklenburg-Vorpommern)
:[[Goch]] (Nordrhein-Westfalen)
:[[Goldberg (Mecklenburg)|Goldberg]] (Mecklenburg-Vorpommern)
:[[Goldkronach]] (Bayern)
:[[Golßen]] (Brandenburg)
:[[Gommern]] (Sachsen-Anhalt)
:[[Göppingen]] (Baden-Württemberg)
:[[Görlitz]] (Sachsen)
:[[Goslar]] (Niedersachsen)
:[[Gößnitz]] (Thüringen)
:[[Gotha]] (Thüringen)
:[[Göttingen]] (Niedersachsen)
:[[Grabow (Elde)|Grabow]] (Mecklenburg-Vorpommern)
:[[Grafenau (Niederbayern)|Grafenau]] (Bayern)
:[[Gräfenberg]] (Bayern)
:[[Gräfenhainichen]] (Sachsen-Anhalt)
:[[Gräfenthal]] (Thüringen)
:[[Grafenwöhr]] (Bayern)
:[[Grafing bei München]] (Bayern)
:[[Gransee]] (Brandenburg)
:[[Grebenau]] (Hessen)
:[[Grebenstein]] (Hessen)
:[[Greding]] (Bayern)´
| width="400" valign="top" |
:[[Greifswald]] (Meckl.-Vorp. / Hansestadt)
:[[Greiz]] (Thüringen)
:[[Greußen]] (Thüringen)
:[[Greven (Westfalen)|Greven]] (Nordrhein-Westfalen)
:[[Grevenbroich]] (Nordrhein-Westfalen)
:[[Grevesmühlen]] (Mecklenburg-Vorp.)
:[[Griesheim]] (Hessen)
:[[Grimma]] (Sachsen)
:[[Grimmen]] (Mecklenburg-Vorpommern)
:[[Gröbzig]] (Sachsen-Anhalt)
:[[Gröditz]] (Sachsen)
:[[Groitzsch]] (Sachsen)
:[[Gronau (Leine)]] (Niedersachsen)
:[[Gronau (Westf.)]] (Nordrhein-Westfalen)
:[[Gröningen]] (Sachsen-Anhalt)
:[[Großalmerode]] (Hessen)
:[[Groß-Bieberau]] (Hessen)
:[[Großbottwar]] (Baden-Württemberg)
:[[Großbreitenbach]] (Thüringen)
:[[Großenehrich]] (Thüringen)
:[[Großenhain]] (Sachsen)
:[[Groß-Gerau]] (Hessen)
:[[Großräschen]] (Brandenburg)
:[[Großröhrsdorf]] (Sachsen)
:[[Großschirma]] (Sachsen)
:[[Groß-Umstadt]] (Hessen)
:[[Grünberg (Hessen)|Grünberg]] (Hessen)
:[[Grünhain-Beierfeld]] (Sachsen)
:[[Grünsfeld]] (Baden-Württemberg)
:[[Grünstadt]] (Rheinland-Pfalz)
:[[Guben]] (Brandenburg)
:[[Gudensberg]] (Hessen)
:[[Güglingen]] (Baden-Württemberg)
:[[Gummersbach]] (Nordrhein-Westfalen)
:[[Gundelfingen an der Donau]] (Bayern)
:[[Gundelsheim (Württemberg)|Gundelsheim]] (Baden-Württemberg)
:[[Güntersberge]] (Sachsen-Anhalt)
:[[Günzburg]] (Bayern)
:[[Gunzenhausen]] (Bayern)
:[[Güsten]] (Sachsen-Anhalt)
:[[Güstrow]] (Mecklenburg-Vorpommern)
:[[Gütersloh]] (Nordrhein-Westfalen)
:[[Gützkow]] (Mecklenburg-Vorpommern)
|}
{{TOC}}

===H===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Haan]] (Nordrhein-Westfalen)
:[[Hachenburg]] (Rheinland-Pfalz)
:[[Hadamar]] (Hessen)
:[[Hadmersleben]] (Sachsen-Anhalt)
:[[Hagen]] (Nordrhein-Westfalen)
:[[Hagenbach]] (Rheinland-Pfalz)
:[[Hagenow]] (Mecklenburg-Vorpommern)
:[[Haiger]] (Hessen)
:[[Haigerloch]] (Baden-Württemberg)
:[[Hainichen]] (Sachsen)
:[[Haiterbach]] (Baden-Württemberg)
:[[Halberstadt]] (Sachsen-Anhalt)
:[[Haldensleben]] (Sachsen-Anhalt)
:[[Halle (Saale)]] (Sachsen-Anhalt)
:[[Halle (Westf.)]] (Nordrhein-Westfalen)
:[[Hallenberg]] (Nordrhein-Westfalen)
:[[Hallstadt]] (Bayern)
:[[Haltern am See]] (Nordrhein-Westfalen)
:[[Halver]] (Nordrhein-Westfalen)
:[[Hamburg]] (Freie und Hansestadt)
:[[Hameln]] (Niedersachsen)
:[[Hamm]] (Nordrhein-Westfalen)
:[[Hammelburg]] (Bayern)
:[[Hamminkeln]] (Nordrhein-Westfalen)
:[[Hanau]] (Hessen)
:[[Hannover]] (Landeshauptst. von Nieders.)
:[[Hann. Münden]] (Niedersachsen)
:[[Harburg (Schwaben)]] (Bayern)
:[[Hardegsen]] (Niedersachsen)
:[[Haren (Ems)]] (Niedersachsen)
:[[Harsewinkel]] (Nordrhein-Westfalen)
:[[Hartenstein (Sachsen)|Hartenstein]] (Sachsen)
:[[Hartha]] (Sachsen)
:[[Harzgerode]] (Sachsen-Anhalt)
:[[Haselünne]] (Niedersachsen)
:[[Haslach im Kinzigtal]] (Baden-Württ.)
:[[Hasselfelde]] (Sachsen-Anhalt)
:[[Haßfurt]] (Bayern)
:[[Hattersheim am Main]] (Hessen)
:[[Hattingen]] (Nordrhein-Westfalen)
:[[Hatzfeld (Eder)]] (Hessen)
:[[Hausach]] (Baden-Württemberg)
:[[Hauzenberg]] (Bayern)
:[[Havelberg]] (Sachsen-Anhalt)
:[[Havelsee]] (Brandenburg)
:[[Hayingen]] (Baden-Württemberg)
:[[Hechingen]] (Baden-Württemberg)
:[[Hecklingen]] (Sachsen-Anhalt)
:[[Heide (Holstein)|Heide]] (Schleswig-Holstein)
:[[Heideck]] (Bayern)
| width="400" valign="top" |
:[[Heidelberg]] (Baden-Württemberg)
:[[Heidenau (Sachsen)|Heidenau]] (Sachsen)
:[[Heidenheim an der Brenz]] (Baden-Württ.)
:[[Heilbad Heiligenstadt]] (Thüringen)
:[[Heilbronn]] (Baden-Württemberg)
:[[Heiligenhafen]] (Schleswig-Holstein)
:[[Heiligenhaus]] (Nordrhein-Westfalen)
:[[Heilsbronn]] (Bayern)
:[[Heimbach (Eifel)|Heimbach]] (Nordrhein-Westfalen)
:[[Heimsheim]] (Baden-Württemberg)
:[[Heinsberg]] (Nordrhein-Westfalen)
:[[Heitersheim]] (Baden-Württemberg)
:[[Heldrungen]] (Thüringen)
:[[Helmbrechts]] (Bayern)
:[[Helmstedt]] (Niedersachsen)
:[[Hemau]] (Bayern)
:[[Hemer]] (Nordrhein-Westfalen)
:[[Hemmingen (Niedersachsen)|Hemmingen]] (Niedersachsen)
:[[Hemmoor]] (Niedersachsen)
:[[Hemsbach]] (Baden-Württemberg)
:[[Hennef (Sieg)]] (Nordrhein-Westfalen)
:[[Hennigsdorf]] (Brandenburg)
:[[Heppenheim (Bergstraße)]] (Hessen)
:[[Herbolzheim]] (Baden-Württemberg)
:[[Herborn]] (Hessen)
:[[Herbrechtingen]] (Baden-Württemberg)
:[[Herbstein]] (Hessen)
:[[Herdecke]] (Nordrhein-Westfalen)
:[[Herdorf]] (Rheinland-Pfalz)
:[[Herford]] (Nordrhein-Westfalen)
:[[Heringen/Helme]] (Thüringen)
:[[Heringen (Werra)]] (Hessen)
:[[Hermeskeil]] (Rheinland-Pfalz)
:[[Hermsdorf (Thüringen)|Hermsdorf]] (Thüringen)
:[[Herne]] (Nordrhein-Westfalen)
:[[Herrenberg]] (Baden-Württemberg)
:[[Herrieden]] (Bayern)
:[[Herrnhut]] (Sachsen)
:[[Hersbruck]] (Bayern)
:[[Herten]] (Nordrhein-Westfalen)
:[[Herzberg am Harz]] (Niedersachsen)
:[[Herzberg (Elster)]] (Brandenburg)
:[[Herzogenaurach]] (Bayern)
:[[Herzogenrath]] (Nordrhein-Westfalen)
:[[Hessisch Lichtenau]] (Hessen)
:[[Hessisch Oldendorf]] (Niedersachsen)
:[[Hettingen]] (Baden-Württemberg)
:[[Hettstedt]] (Sachsen-Anhalt)
:[[Heubach (Württemberg)|Heubach]] (Baden-Württemberg)
:[[Heusenstamm]] (Hessen)
| width="400" valign="top" |
:[[Hilchenbach]] (Nordrhein-Westfalen)
:[[Hildburghausen]] (Thüringen)
:[[Hilden]] (Nordrhein-Westfalen)
:[[Hildesheim]] (Niedersachsen)
:[[Hillesheim (Eifel)|Hillesheim]] (Rheinland-Pfalz)
:[[Hilpoltstein]] (Bayern)
:[[Hirschau]] (Bayern)
:[[Hirschberg (Saale)|Hirschberg]] (Thüringen)
:[[Hirschhorn (Neckar)]] (Hessen)
:[[Hitzacker (Elbe)]] (Niedersachsen)
:[[Hochheim am Main]] (Hessen)
:[[Höchstadt an der Aisch]] (Bayern)
:[[Höchstädt an der Donau]] (Bayern)
:[[Hockenheim]] (Baden-Württemberg)
:[[Hof (Saale)|Hof]] (Bayern)
:[[Hofgeismar]] (Hessen)
:[[Hofheim am Taunus]] (Hessen)
:[[Hofheim in Unterfranken]] (Bayern)
:[[Hohenberg an der Eger]] (Bayern)
:[[Hohenleuben]] (Thüringen)
:[[Hohenmölsen]] (Sachsen-Anhalt)
:[[Hohen Neuendorf]] (Brandenburg)
:[[Hohenstein-Ernstthal]] (Sachsen)
:[[Hohnstein (Sächs. Schweiz)|Hohnstein]] (Sachsen)
:[[Höhr-Grenzhausen]] (Rheinland-Pfalz)
:[[Hollfeld]] (Bayern)
:[[Holzgerlingen]] (Baden-Württemberg)
:[[Holzminden]] (Niedersachsen)
:[[Homberg (Efze)]] (Hessen)
:[[Homberg (Ohm)]] (Hessen)
:[[Homburg (Saar)]] (Saarland)
:[[Horb am Neckar]] (Baden-Württemberg)
:[[Hornbach]] (Rheinland-Pfalz)
:[[Horn-Bad Meinberg]] (Nordrhein-Westf.)
:[[Hornberg (Schwarzwald)|Hornberg]] (Baden-Württemberg)
:[[Hornburg]] (Niedersachsen)
:[[Hörstel]] (Nordrhein-Westfalen)
:[[Horstmar]] (Nordrhein-Westfalen)
:[[Höxter]] (Nordrhein-Westfalen)
:[[Hoya]] (Niedersachsen)
:[[Hoyerswerda]] (Sachsen)
:[[Hoym]] (Sachsen-Anhalt)
:[[Hückelhoven]] (Nordrhein-Westfalen)
:[[Hückeswagen]] (Nordrhein-Westfalen)
:[[Hüfingen]] (Baden-Württemberg)
:[[Hünfeld]] (Hessen)
:[[Hungen]] (Hessen)
:[[Hürth]] (Nordrhein-Westfalen)
:[[Husum]] (Schleswig-Holstein)
|}
{{TOC}}
===I===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Ibbenbüren]] (Nordrhein-Westfalen)
:[[Ichenhausen]] (Bayern)
:[[Idar-Oberstein]] (Rheinland-Pfalz)
:[[Idstein]] (Hessen)
:[[Illertissen]] (Bayern)
:[[Ilmenau]] (Thüringen)
| width="400" valign="top" |
:[[Ilsenburg (Harz)]] (Sachsen-Anhalt)
:[[Ilshofen]] (Baden-Württemberg)
:[[Immenhausen]] (Hessen)
:[[Immenstadt im Allgäu]] (Bayern)
:[[Ingelfingen]] (Baden-Württemberg)
:[[Ingelheim am Rhein]] (Rheinland-Pfalz)
| width="400" valign="top" |
:[[Ingolstadt]] (Bayern)
:[[Iphofen]] (Bayern)
:[[Iserlohn]] (Nordrhein-Westfalen)
:[[Isny im Allgäu]] (Baden-Württemberg)
:[[Isselburg]] (Nordrhein-Westfalen)
:[[Itzehoe]] (Schleswig-Holstein)
|}
{{TOC}}
===J===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Jarmen]] (Mecklenburg-Vorpommern)
:[[Jena]] (Thüringen)
:[[Jerichow]] (Sachsen-Anhalt)
:[[Jessen (Elster)]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Jeßnitz (Anhalt)]] (Sachsen-Anhalt)
:[[Jever]] (Niedersachsen)
:[[Joachimsthal (Barnim)|Joachimsthal]] (Brandenburg)
:[[Johanngeorgenstadt]] (Sachsen)
| width="400" valign="top" |
:[[Jöhstadt]] (Sachsen)
:[[Jülich]] (Nordrhein-Westfalen)
:[[Jüterbog]] (Brandenburg)
|}
{{TOC}}
===K===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Kaarst]] (Nordrhein-Westfalen)
:[[Kahla]] (Thüringen)
:[[Kaisersesch]] (Rheinland-Pfalz)
:[[Kaiserslautern]] (Rheinland-Pfalz)
:[[Kalbe (Milde)]] (Sachsen-Anhalt)
:[[Kalkar]] (Nordrhein-Westfalen)
:[[Kaltenkirchen]] (Schleswig-Holstein)
:[[Kaltennordheim]] (Thüringen)
:[[Kamen]] (Nordrhein-Westfalen)
:[[Kamenz]] (Sachsen)
:[[Kamp-Lintfort]] (Nordrhein-Westfalen)
:[[Kandel (Stadt)|Kandel]] (Rheinland-Pfalz)
:[[Kandern]] (Baden-Württemberg)
:[[Kappeln]] (Schleswig-Holstein)
:[[Karben]] (Hessen)
:[[Karlsruhe]] (Baden-Württemberg)
:[[Karlstadt]] (Bayern)
:[[Kassel]] (Hessen)
:[[Kastellaun]] (Rheinland-Pfalz)
:[[Katzenelnbogen]] (Rheinland-Pfalz)
:[[Kaub]] (Rheinland-Pfalz)
:[[Kaufbeuren]] (Bayern)
:[[Kehl]] (Baden-Württemberg)
:[[Kelbra (Kyffhäuser)]] (Sachsen-Anhalt)
:[[Kelheim]] (Bayern)
:[[Kelkheim (Taunus)]] (Hessen)
:[[Kellinghusen]] (Schleswig-Holstein)
:[[Kelsterbach]] (Hessen)
:[[Kemberg]] (Sachsen-Anhalt)
:[[Kemnath]] (Bayern)
:[[Kempen]] (Nordrhein-Westfalen)
:[[Kempten (Allgäu)]] (Bayern)
:[[Kenzingen]] (Baden-Württemberg)
:[[Kerpen]] (Nordrhein-Westfalen)
| width="400" valign="top" |
:[[Ketzin]] (Brandenburg)
:[[Kevelaer]] (Nordrhein-Westfalen)
:[[Kiel]] (Landeshauptstadt von Schl.-Holst.)
:[[Kierspe]] (Nordrhein-Westfalen)
:[[Kindelbrück]] (Thüringen)
:[[Kirchberg (Sachsen)|Kirchberg]] (Sachsen)
:[[Kirchberg an der Jagst]] (Baden-Württ.)
:[[Kirchberg (Hunsrück)]] (Rheinland-Pfalz)
:[[Kirchen (Sieg)]] (Rheinland-Pfalz)
:[[Kirchenlamitz]] (Bayern)
:[[Kirchhain]] (Hessen)
:[[Kirchheimbolanden]] (Rheinland-Pfalz)
:[[Kirchheim unter Teck]] (Baden-Württemb.)
:[[Kirn]] (Rheinland-Pfalz)
:[[Kirtorf]] (Hessen)
:[[Kitzingen]] (Bayern)
:[[Kitzscher]] (Sachsen)
:[[Kleve]] (Nordrhein-Westfalen)
:[[Klingenberg am Main]] (Bayern)
:[[Klingenthal/Sa.]] (Sachsen)
:[[Klötze]] (Sachsen-Anhalt)
:[[Klütz]] (Mecklenburg-Vorpommern)
:[[Knittlingen]] (Baden-Württemberg)
:[[Koblenz]] (Rheinland-Pfalz)
:[[Kohren-Sahlis]] (Sachsen)
:[[Kolbermoor]] (Bayern)
:[[Kölleda]] (Thüringen)
:[[Köln]] (Nordrhein-Westfalen)
:[[Königsberg in Bayern]] (Bayern)
:[[Königsbrück]] (Sachsen)
:[[Königsbrunn]] (Bayern)
:[[Königsee]] (Thüringen)
:[[Königslutter am Elm]] (Niedersachsen)
:[[Königstein im Taunus]] (Hessen)
| width="400" valign="top" |
:[[Königstein (Sächsische Schweiz)]] (Sa.)
:[[Königswinter]] (Nordrhein-Westfalen)
:[[Königs Wusterhausen]] (Brandenburg)
:[[Könnern]] (Sachsen-Anhalt)
:[[Konstanz]] (Baden-Württemberg)
:[[Konz]] (Rheinland-Pfalz)
:[[Korbach]] (Hessen)
:[[Korntal-Münchingen]] (Baden-Württemb.)
:[[Kornwestheim]] (Baden-Württemberg)
:[[Korschenbroich]] (Nordrhein-Westfalen)
:[[Köthen (Anhalt)]] (Sachsen-Anhalt)
:[[Kraichtal]] (Baden-Württemberg)
:[[Krakow am See]] (Mecklenb.-Vorpomm.)
:[[Kranichfeld]] (Thüringen)
:[[Krautheim (Jagst)|Krautheim]] (Baden-Württemberg)
:[[Krefeld]] (Nordrhein-Westfalen)
:[[Kremmen]] (Brandenburg)
:[[Krempe (Steinburg)|Krempe]] (Schleswig-Holstein)
:[[Kreuztal]] (Nordrhein-Westfalen)
:[[Kronach]] (Bayern)
:[[Kronberg im Taunus]] (Hessen)
:[[Kröpelin]] (Mecklenburg-Vorpommern)
:[[Kroppenstedt]] (Sachsen-Anhalt)
:[[Krumbach (Schwaben)]] (Bayern)
:[[Kühlungsborn]] (Mecklenb.-Vorpommern)
:[[Kulmbach]] (Bayern)
:[[Külsheim]] (Baden-Württemberg)
:[[Künzelsau]] (Baden-Württemberg)
:[[Kupferberg (Oberfranken)|Kupferberg]] (Bayern)
:[[Kuppenheim]] (Baden-Württemberg)
:[[Kusel]] (Rheinland-Pfalz)
:[[Kyllburg]] (Rheinland-Pfalz)
:[[Kyritz]] (Brandenburg)
|}
{{TOC}}

===L===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Laage]] (Mecklenburg-Vorpommern)
:[[Laatzen]] (Niedersachsen)
:[[Ladenburg]] (Baden-Württemberg)
:[[Lage (Lippe)|Lage]] (Nordrhein-Westfalen)
:[[Lahnstein]] (Rheinland-Pfalz)
:[[Lahr/Schwarzwald]] (Baden-Württemberg)
:[[Laichingen]] (Baden-Württemberg)
:[[Lambrecht (Pfalz)]] (Rheinland-Pfalz)
:[[Lampertheim]] (Hessen)
:[[Landau an der Isar]] (Bayern)
:[[Landau in der Pfalz]] (Rheinland-Pfalz)
:[[Landsberg am Lech]] (Bayern)
:[[Landsberg (Saalkreis)|Landsberg]] (Sachsen-Anhalt)
:[[Landshut]] (Bayern)
:[[Landstuhl]] (Rheinland-Pfalz)
:[[Langelsheim]] (Niedersachsen)
:[[Langen (bei Bremerhaven)|Langen]] (Niedersachsen)
:[[Langen (Hessen)]] (Hessen)
:[[Langenau (Württemberg)|Langenau]] (Baden-Württemberg)
:[[Langenburg]] (Baden-Württemberg)
:[[Langenfeld (Rheinland)]] (Nordrhein-Westf.)
:[[Langenhagen (Region Hannover)|Langenhagen]] (Niedersachsen)
:[[Langenselbold]] (Hessen)
:[[Langenzenn]] (Bayern)
:[[Langewiesen]] (Thüringen)
:[[Lassan]] (Mecklenburg-Vorpommern)
:[[Laubach]] (Hessen)
:[[Laucha an der Unstrut]] (Sachsen-Anhalt)
:[[Lauchhammer]] (Brandenburg)
:[[Lauchheim]] (Baden-Württemberg)
:[[Lauda-Königshofen]] (Baden-Württemberg)
:[[Lauenburg/Elbe]] (Schleswig-Holstein)
:[[Lauf an der Pegnitz]] (Bayern)
:[[Laufen (Salzach)|Laufen]] (Bayern)
:[[Laufenburg (Baden)]] (Baden-Württemberg)
:[[Lauffen am Neckar]] (Baden-Württemberg)
:[[Lauingen|Lauingen (Donau)]] (Bayern)
:[[Laupheim]] (Baden-Württemberg)
:[[Lauscha]] (Thüringen)
:[[Lauta]] (Sachsen)
:[[Lauter/Sa.]] (Sachsen)
:[[Lauterbach (Hessen)]] (Hessen)
:[[Lauterecken]] (Rheinland-Pfalz)
:[[Lauterstein]] (Baden-Württemberg)
:[[Lebach]] (Saarland)
| width="400" valign="top" |
:[[Lebus (Stadt)|Lebus]] (Brandenburg)
:[[Leer (Ostfriesland)]] (Niedersachsen)
:[[Lehesten]] (Thüringen)
:[[Lehrte]] (Niedersachsen)
:[[Leichlingen (Rheinland)]] (Nordrh.-Westf.)
:[[Leimen (Baden)]] (Baden-Württemberg)
:[[Leinefelde-Worbis]] (Thüringen)
:[[Leinfelden-Echterdingen]] (Baden-Württ.)
:[[Leipheim]] (Bayern)
:[[Leipzig]] (Sachsen)
:[[Leisnig]] (Sachsen)
:[[Lemgo]] (Nordrhein-Westfalen)
:[[Lengefeld]] (Sachsen)
:[[Lengenfeld (Vogtland)|Lengenfeld]] (Sachsen)
:[[Lengerich (Westfalen)|Lengerich]] (Nordrhein-Westfalen)
:[[Lennestadt]] (Nordrhein-Westfalen)
:[[Lenzen (Elbe)|Lenzen]] (Brandenburg)
:[[Leonberg]] (Baden-Württemberg)
:[[Leun]] (Hessen)
:[[Leuna]] (Sachsen-Anhalt)
:[[Leutenberg]] (Thüringen)
:[[Leutershausen]] (Bayern)
:[[Leutkirch im Allgäu]] (Baden-Württemb.)
:[[Leverkusen]] (Nordrhein-Westfalen)
:[[Lich (Hessen)|Lich]] (Hessen)
:[[Lichtenau (Baden)|Lichtenau]] (Baden-Württemberg)
:[[Lichtenau (Westfalen)|Lichtenau]] (Nordrhein-Westfalen)
:[[Lichtenberg (Oberfranken)|Lichtenberg]] (Bayern)
:[[Lichtenfels]] (Bayern)
:[[Lichtenfels (Hessen)|Lichtenfels]] (Hessen)
:[[Lichtenstein/Sa.]] (Sachsen)
:[[Liebenau]] (Hessen)
:[[Liebenwalde]] (Brandenburg)
:[[Lieberose]] (Brandenburg)
:[[Liebstadt]] (Sachsen)
:[[Limbach-Oberfrohna]] (Sachsen)
:[[Limburg an der Lahn]] (Hessen)
:[[Lindau (Anhalt)|Lindau]] (Sachsen-Anhalt)
:[[Lindau|Lindau (Bodensee)]] (Bayern)
:[[Linden (Hessen)|Linden]] (Hessen)
:[[Lindenberg im Allgäu]] (Bayern)
:[[Lindenfels]] (Hessen)
:[[Lindow (Mark)]] (Brandenburg)
:[[Lingen (Ems)]] (Niedersachsen)
:[[Linnich]] (Nordrhein-Westfalen)
| width="400" valign="top" |
:[[Linz am Rhein]] (Rheinland-Pfalz)
:[[Lippstadt]] (Nordrhein-Westfalen)
:[[Löbau]] (Sachsen)
:[[Löbejün]] (Sachsen-Anhalt)
:[[Loburg]] (Sachsen-Anhalt)
:[[Löffingen]] (Baden-Württemberg)
:[[Lohmar]] (Nordrhein-Westfalen)
:[[Lohne (Oldenburg)]] (Niedersachsen)
:[[Löhne]] (Nordrhein-Westfalen)
:[[Lohr am Main]] (Bayern)
:[[Loitz]] (Mecklenburg-Vorpommern)
:[[Lollar]] (Hessen)
:[[Lommatzsch]] (Sachsen)
:[[Löningen]] (Niedersachsen)
:[[Lorch (Württemberg)|Lorch]] (Baden-Württemberg)
:[[Lorch (Rheingau)|Lorch]] (Hessen)
:[[Lörrach]] (Baden-Württemberg)
:[[Lorsch]] (Hessen)
:[[Lößnitz]] (Sachsen)
:[[Löwenstein]] (Baden-Württemberg)
:[[Lübbecke]] (Nordrhein-Westfalen)
:[[Lübben (Spreewald)]] (Brandenburg)
:[[Lübbenau/Spreewald]] (Brandenburg)
:[[Lübeck]] (Schleswig-Holst. / Hansestadt)
:[[Lübtheen]] (Mecklenburg-Vorpommern)
:[[Lübz]] (Mecklenburg-Vorpommern)
:[[Lüchow (Wendland)]] (Niedersachsen)
:[[Lucka]] (Thüringen)
:[[Luckau]] (Brandenburg)
:[[Luckenwalde]] (Brandenburg)
:[[Lüdenscheid]] (Nordrhein-Westfalen)
:[[Lüdinghausen]] (Nordrhein-Westfalen)
:[[Ludwigsburg]] (Baden-Württemberg)
:[[Ludwigsfelde]] (Brandenburg)
:[[Ludwigshafen am Rhein]] (Rheinland-Pfalz)
:[[Ludwigslust]] (Mecklenburg-Vorpommern)
:[[Ludwigsstadt]] (Bayern)
:[[Lugau/Erzgeb.]] (Sachsen)
:[[Lügde]] (Nordrhein-Westfalen)
:[[Lüneburg]] (Niedersachsen)
:[[Lünen]] (Nordrhein-Westfalen)
:[[Lunzenau]] (Sachsen)
:[[Lütjenburg]] (Schleswig-Holstein)
:[[Lützen]] (Sachsen-Anhalt)
:[[Lychen]] (Brandenburg)
|}
{{TOC}}

===M===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Magdala]] (Thüringen)
:[[Magdeburg]] (Landeshauptst. Sachs.-A.)
:[[Mahlberg]] (Baden-Württemberg)
:[[Mainbernheim]] (Bayern)
:[[Mainburg]] (Bayern)
:[[Maintal]] (Hessen)
:[[Mainz]] (Landeshauptst. von Rheinl.-Pfalz)
:[[Malchin]] (Mecklenburg-Vorpommern)
:[[Malchow (Mecklenburg)|Malchow]] (Mecklenburg-Vorpommern)
:[[Mannheim]] (Baden-Württemberg)
:[[Manderscheid (Stadt)|Manderscheid]] (Rheinland-Pfalz)
:[[Mansfeld]] (Sachsen-Anhalt)
:[[Marbach am Neckar]] (Baden-Württ.)
:[[Marburg]] (Hessen)
:[[Marienberg (Erzgebirge)|Marienberg]] (Sachsen)
:[[Marienmünster]] (Nordrhein-Westfalen)
:[[Markdorf]] (Baden-Württemberg)
:[[Markgröningen]] (Baden-Württemberg)
:[[Märkisch Buchholz]] (Brandenburg)
:[[Markkleeberg]] (Sachsen)
:[[Markneukirchen]] (Sachsen)
:[[Markranstädt]] (Sachsen)
:[[Marktbreit]] (Bayern)
:[[Marktheidenfeld]] (Bayern)
:[[Marktleuthen]] (Bayern)
:[[Marktoberdorf]] (Bayern)
:[[Marktredwitz]] (Bayern)
:[[Marktsteft]] (Bayern)
:[[Marl]] (Nordrhein-Westfalen)
:[[Marlow]] (Mecklenburg-Vorpommern)
:[[Marne (Holstein)|Marne]] (Schleswig-Holstein)
:[[Marsberg]] (Nordrhein-Westfalen)
:[[Maulbronn]] (Baden-Württemberg)
:[[Maxhütte-Haidhof]] (Bayern)
:[[Mayen]] (Rheinland-Pfalz)
:[[Mechernich]] (Nordrhein-Westfalen)
:[[Meckenheim (Rheinland)|Meckenheim]] (Nordrhein-Westfalen)
:[[Medebach]] (Nordrhein-Westfalen)
| width="400" valign="top" |
:[[Meerane]] (Sachsen)
:[[Meerbusch]] (Nordrhein-Westfalen)
:[[Meersburg]] (Baden-Württemberg)
:[[Meinerzhagen]] (Nordrhein-Westfalen)
:[[Meiningen]] (Thüringen)
:[[Meisenheim]] (Rheinland-Pfalz)
:[[Meißen]] (Sachsen)
:[[Meldorf]] (Schleswig-Holstein)
:[[Melle]] (Niedersachsen)
:[[Mellrichstadt]] (Bayern)
:[[Melsungen]] (Hessen)
:[[Memmingen]] (Bayern)
:[[Menden (Sauerland)]] (Nordrh.-Westf.)
:[[Mendig]] (Rheinland-Pfalz)
:[[Mengen]] (Baden-Württemberg)
:[[Meppen]] (Niedersachsen)
:[[Merkendorf (Mittelfranken)|Merkendorf]] (Bayern)
:[[Merseburg]] (Sachsen-Anhalt)
:[[Merzig]] (Saarland)
:[[Meschede]] (Nordrhein-Westfalen)
:[[Meßkirch]] (Baden-Württemberg)
:[[Meßstetten]] (Baden-Württemberg)
:[[Mettmann]]  (Nordrhein-Westfalen)
:[[Metzingen]] (Baden-Württemberg)
:[[Meuselwitz]] (Thüringen)
:[[Meyenburg (Prignitz)|Meyenburg]] (Brandenburg)
:[[Michelstadt]] (Hessen)
:[[Miesbach]] (Bayern)
:[[Miltenberg]] (Bayern)
:[[Mindelheim]] (Bayern)
:[[Minden]] (Nordrhein-Westfalen)
:[[Mirow]] (Mecklenburg-Vorpommern)
:[[Mittenwalde (Mark)|Mittenwalde]] (Brandenburg)
:[[Mitterteich]] (Bayern)
:[[Mittweida]] (Sachsen)
:[[Möckern]] (Sachsen-Anhalt)
:[[Möckmühl]] (Baden-Württemberg)
:[[Moers]] (Nordrhein-Westfalen)
| width="400" valign="top" |
:[[Mölln]] (Schleswig-Holstein)
:[[Mönchengladbach]] (Nordrhein-Westfalen)
:[[Monheim am Rhein]] (Nordrhein-Westf.)
:[[Monheim (Schwaben)|Monheim]] (Bayern)
:[[Monschau]] (Nordrhein-Westfalen)
:[[Montabaur]] (Rheinland-Pfalz)
:[[Moosburg an der Isar]] (Bayern)
:[[Mörfelden-Walldorf]] (Hessen)
:[[Moringen]] (Niedersachsen)
:[[Mosbach]] (Baden-Württemberg)
:[[Mössingen]] (Baden-Württemberg)
:[[Mücheln (Geiseltal)]] (Sachsen-Anhalt)
:[[Mügeln]] (Sachsen)
:[[Mühlacker]] (Baden-Württemberg)
:[[Mühlberg/Elbe]] (Brandenburg)
:[[Mühldorf am Inn]] (Bayern)
:[[Mühlhausen/Thüringen]] (Thüringen)
:[[Mühlheim am Main]] (Hessen)
:[[Mühlheim an der Donau]] (Baden-Württ.)
:[[Mühltroff]] (Sachsen)
:[[Mülheim an der Ruhr]] (Nordrhein-Westfalen)
:[[Mülheim-Kärlich]] (Rheinland-Pfalz)
:[[Müllheim (Baden)|Müllheim]] (Baden-Württemberg)
:[[Müllrose]] (Brandenburg)
:[[Münchberg]] (Bayern)
:[[Müncheberg]] (Brandenburg)
:[[München]] (Landeshauptstadt von Bayern)
:[[Münchenbernsdorf]] (Thüringen)
:[[Munderkingen]] (Baden-Württemberg)
:[[Münnerstadt]] (Bayern)
:[[Münsingen (Württemberg)|Münsingen]] (Baden-Württemberg)
:[[Munster (Örtze)|Munster]] (Niedersachsen)
:[[Münster (Westfalen)|Münster]] (Nordrhein-Westfalen)
:[[Münstermaifeld]] (Rheinland-Pfalz)
:[[Münzenberg (Hessen)|Münzenberg]] (Hessen)
:[[Murrhardt]] (Baden-Württemberg)
:[[Mutzschen]] (Sachsen)
:[[Mylau]] (Sachsen)
|}
{{TOC}}
===N===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Nabburg]] (Bayern)
:[[Nagold (Stadt)|Nagold]] (Baden-Württemberg)
:[[Naila]] (Bayern)
:[[Nassau (Lahn)|Nassau]] (Rheinland-Pfalz)
:[[Nastätten]] (Rheinland-Pfalz)
:[[Nauen]] (Brandenburg)
:[[Naumburg (Hessen)|Naumburg]] (Hessen)
:[[Naumburg (Saale)]] (Sachsen-Anhalt)
:[[Naunhof]] (Sachsen)
:[[Nebra (Unstrut)]] (Sachsen-Anhalt)
:[[Neckarbischofsheim]] (Baden-Württemberg)
:[[Neckargemünd]] (Baden-Württemberg)
:[[Neckarsteinach]] (Hessen)
:[[Neckarsulm]] (Baden-Württemberg)
:[[Nerchau]] (Sachsen)
:[[Neresheim]] (Baden-Württemberg)
:[[Netphen]] (Nordrhein-Westfalen)
:[[Nettetal]] (Nordrhein-Westfalen)
:[[Netzschkau]] (Sachsen)
:[[Neubrandenburg]] (Mecklenburg-Vorpomm.)
:[[Neubukow]] (Mecklenburg-Vorpommern)
:[[Neubulach]] (Baden-Württemberg)
:[[Neuburg an der Donau]] (Bayern)
:[[Neudenau]] (Baden-Württemberg)
:[[Neuenbürg (Enz)|Neuenbürg]] (Baden-Württemberg)
:[[Neuenburg am Rhein]] (Baden-Württemb.)
:[[Neuenhaus]] (Niedersachsen)
:[[Neuenrade]] (Nordrhein-Westfalen)
:[[Neuenstadt am Kocher]] (Baden-Württemb.)
:[[Neuenstein (Hohenlohe)|Neuenstein]] (Baden-Württemberg)
:[[Neuerburg]] (Rheinland-Pfalz)
:[[Neuffen]] (Baden-Württemberg)
| width="400" valign="top" |
:[[Neugersdorf]] (Sachsen)
:[[Neuhaus am Rennweg]] (Thüringen)
:[[Neu-Isenburg]] (Hessen)
:[[Neukalen]] (Mecklenburg-Vorpommern)
:[[Neukirchen (Knüll)|Neukirchen]] (Hessen)
:[[Neukirchen-Vluyn]] (Nordrhein-Westfalen)
:[[Neukloster]] (Mecklenburg-Vorpommern)
:[[Neumark bei Weimar|Neumark]] (Thüringen)
:[[Neumarkt in der Oberpfalz]] (Bayern)
:[[Neumarkt-Sankt Veit]] (Bayern)
:[[Neumünster]] (Schleswig-Holstein)
:[[Neunburg vorm Wald]] (Bayern)
:[[Neunkirchen (Saar)|Neunkirchen]] (Saarland)
:[[Neuötting]] (Bayern)
:[[Neuruppin]] (Brandenburg)
:[[Neusalza-Spremberg]] (Sachsen)
:[[Neusäß]] (Bayern)
:[[Neuss]] (Nordrhein-Westfalen)
:[[Neustadt an der Aisch]] (Bayern)
:[[Neustadt an der Donau]] (Bayern)
:[[Neustadt an der Waldnaab]] (Bayern)
:[[Neustadt am Kulm]] (Bayern)
:[[Neustadt am Rübenberge]] (Nieders.)
:[[Neustadt an der Orla]] (Thüringen)
:[[Neustadt an der Weinstraße]] (Rh.-Pfalz)
:[[Neustadt bei Coburg]] (Bayern)
:[[Neustadt (Dosse)]] (Brandenburg)
:[[Neustadt-Glewe]] (Mecklenburg-Vorp.)
:[[Neustadt (Hessen)]] (Hessen)
:[[Neustadt in Holstein]] (Schlesw.-Holst.)
:[[Neustadt in Sachsen]] (Sachsen)
:[[Neustrelitz]] (Mecklenburg-Vorpommern)
| width="400" valign="top" |
:[[Neutraubling]] (Bayern)
:[[Neu-Ulm]] (Bayern)
:[[Neuwied]] (Rheinland-Pfalz)
:[[Nidda]] (Hessen)
:[[Niddatal]] (Hessen)
:[[Nidderau]] (Hessen)
:[[Nideggen]] (Nordrhein-Westfalen)
:[[Niebüll]] (Schleswig-Holstein)
:[[Niedenstein]] (Hessen)
:[[Niederkassel]] (Nordrhein-Westfalen)
:[[Niedernhall]] (Baden-Württemberg)
:[[Niederstetten]] (Baden-Württemberg)
:[[Niederstotzingen]] (Baden-Württemb.)
:[[Nieheim]] (Nordrhein-Westfalen)
:[[Niemegk]] (Brandenburg)
:[[Nienburg (Saale)]] (Sachsen-Anhalt)
:[[Nienburg/Weser]] (Niedersachsen)
:[[Niesky]] (Sachsen)
:[[Nittenau]] (Bayern)
:[[Norden (Niedersachsen)|Norden]] (Niedersachsen)
:[[Nordenham]] (Niedersachsen)
:[[Norderney]] (Niedersachsen)
:[[Norderstedt]] (Schleswig-Holstein)
:[[Nordhausen]] (Thüringen)
:[[Nordhorn]] (Niedersachsen)
:[[Nördlingen]] (Bayern)
:[[Northeim]] (Niedersachsen)
:[[Nortorf]] (Schleswig-Holstein)
:[[Nossen]] (Sachsen)
:[[Nürnberg]] (Bayern)
:[[Nürtingen]] (Baden-Württemberg)
|}
{{TOC}}

===O===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Oberasbach]] (Bayern)
:[[Oberhausen]] (Nordrhein-Westfalen)
:[[Oberhof]] (Thüringen)
:[[Oberkirch (Baden)|Oberkirch]] (Baden-Württemberg)
:[[Oberkochen]] (Baden-Württemberg)
:[[Oberlungwitz]] (Sachsen)
:[[Obermoschel]] (Rheinland-Pfalz)
:[[Obernburg am Main]] (Bayern)
:[[Oberndorf am Neckar]] (Baden-Württ.)
:[[Obernkirchen]] (Niedersachsen)
:[[Ober-Ramstadt]] (Hessen)
:[[Oberriexingen]] (Baden-Württemberg)
:[[Obertshausen]] (Hessen)
:[[Oberursel|Oberursel (Taunus)]] (Hessen)
:[[Oberviechtach]] (Bayern)
:[[Oberweißbach/Thür. Wald]] (Thüringen)
:[[Oberwesel]] (Rheinland-Pfalz)
:[[Oberwiesenthal]], Kurort (Sachsen)
:[[Ochsenfurt]] (Bayern)
:[[Ochsenhausen]] (Baden-Württemberg)
:[[Ochtrup]] (Nordrhein-Westfalen)
:[[Oderberg]] (Brandenburg)
:[[Oebisfelde]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Oederan]] (Sachsen)
:[[Oelde]] (Nordrhein-Westfalen)
:[[Oelsnitz (Vogtland)|Oelsnitz]] (Sachsen)
:[[Oelsnitz/Erzgeb.]] (Sachsen)
:[[Oer-Erkenschwick]] (Nordrhein-Westfalen)
:[[Oerlinghausen]] (Nordrhein-Westfalen)
:[[Oestrich-Winkel]] (Hessen)
:[[Oettingen in Bayern]] (Bayern)
:[[Offenbach am Main]] (Hessen)
:[[Offenburg]] (Baden-Württemberg)
:[[Ohrdruf]] (Thüringen)
:[[Öhringen]] (Baden-Württemberg)
:[[Olbernhau]] (Sachsen)
:[[Oldenburg (Oldb)]] (Niedersachsen)
:[[Oldenburg in Holstein]] (Schleswig-Holst.)
:[[Olfen]] (Nordrhein-Westfalen)
:[[Olpe]] (Nordrhein-Westfalen)
:[[Olsberg (Sauerland)|Olsberg]] (Nordrhein-Westfalen)
:[[Oppenau]] (Baden-Württemberg)
:[[Oppenheim]] (Rheinland-Pfalz)
:[[Oranienbaum]] (Sachsen-Anhalt)
:[[Oranienburg]] (Brandenburg)
:[[Orlamünde]] (Thüringen)
| width="400" valign="top" |
:[[Ornbau]] (Bayern)
:[[Ortenberg (Hessen)|Ortenberg]] (Hessen)
:[[Ortrand]] (Brandenburg)
:[[Oschatz]] (Sachsen)
:[[Oschersleben (Bode)]] (Sachsen-Anhalt)
:[[Osnabrück]] (Niedersachsen)
:[[Osterburg (Altmark)]] (Sachsen-Anhalt)
:[[Osterburken]] (Baden-Württemberg)
:[[Osterfeld (bei Naumburg)|Osterfeld]] (Sachsen-Anhalt)
:[[Osterhofen]] (Bayern)
:[[Osterholz-Scharmbeck]] (Niedersachsen)
:[[Osterode am Harz]] (Niedersachsen)
:[[Osterwieck]] (Sachsen-Anhalt)
:[[Ostfildern]] (Baden-Württemberg)
:[[Ostheim vor der Rhön]] (Bayern)
:[[Osthofen]] (Rheinland-Pfalz)
:[[Östringen]] (Baden-Württemberg)
:[[Ostritz]] (Sachsen)
:[[Otterberg]] (Rheinland-Pfalz)
:[[Otterndorf]] (Niedersachsen)
:[[Ottweiler]] (Saarland)
:[[Overath]] (Nordrhein-Westfalen)
:[[Owen (Teck)|Owen]] (Baden-Württemberg)
|}
{{TOC}}

===P===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Paderborn]] (Nordrhein-Westfalen)
:[[Papenburg]] (Niedersachsen)
:[[Pappenheim]] (Bayern)
:[[Parchim]] (Mecklenburg-Vorpommern)
:[[Parsberg]] (Bayern)
:[[Pasewalk]] (Mecklenburg-Vorpommern)
:[[Passau]] (Bayern)
:[[Pattensen]] (Niedersachsen)
:[[Pausa/Vogtl.]] (Sachsen)
:[[Pegau]] (Sachsen)
:[[Pegnitz (Stadt)|Pegnitz]] (Bayern)
:[[Peine]] (Niedersachsen)
:[[Peitz]] (Brandenburg)
:[[Penig]] (Sachsen)
:[[Penkun]] (Mecklenburg-Vorpommern)
:[[Penzberg]] (Bayern)
:[[Penzlin]] (Mecklenburg-Vorpommern)
:[[Perleberg]] (Brandenburg)
:[[Petershagen]] (Nordrhein-Westfalen)
:[[Pfaffenhofen an der Ilm]] (Bayern)
| width="400" valign="top" |
:[[Pfarrkirchen]] (Bayern)
:[[Pforzheim]] (Baden-Württemberg)
:[[Pfreimd]] (Bayern)
:[[Pfullendorf]] (Baden-Württemberg)
:[[Pfullingen]] (Baden-Württemberg)
:[[Pfungstadt]] (Hessen)
:[[Philippsburg]] (Baden-Württemberg)
:[[Pinneberg]] (Schleswig-Holstein)
:[[Pirmasens]] (Rheinland-Pfalz)
:[[Pirna]] (Sachsen)
:[[Plattling]] (Bayern)
:[[Plau am See]] (Mecklenburg-Vorpomm.)
:[[Plaue]] (Thüringen)
:[[Plauen]] (Sachsen)
:[[Plettenberg]] (Nordrhein-Westfalen)
:[[Pleystein]] (Bayern)
:[[Plochingen]] (Baden-Württemberg)
:[[Plön]] (Schleswig-Holstein)
:[[Pocking]] (Bayern)
:[[Pohlheim]] (Hessen)
| width="400" valign="top" |
:[[Polch]] (Rheinland-Pfalz)
:[[Porta Westfalica]] (Nordrhein-Westfalen)
:[[Pößneck]] (Thüringen)
:[[Potsdam]] (Landeshauptst. Brandenburg)
:[[Pottenstein (Bayern)|Pottenstein]] (Bayern)
:[[Preetz (Holstein)|Preetz]] (Schleswig-Holstein)
:[[Premnitz]] (Brandenburg)
:[[Prenzlau]] (Brandenburg)
:[[Pressath]] (Bayern)
:[[Prettin]] (Sachsen-Anhalt)
:[[Pretzsch (Elbe)]] (Sachsen-Anhalt)
:[[Preußisch Oldendorf]] (Nordrhein-Westf.)
:[[Prichsenstadt]] (Bayern)
:[[Pritzwalk]] (Brandenburg)
:[[Prüm]] (Rheinland-Pfalz)
:[[Pulheim]] (Nordrhein-Westfalen)
:[[Pulsnitz]] (Sachsen)
:[[Putbus]] (Mecklenburg-Vorpommern)
:[[Putlitz]] (Brandenburg)
:[[Püttlingen]] (Saarland)
|}
{{TOC}}

===Q===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Quakenbrück]] (Niedersachsen)
:[[Quedlinburg]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Querfurt]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Quickborn (Kreis Pinneberg)|Quickborn]] (Schleswig-Holstein)
|}
{{TOC}}
===R===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Rabenau (Sachsen)|Rabenau]] (Sachsen)
:[[Radeberg]] (Sachsen)
:[[Radebeul]] (Sachsen)
:[[Radeburg]] (Sachsen)
:[[Radegast (Anhalt)|Radegast]] (Sachsen-Anhalt)
:[[Radevormwald]] (Nordrhein-Westfalen)
:[[Radolfzell am Bodensee]] (Baden-Württ.)
:[[Raguhn]] (Sachsen-Anhalt)
:[[Rahden]] (Nordrhein-Westfalen)
:[[Rain (Lech)|Rain]] (Bayern)
:[[Ramstein-Miesenbach]] (Rheinland-Pfalz)
:[[Ranis]] (Thüringen)
:[[Ransbach-Baumbach]] (Rheinland-Pfalz)
:[[Rastatt]] (Baden-Württemberg)
:[[Rastenberg]] (Thüringen)
:[[Rathenow]] (Brandenburg)
:[[Ratingen]] (Nordrhein-Westfalen)
:[[Ratzeburg]] (Schleswig-Holstein)
:[[Rauenberg (Kraichgau)|Rauenberg]] (Baden-Württemberg)
:[[Raunheim]] (Hessen)
:[[Rauschenberg (Hessen)|Rauschenberg]] (Hessen)
:[[Ravensburg]] (Baden-Württemberg)
:[[Ravenstein]] (Baden-Württemberg)
:[[Recklinghausen]] (Nordrhein-Westfalen)
:[[Rees]] (Nordrhein-Westfalen)
:[[Regen (Stadt)|Regen]] (Bayern)
:[[Regensburg]] (Bayern)
:[[Regis-Breitingen]] (Sachsen)
:[[Rehau]] (Bayern)
:[[Rehburg-Loccum]] (Niedersachsen)
:[[Rehna]] (Mecklenburg-Vorpommern)
:[[Reichelsheim (Wetterau)]] (Hessen)
:[[Reichenbach im Vogtland]] (Sachsen)
:[[Reichenbach/O.L.]] (Sachsen)
:[[Reinbek]] (Schleswig-Holstein)
:[[Reinfeld (Holstein)]] (Schleswig-Holstein)
:[[Reinheim]] (Hessen)
| width="400" valign="top" |
:[[Remagen]] (Rheinland-Pfalz)
:[[Remda-Teichel]] (Thüringen)
:[[Remscheid]] (Nordrhein-Westfalen)
:[[Remseck am Neckar]] (Baden-Württemb.)
:[[Renchen]] (Baden-Württemberg)
:[[Rendsburg]] (Schleswig-Holstein)
:[[Rennerod]] (Rheinland-Pfalz)
:[[Renningen]] (Baden-Württemberg)
:[[Rerik]] (Mecklenburg-Vorpommern)
:[[Rethem (Aller)]] (Niedersachsen)
:[[Reutlingen]] (Baden-Württemberg)
:[[Rheda-Wiedenbrück]] (Nordrhein-Westf.)
:[[Rhede]] (Nordrhein-Westfalen)
:[[Rheinau (Baden)|Rheinau]] (Baden-Württemberg)
:[[Rheinbach]] (Nordrhein-Westfalen)
:[[Rheinberg]] (Nordrhein-Westfalen)
:[[Rheine]] (Nordrhein-Westfalen)
:[[Rheinfelden (Baden)]] (Baden-Württemb.)
:[[Rheinsberg]] (Brandenburg)
:[[Rheinstetten]] (Baden-Württemberg)
:[[Rhens]] (Rheinland-Pfalz)
:[[Rhinow]] (Brandenburg)
:[[Ribnitz-Damgarten]] (Mecklenburg-Vorp.)
:[[Richtenberg]] (Mecklenburg-Vorpommern)
:[[Riedenburg]] (Bayern)
:[[Riedlingen]] (Baden-Württemberg)
:[[Rieneck]] (Bayern)
:[[Riesa]] (Sachsen)
:[[Rietberg]] (Nordrhein-Westfalen)
:[[Rinteln]] (Niedersachsen)
:[[Röbel/Müritz]] (Mecklenburg-Vorpommern)
:[[Rochlitz]] (Sachsen)
:[[Rockenhausen]] (Rheinland-Pfalz)
:[[Rodalben]] (Rheinland-Pfalz)
:[[Rodenberg]] (Niedersachsen)
:[[Rödental]] (Bayern)
:[[Rödermark]] (Hessen)
| width="400" valign="top" |
:[[Rodewisch]] (Sachsen)
:[[Rodgau]] (Hessen)
:[[Roding]] (Bayern)
:[[Römhild]] (Thüringen)
:[[Romrod]] (Hessen)
:[[Ronneburg (Thüringen)|Ronneburg]] (Thüringen)
:[[Ronnenberg]] (Niedersachsen)
:[[Rosbach vor der Höhe]] (Hessen)
:[[Rosenfeld (Baden-Württemberg)|Rosenfeld]] (Baden-Württemberg)
:[[Rosenheim]] (Bayern)
:[[Rosenthal (Hessen)|Rosenthal]] (Hessen)
:[[Rösrath]] (Nordrhein-Westfalen)
:[[Roßlau (Elbe)]] (Sachsen-Anhalt)
:[[Roßleben]] (Thüringen)
:[[Roßwein]] (Sachsen)
:[[Rostock]] (Mecklenb.-Vorp. / Hansestadt)
:[[Rotenburg an der Fulda]] (Hessen)
:[[Rotenburg (Wümme)]] (Niedersachsen)
:[[Roth (bei Nürnberg)|Roth]] (Bayern)
:[[Rötha]] (Sachsen)
:[[Röthenbach an der Pegnitz]] (Bayern)
:[[Rothenburg/O.L.]] (Sachsen)
:[[Rothenburg ob der Tauber]] (Bayern)
:[[Rothenfels]] (Bayern)
:[[Rottenburg am Neckar]] (Baden-Württ.)
:[[Rottenburg an der Laaber|Rottenburg a.d.Laaber]] (Bayern)
:[[Röttingen]] (Bayern)
:[[Rottweil]] (Baden-Württemberg)
:[[Rötz]] (Bayern)
:[[Rüdesheim am Rhein]] (Hessen)
:[[Rudolstadt]] (Thüringen)
:[[Ruhla]] (Thüringen)
:[[Ruhland]] (Brandenburg)
:[[Runkel]] (Hessen)
:[[Rüsselsheim]] (Hessen)
:[[Rüthen]] (Nordrhein-Westfalen)
|}
{{TOC}}

===S===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Saalburg-Ebersdorf]] (Thüringen)
:[[Saalfeld/Saale]] (Thüringen)
:[[Saarbrücken]] (Landeshauptst. Saarland)
:[[Saarburg (Rheinland-Pfalz)|Saarburg]] (Rheinland-Pfalz)
:[[Saarlouis]] (Saarland)
:[[Sachsenhagen]] (Niedersachsen)
:[[Sachsenheim]] (Baden-Württemberg)
:[[Salzgitter]] (Niedersachsen)
:[[Salzkotten]] (Nordrhein-Westfalen)
:[[Salzwedel]] (Sachsen-Anhalt)
:[[Sandau (Elbe)]] (Sachsen-Anhalt)
:[[Sandersleben]] (Sachsen-Anhalt)
:[[Sangerhausen]] (Sachsen-Anhalt)
:[[Sankt Andreasberg|Sankt Andreasberg, Bergstadt]] (Nieders.)
:[[Sankt Augustin]] (Nordrhein-Westfalen)
:[[Sankt Goar]] (Rheinland-Pfalz)
:[[Sankt Goarshausen]] (Rheinland-Pfalz)
:[[Sarstedt]] (Niedersachsen)
:[[Sassenberg]] (Nordrhein-Westfalen)
:[[Sassnitz]] (Mecklenburg-Vorpommern)
:[[Sayda]] (Sachsen)
:[[Schafstädt]] (Sachsen-Anhalt)
:[[Schalkau]] (Thüringen)
:[[Schauenstein]] (Bayern)
:[[Scheer]] (Baden-Württemberg)
:[[Scheibenberg]] (Sachsen)
:[[Scheinfeld]] (Bayern)
:[[Schelklingen]] (Baden-Württemberg)
:[[Schenefeld (Kreis Pinneberg)|Schenefeld]] (Schleswig-Holstein)
:[[Scheßlitz]] (Bayern)
:[[Schieder-Schwalenberg]] (NRW)
:[[Schifferstadt]] (Rheinland-Pfalz)
:[[Schildau]], Gneisenaustadt (Sachsen)
:[[Schillingsfürst]] (Bayern)
:[[Schiltach]] (Baden-Württemberg)
:[[Schirgiswalde]] (Sachsen)
:[[Schkeuditz]] (Sachsen)
:[[Schkölen]] (Thüringen)
:[[Schleiden]] (Nordrhein-Westfalen)
:[[Schleiz]] (Thüringen)
:[[Schleswig (Stadt)|Schleswig]] (Schleswig-Holstein)
:[[Schlettau]] (Sachsen)
:[[Schleusingen]] (Thüringen)
:[[Schlieben]] (Brandenburg)
:[[Schlitz (Vogelsbergkreis)|Schlitz]] (Hessen)
:[[Schloß Holte-Stukenbrock]] (NRW)
:[[Schlotheim]] (Thüringen)
:[[Schlüchtern]] (Hessen)
:[[Schlüsselfeld]] (Bayern)
:[[Schmalkalden]] (Thüringen)
:[[Schmallenberg]] (Nordrhein-Westfalen)
:[[Schmölln]] (Thüringen)
:[[Schnackenburg]] (Niedersachsen)
:[[Schnaittenbach]] (Bayern)
:[[Schneeberg (Erzgebirge)|Schneeberg]] (Sachsen)
:[[Schneverdingen]] (Niedersachsen)
:[[Schömberg (bei Balingen)|Schömberg]] (Baden-Württemberg)
:[[Schönau (Odenwald)|Schönau]] (Baden-Württemberg)
:[[Schönau im Schwarzwald]] (Baden-W.)
:[[Schönberg (Mecklenburg)|Schönberg]] (Mecklenburg-Vorp.)
:[[Schönebeck (Elbe)]] (Sachsen-Anhalt)
:[[Schöneck/Vogtl.]] (Sachsen)
:[[Schönewalde]] (Brandenburg)
:[[Schongau]] (Bayern)
:[[Schöningen]] (Niedersachsen)
:[[Schönsee]] (Bayern)
:[[Schönwald (Bayern)|Schönwald]] (Bayern)
| width="400" valign="top" |
:[[Schopfheim]] (Baden-Württemberg)
:[[Schöppenstedt]] (Niedersachsen)
:[[Schorndorf]] (Baden-Württemberg)
:[[Schortens]] (Niedersachsen)
:[[Schotten (Stadt)|Schotten]] (Hessen)
:[[Schramberg]] (Baden-Württemberg)
:[[Schraplau]] (Sachsen-Anhalt)
:[[Schriesheim]] (Baden-Württemberg)
:[[Schrobenhausen]] (Bayern)
:[[Schrozberg]] (Baden-Württemberg)
:[[Schüttorf]] (Niedersachsen)
:[[Schwaan]] (Mecklenburg-Vorpommern)
:[[Schwabach]] (Bayern)
:[[Schwäbisch Gmünd]] (Baden-Württemb.)
:[[Schwäbisch Hall]] (Baden-Württemberg)
:[[Schwabmünchen]] (Bayern)
:[[Schwaigern]] (Baden-Württemberg)
:[[Schwalbach am Taunus]] (Hessen)
:[[Schwalmstadt]] (Hessen)
:[[Schwandorf]] (Bayern)
:[[Schwanebeck]] (Sachsen-Anhalt)
:[[Schwarzenbach am Wald]] (Bayern)
:[[Schwarzenbach an der Saale]] (Bayern)
:[[Schwarzenbek]] (Schleswig-Holstein)
:[[Schwarzenberg/Erzgeb.]] (Sachsen)
:[[Schwarzenborn (Knüll)|Schwarzenborn]] (Hessen)
:[[Schwarzheide]] (Brandenburg)
:[[Schwedt/Oder]] (Brandenburg)
:[[Schweich]] (Rheinland-Pfalz)
:[[Schweinfurt]] (Bayern)
:[[Schwelm]] (Nordrhein-Westfalen)
:[[Schwerin]] (Landeshauptstadt Meckl.-Vorp.)
:[[Schwerte]] (Nordrhein-Westfalen)
:[[Schwetzingen]] (Baden-Württemberg)
:[[Sebnitz]] (Sachsen)
:[[Seehausen (Börde)|Seehausen]] (Sachsen-Anhalt)
:[[Seehausen (Altmark)]] (Sachsen-Anhalt)
:[[Seelow]] (Brandenburg)
:[[Seelze]] (Niedersachsen)
:[[Seesen]] (Niedersachsen)
:[[Sehnde]] (Niedersachsen)
:[[Seifhennersdorf]] (Sachsen)
:[[Selb]] (Bayern)
:[[Selbitz (Oberfranken)|Selbitz]] (Bayern)
:[[Seligenstadt]] (Hessen)
:[[Selm]] (Nordrhein-Westfalen)
:[[Selters (Westerwald)]] (Rheinland-Pfalz)
:[[Senden (Bayern)|Senden]] (Bayern)
:[[Sendenhorst]] (Nordrhein-Westfalen)
:[[Senftenberg]] (Brandenburg)
:[[Seßlach]] (Bayern)
:[[Siegburg]] (Nordrhein-Westfalen)
:[[Siegen]] (Nordrhein-Westfalen)
:[[Sigmaringen]] (Baden-Württemberg)
:[[Simbach am Inn]] (Bayern)
:[[Simmern/ Hunsrück]] (Rheinland-Pfalz)
:[[Sindelfingen]] (Baden-Württemberg)
:[[Singen (Hohentwiel)]] (Baden-Württemb.)
:[[Sinsheim]] (Baden-Württemberg)
:[[Sinzig]] (Rheinland-Pfalz)
:[[Soest]] (Nordrhein-Westfalen)
:[[Solingen]] (Nordrhein-Westfalen)
:[[Solms]] (Hessen)
:[[Soltau]] (Niedersachsen)
:[[Sömmerda]] (Thüringen)
:[[Sondershausen]] (Thüringen)
:[[Sonneberg]] (Thüringen)
| width="400" valign="top" |
:[[Sonnewalde]] (Brandenburg)
:[[Sonthofen]] (Bayern)
:[[Sontra]] (Hessen)
:[[Spaichingen]] (Baden-Württemberg)
:[[Spalt (Stadt)|Spalt]] (Bayern)
:[[Spangenberg (Hessen)|Spangenberg]] (Hessen)
:[[Spenge]] (Nordrhein-Westfalen)
:[[Speyer]] (Rheinland-Pfalz)
:[[Spremberg]] (Brandenburg)
:[[Springe]] (Niedersachsen)
:[[Sprockhövel]] (Nordrhein-Westfalen)
:[[Stade]] (Niedersachsen)
:[[Stadtallendorf]] (Hessen)
:[[Stadthagen]] (Niedersachsen)
:[[Stadtilm]] (Thüringen)
:[[Stadtlengsfeld]] (Thüringen)
:[[Stadtlohn]] (Nordrhein-Westfalen)
:[[Stadtoldendorf]] (Niedersachsen)
:[[Stadtprozelten]] (Bayern)
:[[Stadtroda]] (Thüringen)
:[[Stadtsteinach]] (Bayern)
:[[Stadt Wehlen]] (Sachsen)
:[[Starnberg]] (Bayern)
:[[Staßfurt]] (Sachsen-Anhalt)
:[[Staufen im Breisgau]] (Baden-Württ.)
:[[Staufenberg (Hessen)|Staufenberg]] (Hessen)
:[[Stavenhagen]], Reuterstadt (Meckl.-V.)
:[[St. Blasien]] (Baden-Württemberg)
:[[Stein (Mittelfranken)|Stein]] (Bayern)
:[[Steinach (Thüringen)|Steinach]] (Thüringen)
:[[Steinau an der Straße]] (Hessen)
:[[Steinbach-Hallenberg]] (Thüringen)
:[[Steinbach (Taunus)]] (Hessen)
:[[Steinfurt]] (Nordrhein-Westfalen)
:[[Steinheim an der Murr]] (Baden-Württ.)
:[[Steinheim (Westfalen)|Steinheim]] (Nordrhein-Westfalen)
:[[Stendal]] (Sachsen-Anhalt)
:[[Sternberg]] (Mecklenburg-Vorpommern)
:[[St. Ingbert]] (Saarland)
:[[St. Georgen im Schwarzwald]] (BW)
:[[Stockach]] (Baden-Württemberg)
:[[Stolberg (Harz)]] (Sachsen-Anhalt)
:[[Stolberg (Rhld.)]] (Nordrh.-Westf.)
:[[Stollberg/Erzgeb.]] (Sachsen)
:[[Stolpen]] (Sachsen)
:[[Storkow (Mark)]] (Brandenburg)
:[[Stößen]] (Sachsen-Anhalt)
:[[Straelen]] (Nordrhein-Westfalen)
:[[Stralsund]], Hansestadt (Meckl.-Vorp.)
:[[Strasburg (Uckermark)]] (Meckl.-Vorp.)
:[[Straubing]] (Bayern)
:[[Strausberg]] (Brandenburg)
:[[Strehla]] (Sachsen)
:[[Stromberg (Hunsrück)|Stromberg]] (Rheinland-Pfalz)
:[[Stühlingen]] (Baden-Württemberg)
:[[Stutensee]] (Baden-Württemberg)
:[[Stuttgart]] (Landeshauptst. Baden-W.)
:[[St. Wendel]] (Saarland)
:[[Suhl]] (Thüringen)
:[[Sulingen]] (Niedersachsen)
:[[Sulz am Neckar]] (Baden-Württemberg)
:[[Sulzbach/Saar]] (Saarland)
:[[Sulzbach-Rosenberg]] (Bayern)
:[[Sulzburg]] (Baden-Württemberg)
:[[Sundern (Sauerland)]] (Nordrh.-Westf.)
:[[Süßen]] (Baden-Württemberg)
:[[Syke]] (Niedersachsen)
|}
{{TOC}}

===T===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Tambach-Dietharz/Thür. Wald]] (Thüringen)
:[[Tangerhütte]] (Sachsen-Anhalt)
:[[Tangermünde]] (Sachsen-Anhalt)
:[[Tann (Rhön)]] (Hessen)
:[[Tanna]] (Thüringen)
:[[Tauberbischofsheim]] (Baden-Württemb.)
:[[Taucha]] (Sachsen)
:[[Taunusstein]] (Hessen)
:[[Tecklenburg]] (Nordrhein-Westfalen)
:[[Tegernsee (Stadt)|Tegernsee]] (Bayern)
:[[Telgte]] (Nordrhein-Westfalen)
:[[Teltow]] (Brandenburg)
:[[Templin]] (Brandenburg)
:[[Tengen]] (Baden-Württemberg)
:[[Tessin (bei Rostock)|Tessin]] (Mecklenburg-Vorpommern)
:[[Teterow]] (Mecklenburg-Vorpommern)
:[[Tettnang]] (Baden-Württemberg)
:[[Teublitz]] (Bayern)
:[[Teuchern]] (Sachsen-Anhalt)
:[[Teupitz]]  (Brandenburg)
| width="400" valign="top" |
:[[Teuschnitz]] (Bayern)
:[[Thale]] (Sachsen-Anhalt)
:[[Thalheim/Erzgeb.]] (Sachsen)
:[[Thannhausen (Bayern)|Thannhausen]] (Bayern)
:[[Tharandt]] (Sachsen)
:[[Themar]] (Thüringen)
:[[Thum]] (Sachsen)
:[[Tirschenreuth]] (Bayern)
:[[Titisee-Neustadt]] (Baden-Württemberg)
:[[Tittmoning]] (Bayern)
:[[Todtnau]] (Baden-Württemberg)
:[[Töging am Inn]] (Bayern)
:[[Tönisvorst]] (Nordrhein-Westfalen)
:[[Tönning]] (Schleswig-Holstein)
:[[Torgau]] (Sachsen)
:[[Torgelow]] (Mecklenburg-Vorpommern)
:[[Tornesch]] (Schleswig-Holstein)
:[[Traben-Trarbach]] (Rheinland-Pfalz)
:[[Traunreut]] (Bayern)
| width="400" valign="top" |
:[[Traunstein]] (Bayern)
:[[Trebbin]] (Brandenburg)
:[[Trebsen (Mulde)|Trebsen/Mulde]] (Sachsen)
:[[Treffurt]] (Thüringen)
:[[Trendelburg]] (Hessen)
:[[Treuchtlingen]] (Bayern)
:[[Treuen]] (Sachsen)
:[[Treuenbrietzen]] (Brandenburg)
:[[Triberg im Schwarzwald]] (Baden-Württ.)
:[[Tribsees]] (Mecklenburg-Vorpommern)
:[[Trier]] (Rheinland-Pfalz)
:[[Triptis]] (Thüringen)
:[[Trochtelfingen]] (Baden-Württemberg)
:[[Troisdorf]] (Nordrhein-Westfalen)
:[[Trossingen]] (Baden-Württemberg)
:[[Trostberg]] (Bayern)
:[[Tübingen]] (Baden-Württemberg)
:[[Tuttlingen]] (Baden-Württemberg)
:[[Twistringen]] (Niedersachsen)
|}
{{TOC}}

===U===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Übach-Palenberg]] (Nordrhein-Westfalen)
:[[Überlingen]] (Baden-Württemberg)
:[[Uebigau-Wahrenbrück]] (Brandenburg)
:[[Ueckermünde]] (Mecklenburg-Vorpommern)
:[[Uelzen]] (Niedersachsen)
:[[Uetersen]] (Schleswig-Holstein)
| width="400" valign="top" |
:[[Uffenheim]] (Bayern)
:[[Uhingen]] (Baden-Württemberg)
:[[Ulm]] (Baden-Württemberg)
:[[Ulrichstein]] (Hessen)
:[[Ummerstadt]] (Thüringen)
:[[Unkel]] (Rheinland-Pfalz)
| width="400" valign="top" |
:[[Unna]] (Nordrhein-Westfalen)
:[[Unterschleißheim]] (Bayern)
:[[Usedom (Stadt)|Usedom]] (Mecklenburg-Vorpommern)
:[[Usingen]] (Hessen)
:[[Uslar]] (Niedersachsen)
|}
{{TOC}}
===V===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Vacha]] (Thüringen)
:[[Vaihingen an der Enz]] (Baden-Württemb.)
:[[Vallendar]] (Rheinland-Pfalz)
:[[Varel]] (Niedersachsen)
:[[Vechta]] (Niedersachsen)
:[[Velbert]] (Nordrhein-Westfalen)
:[[Velburg]] (Bayern)
:[[Velden (Pegnitz)|Velden]] (Bayern)
:[[Vellberg]] (Baden-Württemberg)
:[[Vellmar]] (Hessen)
:[[Velten]] (Brandenburg)
:[[Verden (Aller)]] (Niedersachsen)
| width="400" valign="top" |
:[[Veringenstadt]] (Baden-Württemberg)
:[[Versmold]] (Nordrhein-Westfalen)
:[[Vetschau/Spreewald]] (Brandenburg)
:[[Viechtach]] (Bayern)
:[[Vienenburg]] (Niedersachsen)
:[[Viernheim]] (Hessen)
:[[Viersen]] (Nordrhein-Westfalen)
:[[Villingen-Schwenningen]] (Baden-Württemb.)
:[[Vilsbiburg]] (Bayern)
:[[Vilseck]] (Bayern)
:[[Vilshofen an der Donau]] (Bayern)
:[[Visselhövede]] (Niedersachsen)
| width="400" valign="top" |
:[[Vlotho]] (Nordrhein-Westfalen)
:[[Voerde (Niederrhein)]] (Nordrhein-Westf.)
:[[Vogtsburg im Kaiserstuhl]] (B.-Württ.)
:[[Vohburg an der Donau]] (Bayern)
:[[Vohenstrauß]] (Bayern)
:[[Vöhrenbach]] (Baden-Württemberg)
:[[Vöhringen (Schwaben)|Vöhringen]] (Bayern)
:[[Volkach]] (Bayern)
:[[Völklingen]] (Saarland)
:[[Volkmarsen]] (Hessen)
:[[Vreden]] (Nordrhein-Westfalen)
|}
{{TOC}}

===W===
{|
| colspan="3" | 
|-----
| width="35%" valign="top" |
:[[Wachenheim an der Weinstraße]] (Rhl.-Pf.)
:[[Wächtersbach]] (Hessen)
:[[Wadern]] (Saarland)
:[[Waghäusel]] (Baden-Württemberg)
:[[Wahlstedt]] (Schleswig-Holstein)
:[[Waiblingen]] (Baden-Württemberg)
:[[Waibstadt]] (Baden-Württemberg)
:[[Waischenfeld]] (Bayern)
:[[Waldbröl]] (Nordrhein-Westfalen)
:[[Waldeck]] (Hessen)
:[[Waldenbuch]] (Baden-Württemberg)
:[[Waldenburg (Sachsen)|Waldenburg]] (Sachsen)
:[[Waldenburg (Württemberg)|Waldenburg]] (Baden-Württemberg)
:[[Waldershof]] (Bayern)
:[[Waldheim]] (Sachsen)
:[[Waldkappel]] (Hessen)
:[[Waldkirch]] (Baden-Württemberg)
:[[Waldkirchen]] (Bayern)
:[[Waldkraiburg]] (Bayern)
:[[Waldmünchen]] (Bayern)
:[[Waldsassen]] (Bayern)
:[[Waldshut-Tiengen]] (Baden-Württemberg)
:[[Walldorf (Baden)|Walldorf]] (Baden-Württemberg)
:[[Walldürn]] (Baden-Württemberg)
:[[Wallenfels]] (Bayern)
:[[Walsrode]] (Niedersachsen)
:[[Waltershausen]] (Thüringen)
:[[Waltrop]] (Nordrhein-Westfalen)
:[[Wanfried]] (Hessen)
:[[Wangen im Allgäu]] (Baden-Württemberg)
:[[Wanzleben]] (Sachsen-Anhalt)
:[[Warburg]] (Nordrhein-Westfalen)
:[[Waren (Müritz)]] (Mecklenburg-Vorp.)
:[[Warendorf]] (Nordrhein-Westfalen)
:[[Warin]] (Mecklenburg-Vorpommern)
:[[Warstein]] (Nordrhein-Westfalen)
:[[Wassenberg]] (Nordrhein-Westfalen)
:[[Wasserburg am Inn]] (Bayern)
:[[Wassertrüdingen]] (Bayern)
:[[Wasungen]] (Thüringen)
:[[Wedel]] (Schleswig-Holstein)
:[[Weener]] (Niedersachsen)
:[[Wegberg]] (Nordrhein-Westfalen)
:[[Wegeleben]] (Sachsen-Anhalt)
:[[Wehr (Baden)|Wehr]] (Baden-Württemberg)
:[[Weida (Thüringen)|Weida]] (Thüringen)
:[[Weiden in der Oberpfalz]] (Bayern)
:[[Weikersheim]] (Baden-Württemberg)
:[[Weil am Rhein]] (Baden-Württemberg)
:[[Weilburg]] (Hessen)
:[[Weil der Stadt]] (Baden-Württemberg)
:[[Weilheim an der Teck]] (Baden-Württ.)
:[[Weilheim in Oberbayern]] (Bayern)
:[[Weimar]] (Thüringen)
| width="400" valign="top" |
:[[Weingarten (Württemberg)|Weingarten]] (Baden-Württemberg)
:[[Weinheim (Bergstraße)|Weinheim]] (Baden-Württemberg)
:[[Weinsberg]] (Baden-Württemberg)
:[[Weinstadt]] (Baden-Württemberg)
:[[Weismain]] (Bayern)
:[[Weißenberg (Oberlausitz)|Weißenberg]] (Sachsen)
:[[Weißenburg in Bayern]] (Bayern)
:[[Weißenfels]] (Sachsen-Anhalt)
:[[Weißenhorn]] (Bayern)
:[[Weißensee in Thüringen|Weißensee]] (Thüringen)
:[[Weißenstadt]] (Bayern)
:[[Weißenthurm]] (Rheinland-Pfalz)
:[[Weißwasser/O.L.]] (Sachsen)
:[[Weiterstadt]] (Hessen)
:[[Welzheim]] (Baden-Württemberg)
:[[Welzow]] (Brandenburg)
:[[Wemding]] (Bayern)
:[[Wendlingen am Neckar]] (Baden-Württ.)
:[[Werben (Elbe)]] (Sachsen-Anhalt)
:[[Werdau]] (Sachsen)
:[[Werder (Havel)]] (Brandenburg)
:[[Werdohl]] (Nordrhein-Westfalen)
:[[Werl]] (Nordrhein-Westfalen)
:[[Wermelskirchen]] (Nordrhein-Westfalen)
:[[Wernau (Neckar)]] (Baden-Württemberg)
:[[Werne]] (Nordrhein-Westfalen)
:[[Werneuchen]] (Brandenburg)
:[[Wernigerode]] (Sachsen-Anhalt)
:[[Wertheim (Main)|Wertheim]] (Baden-Württemberg)
:[[Werther (Westf.)]] (Nordrhein-Westfalen)
:[[Wertingen]] (Bayern)
:[[Wesel]] (Nordrhein-Westfalen)
:[[Wesenberg (Mecklenburg)|Wesenberg]] (Mecklenburg-Vorpommern)
:[[Wesselburen]] (Schleswig-Holstein)
:[[Wesseling]] (Nordrhein-Westfalen)
:[[Westerburg]] (Rheinland-Pfalz)
:[[Westerland]] (Schleswig-Holstein)
:[[Westerstede]] (Niedersachsen)
:[[Wetter (Ruhr)]] (Nordrhein-Westfalen)
:[[Wetter (Hessen)]] (Hessen)
:[[Wettin]] (Sachsen-Anhalt)
:[[Wetzlar]] (Hessen)
:[[Widdern]] (Baden-Württemberg)
:[[Wiehe]] (Thüringen)
:[[Wiehl]] (Nordrhein-Westfalen)
:[[Wiesbaden]] (Landeshauptstadt Hessen)
:[[Wiesmoor]] (Niedersachsen)
:[[Wiesensteig]] (Baden-Württemberg)
:[[Wiesloch]] (Baden-Württemberg)
:[[Wildberg (Schwarzwald)|Wildberg]] (Baden-Württemberg)
:[[Wildemann]] (Niedersachsen)
:[[Wildenfels]] (Sachsen)
:[[Wildeshausen]] (Niedersachsen)
:[[Wilhelmshaven]] (Niedersachsen)
| width="400" valign="top" |
:[[Wilkau-Haßlau]] (Sachsen)
:[[Willebadessen]] (Nordrhein-Westfalen)
:[[Willich]] (Nordrhein-Westfalen)
:[[Wilsdruff]] (Sachsen)
:[[Wilster]] (Schleswig-Holstein)
:[[Wilthen]] (Sachsen)
:[[Windischeschenbach]] (Bayern)
:[[Windsbach]] (Bayern)
:[[Winnenden]] (Baden-Württemberg)
:[[Winsen (Luhe)]] (Niedersachsen)
:[[Winterberg]] (Nordrhein-Westfalen)
:[[Wipperfürth]] (Nordrhein-Westfalen)
:[[Wirges]] (Rheinland-Pfalz)
:[[Wismar]] (Mecklenb.-Vorp. / Hansestadt)
:[[Wissen (Stadt)|Wissen]] (Rheinland-Pfalz)
:[[Witten]] (Nordrhein-Westfalen)
:[[Wittenberg]], Lutherstadt (Sachsen-Anhalt)
:[[Wittenberge]] (Brandenburg)
:[[Wittenburg]] (Mecklenburg-Vorpommern)
:[[Wittichenau]] (Sachsen)
:[[Wittlich]] (Rheinland-Pfalz)
:[[Wittingen]] (Niedersachsen)
:[[Wittmund]] (Niedersachsen)
:[[Wittstock/Dosse]] (Brandenburg)
:[[Witzenhausen]] (Hessen)
:[[Woldegk]] (Mecklenburg-Vorpommern)
:[[Wolfach]] (Baden-Württemberg)
:[[Wolfen]] (Sachsen-Anhalt)
:[[Wolfenbüttel]] (Niedersachsen)
:[[Wolfhagen]] (Hessen)
:[[Wolframs-Eschenbach]] (Bayern)
:[[Wolfratshausen]] (Bayern)
:[[Wolfsburg]] (Niedersachsen)
:[[Wolfstein]] (Rheinland-Pfalz)
:[[Wolgast]] (Mecklenburg-Vorpommern)
:[[Wolkenstein (Erzgebirge)|Wolkenstein]] (Sachsen)
:[[Wolmirstedt]] (Sachsen-Anhalt)
:[[Wörlitz]] (Sachsen-Anhalt)
:[[Worms]] (Rheinland-Pfalz)
:[[Wörth am Rhein]] (Rheinland-Pfalz)
:[[Wörth an der Donau]] (Bayern)
:[[Wörth am Main]] (Bayern)
:[[Wriezen]] (Brandenburg)
:[[Wülfrath]] (Nordrhein-Westfalen)
:[[Wunsiedel]] (Bayern)
:[[Wunstorf]] (Niedersachsen)
:[[Wuppertal]] (Nordrhein-Westfalen)
:[[Würselen]] (Nordrhein-Westfalen)
:[[Wurzbach]] (Thüringen)
:[[Würzburg]] (Bayern)
:[[Wurzen]] (Sachsen)
:[[Wustrow (Wendland)]] (Niedersachsen)
:[[Wyk auf Föhr]] (Schleswig-Holstein)
|}
{{TOC}}

===X===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Xanten]] (Nordrhein-Westfalen)

| width="400" valign="top" |

| width="400" valign="top" |

|}
{{TOC}}
===Z===
{|
| colspan="3" | 
|-----
| width="400" valign="top" |
:[[Zahna]] (Sachsen-Anhalt)
:[[Zarrentin am Schaalsee]] (Meckl.-Vorp.)
:[[Zehdenick]] (Brandenburg)
:[[Zeil am Main]] (Bayern)
:[[Zeitz]] (Sachsen-Anhalt)
:[[Zell am Harmersbach]] (Baden-Württemb.)
:[[Zell im Wiesental]] (Baden-Württemberg)
:[[Zell (Mosel)]] (Rheinland-Pfalz)
:[[Zella-Mehlis]] (Thüringen)
:[[Zerbst/Anhalt]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Zeulenroda-Triebes]] (Thüringen)
:[[Zeven]] (Niedersachsen)
:[[Ziegenrück]] (Thüringen)
:[[Zierenberg]] (Hessen)
:[[Ziesar]] (Brandenburg)
:[[Zirndorf]] (Bayern)
:[[Zittau]] (Sachsen)
:[[Zöblitz]] (Sachsen)
:[[Zörbig]] (Sachsen-Anhalt)
| width="400" valign="top" |
:[[Zossen]] (Brandenburg)
:[[Zschopau]] (Sachsen)
:[[Zülpich]] (Nordrhein-Westfalen)
:[[Zweibrücken]] (Rheinland-Pfalz)
:[[Zwenkau]] (Sachsen)
:[[Zwickau]] (Sachsen)
:[[Zwiesel]] (Bayern)
:[[Zwingenberg (Bergstraße)|Zwingenberg]] (Hessen)
:[[Zwönitz]] (Sachsen)
