ev,ka,pol;adv1;1. Advent;1. Sonntag im Advent;
ev,ka,pol;adv2;2. Advent;2. Sonntag im Advent;
ev,ka,pol;adv3;3. Advent;3. Sonntag im Advent;
ev,ka,pol;adv4;4. Advent;4. Sonntag im Advent;
ev,ka,pol;xmas0.1224;Heiliger Abend;Heiliger Abend;
ev,  ,pol;xmas0.122418;Christvesper;Heiliger Abend - Christvesper;
ev,  ,pol;xmas0.122422;Christnacht;Heiliger Abend - Christnacht;
ev,ka,pol;xmas1.1225;1. Weihnachstag;Christfest - 1. Feiertag;
ev,ka,pol;xmas2.1226;2. Weihnachtstag;Christfest - 2. Feiertag;
ev,ka,pol;xmas1;1. So.n.Weihn.;1. Sonntag nach dem Christfest;
ev,ka,pol;silv.1231;Sivester;Altjahrsabend: Silvester;
ev,ka,pol;newyear.0101;Neujahrstag;Neujahrstag;
ev,ka,pol;xmas2;2. So.n.Weihn.;2. Sonntag nach dem Christfest;
ev,ka,pol;epi0.0106;Epiph.;Epiphanias;
ev,ka,pol;epi1;1. So.n.Epiph.;1. Sonntag nach Epiphanias;
ev,ka,pol;epi2;2. So.n.Epiph.;2. Sonntag nach Epiphanias;
ev,ka,pol;epi3;3. So.n.Epiph.;3. Sonntag nach Epiphanias;
ev,ka,pol;epi4;4. So.n.Epiph.;4. Sonntag nach Epiphanias;
ev,ka,pol;epi5;5. So.n.Epiph.;5. Sonntag nach Epiphanias;
ev,ka,pol;epi;Letzter So.n.Epiph.;Letzter Sonntag nach Epiphanias;
ev,ka,pol;lent3;Septuagesimä;Septuagesimä: 3. Sonntag vor der Passionszeit;
ev,ka,pol;lent2;Sexagesimä;Sexagesimä: 2. Sonntag vor der Passionszeit;
ev,ka,pol;lent;Estomihi;Estomihi: Sonntag vor der Passionszeit;
ev,ka,pol;fastmo;Rosenmontag;Rosenmontag;
ev,ka,pol;fastdi;Fastnacht;Fastnachtsdienstag;
ev,ka,pol;ashes;Aschermittw.;Aschermittwoch;
ev,ka,pol;lent1;Invokavit;Invokavit: 1. Sonntag der Passionszeit;
ev,ka,pol;lent2;Reminiszere;Reminiszere: 2. Sonntag der Passionszeit;
ev,ka,pol;lent3;Okuli;Okuli: 3. Sonntag der Passionszeit;
ev,ka,pol;lent4;Lätare;Lätare: 4. Sonntag der Passionszeit;
ev,ka,pol;lent5;Judika;Judika: 5. Sonntag der Passionszeit;
ev,ka,pol;lent6;Palmsonntag;Palmsonntag: 6. Sonntag der Passionszeit;
ev,ka,pol;hsupper;Gründonnerstag;Gründonnerstag: Tag der Einsetzung des Abendmahls;
ev,ka,pol;hfriday;Karfreitag;Karfreitag: Tag der Kreuzigung des Herrn;
ev,ka,pol;hsatur;Karsonnabend;Karsonnabend;
ev,ka,pol;east0;Ostersonntag;Ostersonntag: Tag der Auferstehung des Herrn;
ev,ka,pol;eastmon;Ostermontag;Ostermontag;
ev,  ,pol;east1;Quasimodogeniti;Quasimodogeniti: 1. Sonntag nach Ostern;
  ,ka,pol;east1;Weißer Sonntag;Weißer Sonntag;
ev,ka,pol;east2;Miserikordias Dom.;Miserikordias Domini: 2. Sonntag nach Ostern;
ev,ka,pol;east3;Jubilate;Jubilate: 3. Sonntag nach Ostern;
ev,ka,pol;east4;Kantate;Kantate: 4. Sonntag nach Ostern;
ev,ka,pol;east5;Rogate;Rogate: 5. Sonntag nach Ostern;
ev,ka,pol;ascens;Christi Himmelf.;Christi Himmelfahrt;
ev,ka,pol;east6;Exaudi;Exaudi: 6. Sonntag nach Ostern;
ev,ka,pol;pent0;Pfingsten;Pfingstsonntag: Tag der Ausgießung des Heiligen Geistes;
ev,ka,pol;pentmon;Pfingstmontag;Pfingstmontag;
ev,ka,pol;trin;Trinitatis;Trinitatis: Tag der Dreieinigkeit;
ev,ka,pol;trin1;1. So.n.Trin.;1. Sonntag nach Trinitatis;
  ,ka,pol;fronl;Fronleichnam;Fronleichnam;
ev,ka,pol;marasc;Mariä Himmelf.;Mariä Himmelfahrt;
ev,ka,pol;trin2;2. So.n.Trin.;2. Sonntag nach Trinitatis;
ev,ka,pol;trin3;3. So.n.Trin.;3. Sonntag nach Trinitatis;
ev,ka,pol;trin4;4. So.n.Trin.;4. Sonntag nach Trinitatis;
ev,ka,pol;trin5;5. So.n.Trin.;5. Sonntag nach Trinitatis;
ev,ka,pol;trin6;6. So.n.Trin.;6. Sonntag nach Trinitatis;
ev,ka,pol;trin7;7. So.n.Trin.;7. Sonntag nach Trinitatis;
ev,ka,pol;trin8;8. So.n.Trin.;8. Sonntag nach Trinitatis;
ev,ka,pol;trin9;9. So.n.Trin.;9. Sonntag nach Trinitatis;
ev,ka,pol;trin10;10. So.n.Trin.;10. Sonntag nach Trinitatis;
ev,ka,pol;trin11;11. So.n.Trin.;11. Sonntag nach Trinitatis;
ev,ka,pol;trin12;12. So.n.Trin.;12. Sonntag nach Trinitatis;
ev,ka,pol;trin13;13. So.n.Trin.;13. Sonntag nach Trinitatis;
ev,ka,pol;trin14;14. So.n.Trin.;14. Sonntag nach Trinitatis;
ev,ka,pol;trin15;15. So.n.Trin.;15. Sonntag nach Trinitatis;
ev,ka,pol;trin16;16. So.n.Trin.;16. Sonntag nach Trinitatis;
ev,ka,pol;trin17;17. So.n.Trin.;17. Sonntag nach Trinitatis;
ev,ka,pol;trin18;18. So.n.Trin.;18. Sonntag nach Trinitatis;
ev,ka,pol;trin19;19. So.n.Trin.;19. Sonntag nach Trinitatis;
  ,  ,pol;wieder.1003;T.d.Wiedervereinig.;Tag der deutschen Wiedervereinigung;
ev,ka,pol;trin20;20. So.n.Trin.;20. Sonntag nach Trinitatis;
ev,ka,pol;trin21;21. So.n.Trin.;21. Sonntag nach Trinitatis;
ev,ka,pol;trin22;22. So.n.Trin.;22. Sonntag nach Trinitatis;
ev,ka,pol;trin23;23. So.n.Trin.;23. Sonntag nach Trinitatis;
ev,ka,pol;trin24;24. So.n.Trin.;24. Sonntag nach Trinitatis;
ev,ka,pol;martin;Martini;Martinstag;
ev,ka,pol;trin97;3.letzter So.im Kj.;Drittletzter Sonntag des Kirchenjahres;
ev,ka,pol;trin98;Volkstrauertag;Volkstrauertag: Vorletzter Sonntag des Kirchenjahres;
ev,  ,pol;prayer;Buß- und Bettag;Buß- und Bettag;
ev,  ,   ;trin99;Ewigkeitssonntag;Ewigkeitssonntag: / Letzter Sonntag des Kirchenjahres;
  ,ka,pol;trin99;Totensonntag;Totensonntag: / Letzter Sonntag des Kirchenjahres;
ev,ka,pol;thanks;Erntedankfest;Erntedankfest;
ev,  ,pol;reform.1031;Reformationstag;Reformationstag: 31. Oktober;
ev,  ,   ;konfi;Konfirmation;Konfirmation;
ev,  ,   ;kirchw;Kirchweihe;Kirchweihe;
ev,  ,   ;unity;f.d.Einheit d.K.;Bittgottesdienst um die Einheit der Kirche;
ev,  ,   ;evang;f.d.Ausbr. d.Ev.;Bittgottesdienst um die Ausbreitung des Evangeliums;
ev,  ,   ;peace;f.d.Frieden;Bittgottesdienst um Frieden;
ev,ka,   ;steph.1226;Stephanus;26. Dezember, Tag des Erzmärtyrers Stephanus;
ev,ka,   ;child.1228;Unsch. Kinder;28. Dezember, Tag der unschuldigen Kinder;
ev,ka,pol;newyear.0101;Jesu Darst.;1. Januar, Tag der Beschneidung und Namensgebung Jesu;
ev,ka,pol;lichtm.0202;Lichtmess;2. Februar, Tag der Darstellung des Herrn (Lichtmess);
ev,ka,   ;marann.0325;Mariä Ankünd.;25. März, Tag der Ankündigung der Geburt des Herrn;
ev,ka,pol;johann.0624;Johannis;24. Juni, Tag der Geburt Johannes des Täufers;
ev,ka,pol;pepa.0629;Peter+Paul;29. Juni, Tag der Apostel Petrus und Paulus;
ev,ka,   ;marheim.0702;Mariä Heims.;2. Juli, Tag der Heimsuchung Mariä;
ev,ka,pol;michael.0929;Michaelis;29. September, Tag des Erzengels Michael und aller Engel;
ev,ka,pol;halow.1101;Allerheiligen;1. November, Gedenktag der Heiligen;
ev,ka,pol;halos.1102;Allerseelen;Allerseelen;
